Repository nest/nest-simulator, pull requests merged in 2018-08, with the labels that each got.

#951 Update platform specific CMake file so it can be used with CMake 3.11.1
  cmake/Platform/Fujitsu-Sparc64.cmake
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#993 Fix 990 / Compilation issues with C++11 and libc++
  CMakeLists.txt
  cmake/DefaultCompilerFlags.cmake
  models/aeif_cond_alpha_multisynapse.cpp
  models/aeif_cond_beta_multisynapse.cpp
  models/iaf_psc_alpha_multisynapse.cpp
  models/iaf_psc_exp_multisynapse.cpp
  nestkernel/nest_types.h
  nestkernel/recordables_map.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Critical, T: Maintenance

#995 fixed minor issue in WeightRecorderEvent
  nestkernel/event.h
Labels: C: Model, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#998 Shuts off the warnings from LLVM/Clang 4.0.0
  models/siegert_neuron.cpp
Labels: C: Model, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#999 Adjust send_recv_count_target_data_
  nestkernel/mpi_manager.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: High, T: Maintenance

#997 Fix version display during startup
  extras/create_rcsinfo.sh
  lib/sli/sli-init.sli
  pynest/nest/pynest-init.sli
Labels: C: Infrastructure, I: No breaking change, I: User Interface, P: PR Created, S: Low, T: Maintenance

#1005 Mark more skipped SLI tests as skipped, not success
  examples/nest/music/spike_exporter.sli
  examples/nest/music/three_neurons_threaded_receivenest.sli
  examples/nest/music/three_neurons_threaded_sendnest.sli
  lib/sli/unittest.sli
  testsuite/regressiontests/issue-410.sli
  testsuite/regressiontests/ticket-349.sli
  testsuite/regressiontests/ticket-433.sli
  testsuite/regressiontests/ticket-466.sli
  testsuite/selftests/test_crash_or_die.sli
  testsuite/selftests/test_failbutnocrash_or_die_crash.sli
  testsuite/selftests/test_failbutnocrash_or_die_pass.sli
  testsuite/selftests/test_passorfailbutnocrash_or_die.sli
  testsuite/unittests/test_count_connections.sli
  testsuite/unittests/test_gif_cond_exp.sli
  testsuite/unittests/test_gif_cond_exp_multisynapse.sli
  testsuite/unittests/test_multimeter_accu.sli
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1000 Removing pointless comparison with uint
  nestkernel/connector_base.h
  nestkernel/mpi_manager.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1004 Fix compatibility issues with Python 2
  doc/model_details/HillTononiModels.ipynb
  pynest/examples/brunel_alpha_evolution_strategies.py
  pynest/examples/hh_psc_alpha.py
  pynest/examples/sinusoidal_gamma_generator.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: High, T: Maintenance

#1007 Clean up modification of dynamic recordables map in models
  models/aeif_cond_alpha_multisynapse.cpp
  models/aeif_cond_beta_multisynapse.cpp
  models/iaf_psc_alpha_multisynapse.cpp
  models/iaf_psc_exp_multisynapse.cpp
  nestkernel/recordables_map.h
Labels: C: Model, I: No breaking change, P: Pending, S: Low, T: Maintenance

#1003 Resize Connector vectors when adding connection models
  models/modelsmodule.cpp
  nestkernel/model_manager.cpp
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Critical, T: Bug

#1008 Do not use the -Wall option on K computer
  cmake/ProcessOptions.cmake
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1020 small bugfix in test_stdp_multiplicity.py
  pynest/nest/tests/test_stdp_multiplicity.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: High, T: Bug
