Repository nest/nest-simulator, pull requests merged in 2018-07, with the labels that each got.

#976 Fix SLI sleep function (fixes #973)
  lib/sli/sli-init.sli
  sli/slicontrol.cc
  sli/slicontrol.h
Labels: C: Interpreter, I: No breaking change, P: PR Created, S: High, T: Maintenance

#978 keep conductance positive in gif_cond_exp model
  models/gif_cond_exp.cpp
  testsuite/unittests/test_cond_exp_models.sli
Labels: C: Model, I: Behavior changes, P: PR Created, S: High, T: Bug

#932 Update document on build of application on K computer frontend
  INSTALL
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Maintenance
