Repository nest/nest-simulator, pull requests merged in 2018-12, with the labels that each got.

#1057 build using clang and gcc compilers
  .travis.yml
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1068 MyModule example missing Event methods
  examples/MyModule/drop_odd_spike_connection.h
  examples/MyModule/pif_psc_alpha.cpp
Labels: C: Installation, I: No breaking change, P: PR Created, S: High, T: Bug

#1050 Update description of rate model neurons and change parameter names
  models/gauss_rate.h
  models/lin_rate.h
  models/rate_neuron_ipn.h
  models/rate_neuron_ipn_impl.h
  models/rate_neuron_opn.h
  models/rate_neuron_opn_impl.h
  models/sigmoid_rate.h
  models/sigmoid_rate_gg_1998.h
  models/tanh_rate.h
  models/threshold_lin_rate.h
  pynest/examples/lin_rate_ipn_network.py
  pynest/examples/rate_neuron_dm.py
  pynest/nest/tests/test_rate_copy_model.py
  pynest/nest/tests/test_rate_instantaneous_and_delayed.py
  pynest/nest/tests/test_rate_neuron.py
  pynest/nest/tests/test_rate_neuron_communication.py
  testsuite/mpitests/test_rate_neurons_mpi.sli
Labels: C: Model, I: User Interface, P: PR Created, S: High, T: Maintenance

#1086 Fix header installation and multiplicity handling in MyModule
  examples/MyModule/pif_psc_alpha.cpp
  libnestutil/CMakeLists.txt
Labels: C: Installation, C: Model, I: No breaking change, P: PR Created, S: High, T: Bug

#1019 Make testsuite run when nosetests is unavailable
  pynest/nest/tests/test_all.py
  pynest/nest/tests/test_connect_all_patterns.py
  pynest/nest/tests/test_connect_distributions.py
  pynest/nest/tests/test_connect_parameters.py
  pynest/nest/tests/test_mc_neuron.py
  pynest/nest/tests/test_sp/test_all.py
  pynest/nest/tests/test_split_simulation.py
  topology/pynest/tests/test_all.py
  topology/pynest/tests/test_spatial_kernels.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: High, T: Bug

#1081 Source code comment blocks refactored
  examples/MyModule/drop_odd_spike_connection.h
  examples/MyModule/pif_psc_alpha.h
  precise/iaf_psc_exp_ps_lossless.h
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1038 Create iaf_cond_beta
  models/CMakeLists.txt
  models/iaf_cond_beta.cpp
  models/iaf_cond_beta.h
  models/modelsmodule.cpp
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
Labels: C: Model, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1054 nest.Disconnect parameters are consistent with documentation
  pynest/nest/lib/hl_api_connections.py
  pynest/nest/tests/test_sp/test_disconnect.py
  pynest/nest/tests/test_sp/test_disconnect_multiple.py
Labels: C: PyNEST, I: No breaking change, P: PR Created, S: High, T: Bug
