Repository nest/nest-simulator, pull requests merged in 2018-06, with the labels that each got.

#948 Obtain help pager information via SLI and handle failures better
  pynest/nest/lib/hl_api_helper.py
Labels: C: Interpreter, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#966 Fix #825: Improve sign check
  models/vogels_sprekeler_connection.h
Labels: C: Model, I: Behavior changes, P: PR Created, S: High, T: Enhancement

#970 Fixes #967: Correct parameter in documentation
  models/spike_generator.h
Labels: C: Documentation, I: No breaking change, P: PR Created, S: High, T: Bug

#962 Improve documentation on setting extent and center (addresses #961)
  topology/doc/Topology_UserManual.pdf
  topology/doc/Topology_UserManual.tex
Labels: C: Kernel, I: No breaking change, P: PR Created, S: High, T: Maintenance

#965 Fix #949: NEST help files (hlp, html) should end with newline
  extras/help_generator/writers.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#964 Nest developer space: Description for conversion to 5g
  .gitignore
  index.md
  model_conversion_5g.md
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Critical, T: Maintenance
