Repository nest/nest-simulator, pull requests merged in 2018-09, with the labels that each got.

#986 moved Travis-CI build script to `extras` directory
  .travis.yml
  extras/parse_travis_log.py
  extras/static_code_analysis.sh
  extras/travis_build.sh
Labels: C: Infrastructure, I: No breaking change, P: In progess, S: Low, T: Maintenance

#1009 Fix C++17 issues
  models/correlation_detector.cpp
  models/correlomatrix_detector.cpp
  models/correlospinmatrix_detector.cpp
  nestkernel/dynamicloader.cpp
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1012 Add skip_if_without_music to nest dictionary
  lib/sli/sli-init.sli
  lib/sli/unittest.sli
Labels: C: Interpreter, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1024 Use configured instead of standard Python executable
  examples/run_examples.sh
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Bug

#1030 Use reverse iterator in get_history
  nestkernel/archiving_node.cpp
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1033 Remove emacs support for SLI
  .gitignore
  CMakeLists.txt
  README.md
  debian/emacsen-install.ex
  debian/emacsen-remove.ex
  debian/emacsen-startup.ex
  debian/rules
  examples/sli/nestrc.sli
  extras/CMakeLists.txt
  extras/EditorSupport/emacs/postscript-sli.el
  extras/EditorSupport/emacs/psvn.el
  extras/EditorSupport/emacs/sli.el.in
  extras/README.md
  lib/sli/helpinit.sli
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1023 Prevent execution of --debug and --verbosity options as files
  lib/sli/sli-init.sli
  testsuite/regressiontests/issue-779-1016.py
Labels: C: Interpreter, I: Behavior changes, P: PR Created, S: High, T: Bug

#1029 Move ConnectionManager methods from impl to h
  nestkernel/connection_manager.h
  nestkernel/connection_manager_impl.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1032 Remove outdated release-making script
  CMakeLists.txt
  extras/create_release.sh.in
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance
