Repository nest/nest-simulator, pull requests merged in 2018-04, with the labels that each got.

#890 Add 'install-nodoc' target for make
  CMakeLists.txt
  INSTALL
  doc/CMakeLists.txt
  extras/help_generator/README.md
  extras/help_generator/generate_help.py
  extras/help_generator/helpers.py
  extras/help_generator/writers.py
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#917 cmake -Dwith-ltdl=<path-to-libtool> fix
  cmake/ProcessOptions.cmake
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: High, T: Bug

#914 Fix issue #911
  testsuite/regressiontests/ticket-659-copyright.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#927 Documentation of inhomogeneous_poisson_generator
  models/inhomogeneous_poisson_generator.h
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#913 Return help text
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_info.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#789 Major change in the installation and testing of packages using multiple python versions
  .travis.yml
  build.sh
  csa_install.sh
  extras/install_csa-libneurosim.sh
  extras/install_music.sh
  extras/parse_travis_log.py
  pynest/nest/tests/test_sp/test_disconnect.py
  testsuite/unittests/test_unused_names.py
Labels: C: Installation, I: No breaking change, P: PR Created, S: High, T: Enhancement

#823 Add gamma kernel in topology
  topology/doc/Topology_UserManual.tex
  topology/topology_names.cpp
  topology/topology_names.h
  topology/topology_parameter.h
  topology/topologymodule.cpp
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#930 Updated Topology User Manual for NEST 2.16.
  topology/doc/Topology_UserManual.pdf
  topology/doc/Topology_UserManual.tex
  topology/doc/make_manual.sh
  topology/doc/user_manual_figures/conn1.png
  topology/doc/user_manual_figures/conn2.png
  topology/doc/user_manual_figures/conn3.png
  topology/doc/user_manual_figures/conn4.png
  topology/doc/user_manual_figures/conn5.png
  topology/doc/user_manual_figures/conn6.png
  topology/doc/user_manual_figures/conn_3d.png
  topology/doc/user_manual_figures/layer1.png
  topology/doc/user_manual_figures/layer2.png
  topology/doc/user_manual_figures/layer3.png
  topology/doc/user_manual_figures/layer3a.png
  topology/doc/user_manual_figures/layer4.png
  topology/doc/user_manual_figures/layer4_3d.png
  topology/doc/user_manual_figures/player.png
  topology/doc/user_manual_figures/vislayer.png
Labels: C: Documentation, I: No breaking change, P: PR Created, S: High, T: Maintenance

#929 Added test for spatial kernels in topology (depends on #823).
  testsuite/unittests/test_unused_names.py
  topology/pynest/tests/test_all.py
  topology/pynest/tests/test_spatial_kernels.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: High, T: Maintenance

#928 Fixed issue in help
  pynest/nest/lib/hl_api_helper.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#943 Added warning against bad use of Rank()
  pynest/nest/lib/hl_api_parallel_computing.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance
