Repository nest/nest-simulator, pull requests merged in 2019-01, with the labels that each got.

#1089 Remove unused variables
  nestkernel/conn_builder.cpp
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1078 Handle number_of_connections<1 in topology
  topology/connection_creator.cpp
  topology/connection_creator_impl.h
Labels: C: Kernel, I: Behavior changes, P: PR Created, S: High, T: External bug

#1105 Added mpi multiplicity test
  testsuite/mpitests/test_multiplicity.sli
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1101 local_spike_counter takes multiplicity into account
  nestkernel/event_delivery_manager_impl.h
  testsuite/regressiontests/issue-1100.sli
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Bug

#1084 Fix static linking of modules
  cmake/ProcessOptions.cmake
Labels: C: Installation, I: No breaking change, P: PR Created, S: High, T: Bug
