Repository nest/nest-simulator, pull requests merged in 2019-06, with the labels that each got.

#1197 Fixed normalization factor for iaf_cond_beta
  models/iaf_cond_beta.cpp
Labels: C: Model, I: No breaking change, P: PR Created, S: High, T: Bug

#1116 Add ostream operator template for std::vectors
  libnestutil/streamers.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1216 Change target directory for doxygen from source to build
  doc/fulldoc.conf.in
  doc/normaldoc.conf.in
Labels: C: Installation, I: Behavior changes, P: PR Created, S: Low, T: Bug

#952 Make stdp_facetshw synapse consistent with the temporal fix for STDP numerical imprecision
  models/stdp_connection_facetshw_hom.h
Labels: C: Model, I: Behavior changes, P: PR Created, S: Low, T: Maintenance

#1170 CMake option and documentation for using the Intel compiler
  CMakeLists.txt
  INSTALL
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  doc/installation/install_options.rst
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1183 Travis build on OSX
  .travis.yml
  extras/travis_build.sh
  pynest/do_tests.py.in
  pynest/nest/tests/test_regression_issue-1034.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: High, T: Enhancement

#1221 Update parallel computing docs regarding configuration
  doc/guides/parallel_computing.rst
  doc/guides/random_numbers.rst
  doc/installation/linux_install.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: High, T: Maintenance

#1223 Make version information consistent
  CMakeLists.txt
  INSTALL
  cmake/CPackVariables.cmake
  cmake/NestVersionInfo.cmake
  cmake/ProcessOptions.cmake
  doc/CMakeLists.txt
  doc/fulldoc.conf.in
  doc/normaldoc.conf.in
  doc/set_rcsinfo.cmake.in
  extras/CMakeLists.txt
  extras/check_copyright_headers.py
  extras/create_rcsinfo.sh
  extras/nest-config.in
  lib/sli/sli-init.sli
  libnestutil/config.h.in
  pynest/nest/pynest-init.sli
  pynest/setup.py.in
  sli/slistartup.cc
  sli/slistartup.h
  testsuite/do_tests.sh.in
  topology/setup.py.in
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: High, T: Maintenance

#1225 Fix uninitialized variable in iaf_psc_exp
  models/iaf_psc_exp.cpp
Labels: C: Model, I: Behavior changes, P: PR Created, S: High, T: Bug

#1234 Documentation update for #1177 ("Increase maximum line length in source code formatting style from 80 to 120")
  coding_guidelines_c++.md
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1233 Fix multiple definition of rho build complain observed on AArch64 with FCC
  topology/topology_names.cpp
  topology/topology_names.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: High, T: Bug

#1227 Update links to model directory in docs
  doc/index.rst
  doc/models/devices.rst
  doc/models/neurons.rst
  doc/models/synapses.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1204 Add conda-forge installation documentation for Linux and MacOSX
  doc/_static/css/custom.css
  doc/_static/css/pygments.css
  doc/_static/img/import_nest.png
  doc/conf.py
  doc/installation/conda_install.rst
  doc/installation/index.rst
  doc/installation/mac_install.rst
Labels: C: Installation, I: No breaking change, P: PR Created, S: High, T: Enhancement

#1230 Fix up dependencies in Ubuntu install instructions
  doc/installation/index.rst
  doc/installation/linux_install.rst
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1228 Cleanup for the K computer specific CMake file for v2.18
  cmake/Platform/Fujitsu-Sparc64.cmake
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1218 Fix nest_vars in case of undefined PYTHONPATH
  extras/nest_vars.sh.in
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Maintenance
