Repository nest/nest-simulator, pull requests merged in 2019-08, with the labels that each got.

#1243 Unify coeffarray_as_d and coeffarray_as_uint via Union
  nestkernel/event.h
Labels: C: Kernel, I: Internal API, P: PR Created, S: Low, T: Maintenance

#1268 Fix typo in doc - random_numbers
  doc/guides/random_numbers.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1263 Remove the remaining markdown config in docs
  doc/conf.py
  doc/tutorials/videos/index.rst
  doc/tutorials/videos/one_neuron.md
  doc/tutorials/videos/one_neuron.rst
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1260 Add initial membrane potential options to microcircuit example
  examples/nest/Potjans_2014/microcircuit.sli
  examples/nest/Potjans_2014/network_params.sli
  pynest/examples/Potjans_2014/network.py
  pynest/examples/Potjans_2014/network_params.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1254 Fix logical error in elseif-statements in connect functions
  nestkernel/connection_manager.cpp
  testsuite/regressiontests/issue-1242.sli
Labels: C: Kernel, I: No breaking change, P: PR Created, S: High, T: Bug

#1270 Remove spurious brackets from code example in tutorial
  doc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: High, T: Bug

#1266 Allow specifying arrays of values in the synapse specification when connecting with fixed_total_number
  pynest/nest/lib/hl_api_connections.py
Labels: C: PyNEST, I: No breaking change, P: PR Created, S: High, T: Enhancement
