Repository nest/nest-simulator, pull requests merged in 2019-09, with the labels that each got.

#1281 Fix example in nest-3 cheatsheet
  doc/nest-3/cheatsheet.md
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1287 Use shape as argument instead of columns/rows/depth and update topology examples to NEST3
  pynest/examples/spatial/README
  pynest/examples/spatial/conncomp.py
  pynest/examples/spatial/conncon_sources.py
  pynest/examples/spatial/conncon_targets.py
  pynest/examples/spatial/connex.py
  pynest/examples/spatial/connex_ew.py
  pynest/examples/spatial/ctx_2n.py
  pynest/examples/spatial/gaussex.py
  pynest/examples/spatial/grid_iaf.py
  pynest/examples/spatial/grid_iaf_irr.py
  pynest/examples/spatial/grid_iaf_oc.py
  pynest/examples/spatial/hill_tononi_Vp.py
  pynest/examples/spatial/test_3d.py
  pynest/examples/spatial/test_3d_exp.py
  pynest/examples/spatial/test_3d_gauss.py
  pynest/nest/lib/hl_api_connections.py
  pynest/nest/lib/hl_api_nodes.py
  pynest/nest/random/hl_api_random.py
  pynest/nest/spatial/hl_api_spatial.py
  topology/connection_creator.cpp
  topology/connection_creator.h
  topology/grid_layer.h
  topology/grid_mask.h
  topology/layer.cpp
  topology/position.h
  topology/topology_names.cpp
  topology/topology_names.h
  topology/topologymodule.cpp
Labels: C: PyNEST, I: User Interface, P: PR Created, S: Low, T: Enhancement

#1273 Add include sys/time.h.
  nestkernel/simulation_manager.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1295 Remove merge leftovers
  pynest/examples/Potjans_2014/example.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1267 Fast static check in Travis CI
  .travis.yml
  doc/conf.py
  extras/check_code_style.sh
  extras/static_code_analysis.sh
  extras/travis_build.sh
  pynest/nest/tests/test_weight_recorder.py
  topology/doc/insert.py
  topology/pynest/hl_api.py
  topology/pynest/tests/test_basics.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Enhancement
