Repository nest/nest-simulator, pull requests merged in 2019-10, with the labels that each got.

#1300 Skip deployment in Travis CI testsuite when not running a build
  .travis.yml
Labels: C: Infrastructure, S: Critical, S: High

#1255 Files needed to build Debian packages (.deb)
  debian/README
  debian/changelog
  debian/compat
  debian/control
  debian/copyright
  debian/cron.d.ex
  debian/dirs
  debian/docs
  debian/info
  debian/init.d.ex
  debian/manpage.1.ex
  debian/manpage.sgml.ex
  debian/manpage.xml.ex
  debian/menu.ex
  debian/nest-default.ex
  debian/nest.doc-base.EX
  debian/nest.postinst
  debian/postinst.ex
  debian/postrm.ex
  debian/preinst.ex
  debian/prerm.ex
  debian/rules
  debian/source/format
  debian/watch.ex
Labels: C: Installation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1297 Updated/extended macOS install instructions
  doc/installation/mac_install.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: High, T: Enhancement

#865 Add STDP synapses with nearest-neighbor spike pairing schemes
  models/CMakeLists.txt
  models/modelsmodule.cpp
  models/stdp_nn_pre-centered_connection.h
  models/stdp_nn_restr_connection.h
  models/stdp_nn_symm_connection.h
  nestkernel/archiving_node.cpp
  nestkernel/archiving_node.h
  nestkernel/node.cpp
  nestkernel/node.h
  pynest/nest/tests/test_all.py
  pynest/nest/tests/test_stdp_nn_synapses.py
  testsuite/unittests/test_common_props_setting.sli
Labels: C: Model, I: Internal API, P: PR Created, S: Low, T: Enhancement

#1311 Fix formatting in test_stdp_nn_synapses.py
  pynest/nest/tests/test_stdp_nn_synapses.py
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1314 Update DOI and release buttons in README; add Zenodo reference to NEST 2.18.0
  README.md
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Critical, T: Enhancement

#1308 Use an unsigned data type for thread in spike data
  nestkernel/spike_data.h
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1310 Switch to GCC8 as default in continuous integration tests on Travis
  .travis.yml
  doc/installation/install_options.rst
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Maintenance
