Repository nest/nest-simulator, pull requests merged in 2019-07, with the labels that each got.

#1240 Fix pynest installation instructions
  pynest/README.md
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1235 Update FindLibNeurosim to take Python version into account
  cmake/FindLibNeurosim.cmake
Labels: C: Infrastructure, I: Internal API, P: PR Created, S: High, T: Maintenance

#1256 Fix namespaces in Hodgkin-Huxley neuron models
  models/hh_cond_beta_gap_traub.cpp
  models/hh_cond_exp_traub.cpp
  models/hh_psc_alpha.cpp
  models/hh_psc_alpha.h
  models/hh_psc_alpha_clopath.cpp
  models/hh_psc_alpha_clopath.h
  models/hh_psc_alpha_gap.cpp
  models/hh_psc_alpha_gap.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  pynest/examples/hh_phaseplane.py
Labels: C: Model, I: Internal API, P: PR Created, S: Low, T: Maintenance
