Repository nest/nest-simulator, pull requests merged in 2020-03, with the labels that each got.

#1376 Identify changed files for static code analysis using git diff for PRs
  extras/travis_build.sh
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: Low, T: Bug

#1395 Changed EnableStructuralPlasticity documentation to address issue #571
  nestkernel/nestmodule.cpp
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1446 Update Mac manual link
  doc/installation/index.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1458 Correctly initialize result vector in music_rate_in_proxy::get_status()
  models/music_rate_in_proxy.cpp
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Critical, T: Bug

#1396 Improve documentation and location of iaf_chxk_2008 model
  models/CMakeLists.txt
  models/modelsmodule.cpp
  nestkernel/node.h
  precise/CMakeLists.txt
  precise/iaf_chxk_2008.cpp
  precise/iaf_chxk_2008.h
  precise/precisemodule.cpp
Labels: C: Model, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1341 Update issue templates (bugs/features)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Enhancement

#1418 Add links to the new NEST virtual machine
  doc/download.rst
  doc/installation/livemedia.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1443 Count local devices for each thread
  nestkernel/node_manager.cpp
  nestkernel/node_manager.h
  nestkernel/target_table_devices.cpp
  pynest/nest/tests/test_regression_issue-1409.py
Labels: C: Kernel, I: No breaking change, P: PR Created, S: Critical, T: Bug

#1425 Fix python 3.8.0 attribute error: module 'cgi' has no attribute 'escape'
  extras/help_generator/generate_help.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1460 Move "Editor support" from README into documentation
  README.md
  doc/contribute/index.rst
  doc/contribute/templates_styleguides/vim_support_sli.rst
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1466 Use theme options to show logo on readthedocs
  doc/_static/css/custom.css
  doc/conf.py
Labels: C: Documentation, I: No breaking change, P: PR Created, S: Low, T: Bug

#1407 Refactor beta normalization factor calculation into function
  libnestutil/CMakeLists.txt
  libnestutil/beta_normalization_factor.h
  models/aeif_cond_beta_multisynapse.cpp
  models/hh_cond_beta_gap_traub.cpp
  models/ht_neuron.cpp
  models/iaf_cond_beta.cpp
Labels: C: Model, I: No breaking change, P: PR Created, S: Low, T: Maintenance

#1411 Update the conda environment to create the documentation locally
  doc/README.rst
  doc/conda_environment.yml
  doc/nest_doc_conda_env.yml
Labels: C: Infrastructure, I: No breaking change, P: PR Created, S: High, T: Maintenance
