Repository nest/nest-simulator, pull requests merged in 2020-11, with the labels that each got.

#1814 Add documentation for CollocatedSynapses
  doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
  pynest/nest/lib/hl_api_types.py
Labels: I: No breaking change, S: High, T: Maintenance

#1770 Revise PyNEST documentation for GetStatus and get()
  pynest/nest/lib/hl_api_info.py
  pynest/nest/lib/hl_api_types.py
Labels: I: No breaking change, S: Normal, T: Bug

#1825 Add description for "Two neuron example"
  pynest/examples/one_neuron.py
  pynest/examples/twoneurons.py
Labels: I: No breaking change, S: Normal, T: Enhancement

#1826 Fix int/float data type check
  nestkernel/conn_builder.cpp
  nestkernel/conn_builder.h
Labels: I: No breaking change, S: High, T: Bug

#1807 Add tests for receptor_type with CollocatedSynapses
  pynest/nest/tests/test_multiple_synapses.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1715 Efficient initialization of membrane potentials with original and optimized conditions in Potjans_2014
  pynest/examples/Potjans_2014/network.py
  pynest/examples/Potjans_2014/network_params.py
  pynest/examples/Potjans_2014/readme.md
Labels: I: Behavior changes, S: Normal, T: Enhancement

#1762 Update PyNEST README to reStructuredText and fix broken link in documentation
  doc/installation/compilation_options.rst
  doc/installation/pynest_readme_link.rst
  pynest/README.md
  pynest/README.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#1824 Fix typo in IMapFunction::backtrace
  sli/sliarray.cc
Labels: I: No breaking change, S: Normal, T: Bug

#1823 Update PyNEST template code to reference current nest 3 code.
  doc/contribute/templates_styleguides/pynest_api_template.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1793 Fix SetKernelStatus examples in documentation
  doc/faqs/faqs.rst
  doc/guides/running_simulations.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1518 Fix sphinx-build warnings
  doc/README.rst
  doc/citing-nest.rst
  doc/contribute/mailing_list_guidelines.rst
  doc/contribute/templates_styleguides/example_template.rst
  doc/contribute/templates_styleguides/pyapi_template.rst
  doc/contribute/templates_styleguides/vim_support_sli.rst
  doc/examples/index.rst
  doc/faqs/index.rst
  doc/features.rst
  doc/glossary.rst
  doc/guides/conngen_interface.rst
  doc/guides/index.rst
  doc/guides/nest2_to_nest3/nest2_to_nest3_detailed_transition_guide.rst
  doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
  doc/guides/running_simulations.rst
  doc/guides/spatial/guide_spatially_structured_networks.rst
  doc/guides/spatial/pynest.rst
  doc/installation/index.rst
  doc/sli_docs/an-introduction-to-sli.rst
  doc/sli_docs/first-steps.rst
  doc/sli_docs/neural-simulations.rst
  doc/sli_docs/objects-and-data-types.rst
  doc/sli_docs/programming-in-sli.rst
  doc/sli_docs/using-files-and-keyboard-input.rst
  doc/tutorials/music_tutorial/music_tutorial_parrot.rst
  doc/tutorials/music_tutorial/music_tutorial_setlatency.rst
  doc/tutorials/music_tutorial/music_tutorial_sli.rst
  doc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
  pynest/examples/glif_cond_neuron.py
  pynest/examples/glif_psc_neuron.py
  pynest/examples/spatial/connex_ew.py
  pynest/examples/spatial/hill_tononi_Vp.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1740 Changes to volume transmitter documentation
  models/volume_transmitter.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1806 Add description for SIONlib file format to backend documentation
  doc/_static/img/Node_distribution.png
  doc/_static/img/nest_sionlib_file_format_v2.png
  doc/guides/parallel_computing.rst
  doc/guides/recording_from_simulations.rst
  doc/img/nest_sionlib_file_format_v2.png
  doc/img/nest_sionlib_file_format_v2.svg
  doc/installation/compilation_options.rst
  nestkernel/recording_backend_ascii.h
  nestkernel/recording_backend_sionlib.h
Labels: I: No breaking change, S: Normal, T: Enhancement

#1845 Fix NEST3 transition guide formatting
  doc/guides/nest2_to_nest3/nest2_to_nest3_detailed_transition_guide.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1852 Parse C++ warnings more specifically
  .travis.yml
  extras/parse_travis_log.py
  extras/travis_build.sh
  nestkernel/mpi_manager.cpp
  nestkernel/music_manager.cpp
  nestkernel/spatial.cpp
Labels: I: No breaking change, S: Critical, T: Maintenance

#1838 Add documentation on array indexing
  doc/guides/connection_management.rst
  doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
  nestkernel/nest.cpp
  pynest/nest/lib/hl_api_connection_helpers.py
  pynest/nest/lib/hl_api_connections.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1830 Refactor conngen module to be a ConnBuilder
  CMakeLists.txt
  cmake/FindLibNeurosim.cmake
  cmake/ProcessOptions.cmake
  conngen/CMakeLists.txt
  conngen/conngen.h
  conngen/conngendatum.cpp
  conngen/conngendatum.h
  conngen/conngenmodule.cpp
  conngen/conngenmodule.h
  conngen/sli/conngen-interface.sli
  doc/conf.py
  doc/fulldoc.conf.in
  doc/guides/connection_management.rst
  doc/guides/conngen_interface.rst
  doc/guides/index.rst
  doc/guides/nest2_to_nest3/nest2_to_nest3_detailed_transition_guide.rst
  doc/installation/compilation_options.rst
  doc/normaldoc.conf.in
  examples/nest/conngen_interface.sli
  extras/help_generator/conf.py
  extras/include_checker.py
  extras/install_csa-libneurosim.sh
  extras/parse_travis_log.py
  extras/travis_build.sh
  lib/sli/nest-init.sli
  nest/neststartup.cpp
  nest/neststartup.h
  nestkernel/CMakeLists.txt
  nestkernel/conn_builder.cpp
  nestkernel/conn_builder.h
  nestkernel/conn_builder_conngen.cpp
  nestkernel/conn_builder_conngen.h
  nestkernel/nest_datums.h
  nestkernel/nestmodule.cpp
  nestkernel/nestmodule.h
  pynest/examples/csa_example.py
  pynest/examples/csa_spatial_example.py
  pynest/nest/hl_api.py
  pynest/nest/lib/hl_api_connections.py
  pynest/nest/tests/test_all.py
  pynest/nest/tests/test_connect_conngen.py
  pynest/nest/tests/test_csa.py
Labels: I: Behavior changes, S: Normal, T: Maintenance

#1812 Return all values when using get() on a SynapseCollection with more than one synapse
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_types.py
  pynest/nest/tests/test_synapsecollection.py
Labels: I: No breaking change, S: Normal, T: Bug

#1836 Improve printing of SynapseCollections
  doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
  pynest/nest/lib/hl_api_types.py
  pynest/nest/tests/test_synapsecollection.py
Labels: I: No breaking change, S: Normal, T: Maintenance
