Repository nest/nest-simulator, pull requests merged in 2020-06, with the labels that each got.

#1573 Add min_rate to specify a non-zero rectfying rate for rate neuron models with input noise (rate_neuron_ipn)
  models/gauss_rate.h
  models/lin_rate.h
  models/rate_neuron_ipn.h
  models/rate_neuron_ipn_impl.h
  models/rate_neuron_opn_impl.h
  models/sigmoid_rate.h
  models/sigmoid_rate_gg_1998.h
  models/tanh_rate.h
  models/threshold_lin_rate.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
Labels: I: Behavior changes, S: Normal, T: Enhancement

#1533 Fix synaptic time constants in model documentation
  models/aeif_cond_alpha.h
  models/aeif_cond_alpha_multisynapse.h
  models/aeif_cond_beta_multisynapse.h
  models/aeif_cond_exp.h
  models/aeif_psc_alpha.h
  models/aeif_psc_delta.h
  models/aeif_psc_delta_clopath.h
  models/aeif_psc_exp.h
  models/gamma_sup_generator.h
  models/gauss_rate.h
  models/gif_psc_exp.h
  models/gif_psc_exp_multisynapse.h
  models/ht_connection.h
  models/iaf_cond_beta.h
  models/iaf_cond_exp.h
  models/iaf_cond_exp_sfa_rr.h
  models/iaf_psc_exp.h
Labels: I: No breaking change, S: High, T: Bug

#1497 Allow direct conversion from NodeCollection to numpy
  pynest/nest/lib/hl_api_types.py
  pynest/nest/tests/test_NodeCollection.py
Labels: I: No breaking change, S: Normal, T: Enhancement

#1614 Fix Python compatibility issue on Readthedocs
  doc/conf.py
Labels: I: No breaking change, S: Critical, T: Bug

#1639 Remove scrollbars from parameters and other tables on RTD
  doc/_static/css/custom.css
Labels: I: No breaking change, S: Normal, T: Maintenance

#1448 Initialize indicator for changes to connectivity to false
  nestkernel/connection_manager.cpp
Labels: I: No breaking change, S: High, T: Bug

#1647 Add "Acknowledgements" section to v2.20.1 welcome page
  doc/_static/img/EBRAINS.svg
  doc/_static/img/HBP.png
  doc/index.rst
Labels: I: No breaking change, S: High, T: Maintenance

#1515 Add information about nest_vars.sh and update Linux installation instructions
  doc/installation/linux_install.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#1597 Add documentation on converting from PSC to PSP
  models/iaf_psc_exp.h
  models/iaf_psc_exp_htum.h
  models/iaf_psc_exp_multisynapse.h
  pynest/examples/Potjans_2014/helpers.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1646 Add "Acknowledgements" section to welcome page
  doc/_static/img/EBRAINS.svg
  doc/_static/img/HBP.png
  doc/index.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1624 Fix technical typos and spelling
  models/correlospinmatrix_detector.h
  models/gif_cond_exp_multisynapse.h
  models/gif_pop_psc_exp.h
  models/hh_cond_beta_gap_traub.h
  models/hh_cond_exp_traub.h
  models/hh_psc_alpha.h
  models/hh_psc_alpha_clopath.h
  models/hh_psc_alpha_gap.h
  models/ht_neuron.h
  models/iaf_cond_alpha.h
  models/iaf_cond_alpha_mc.h
  models/iaf_cond_beta.h
  models/iaf_cond_exp.h
  models/iaf_cond_exp_sfa_rr.h
  models/iaf_psc_alpha.h
  models/iaf_psc_delta.h
  models/iaf_psc_exp.h
  models/iaf_psc_exp_htum.h
  models/izhikevich.h
  models/mat2_psc_exp.h
  models/noise_generator.h
  models/sinusoidal_gamma_generator.h
  precise/iaf_chxk_2008.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1587 Improved parsing of PyNEST test results and list of failed tests
  .travis.yml
  cmake/ProcessOptions.cmake
  extras/parse_travis_log.py
  testsuite/CMakeLists.txt
  testsuite/cpptests/run_all.cpp
  testsuite/do_tests.sh.in
  testsuite/junit_xml.sh
  testsuite/run_test.sh
  testsuite/summarize_tests.py
Labels: I: No breaking change, S: High, T: Bug

#1644 Update model documentation output directory
  .gitignore
  doc/conf.py
  doc/contents.rst
  doc/guides/recording_from_simulations.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1638 Refer to Vim syntax highlighting
  doc/sli_docs/an-introduction-to-sli.rst
Labels: I: No breaking change, S: Normal, T: Enhancement
