Repository nest/nest-simulator, pull requests merged in 2020-05, with the labels that each got.

#1491 Change definition of realtime factor in print_time
  doc/guides/running_simulations.rst
  nestkernel/simulation_manager.cpp
Labels: I: Behavior changes, S: Normal, T: Enhancement

#1550 Add CMake switch for enabling/disabling the recording backend for Arbor
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  libnestutil/config.h.in
  nestkernel/CMakeLists.txt
  nestkernel/io_manager.cpp
  nestkernel/mpiutil.h
  nestkernel/mpiutil_impl.h
  nestkernel/recording_backend_arbor.cpp
  nestkernel/recording_backend_arbor.h
  pynest/examples/arbor_cosim_example/arbor_proxy.py
  pynest/examples/arbor_cosim_example/nest_sender.py
  sli/slistartup.cc
  sli/slistartup.h
  testsuite/do_tests.sh.in
Labels: I: No breaking change, S: High, T: Bug

#1576 Re-organizing the travis build stages
  .travis.yml
Labels: T: Discussion

#1490 Update readthedocs style sheet to improve text contrast
  doc/_static/css/custom.css
Labels: I: No breaking change, S: Normal, T: Maintenance

#1559 Mention mutual exclusivity of MUSIC and Arbor in documentation
  doc/tutorials/music_tutorial/music_tutorial_1.rst
  doc/tutorials/music_tutorial/music_tutorial_2.rst
  doc/tutorials/music_tutorial/music_tutorial_3.rst
  doc/tutorials/music_tutorial/music_tutorial_4.rst
  doc/tutorials/music_tutorial/music_tutorial_parrot.rst
  doc/tutorials/music_tutorial/music_tutorial_setlatency.rst
  doc/tutorials/music_tutorial/music_tutorial_sli.rst
  doc/tutorials/music_tutorial/music_tutorial_tips.rst
  pynest/examples/music_cont_out_proxy_example/nest_script.py
  pynest/examples/music_cont_out_proxy_example/receiver_script.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1577 Silence startup
  nestkernel/model_manager.cpp
  nestkernel/rng_manager.cpp
Labels: I: No breaking change, S: Normal, T: Maintenance

#1567 Update documentation on adding spatial masks in user-defined modules
  doc/guides/spatial/guide_spatially_structured_networks.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1561 Remove redundant setting of environment variables
  CMakeLists.txt
  cmake/ProcessOptions.cmake
  extras/nest_vars.sh.in
  extras/travis_build.sh
  testsuite/do_tests.sh.in
Labels: I: No breaking change, S: Normal, T: Maintenance

#1580 Move JunitXML and run_test functions to their own files
  testsuite/CMakeLists.txt
  testsuite/do_tests.sh.in
  testsuite/junit_xml.sh
  testsuite/run_test.sh
Labels: I: No breaking change, S: Normal, T: Maintenance

#1472 Final updates in documentation and the debian package for v2.20.1
  debian/changelog
  debian/control
  debian/copyright
  debian/rules
  doc/contribute/mailing_list_guidelines.rst
  doc/download.rst
  doc/installation/index.rst
  doc/tutorials/topology/hill_tononi_Vp.ipynb
  doc/tutorials/topology/hill_tononi_Vp.py
  doc/tutorials/topology/hill_tononi_Vp.rst
Labels: I: No breaking change, S: High, T: Maintenance

#1602 Fixed minimal typo in user documentation.
  models/ht_neuron.h
Labels: I: No breaking change, S: Normal, T: Bug

#1526 Copy the current Microcuircit documentation for use with Readthedocs
  .gitignore
  doc/_static/img/microcircuit.png
  doc/conf.py
  doc/examples/index.rst
  doc/examples/pynest_microcircuit.rst
  doc/examples/pynest_microcircuit_link.rst
  doc/index.rst
  doc/microcircuit/api_potjans/helpers.rst
  doc/microcircuit/api_potjans/modules.rst
  doc/microcircuit/api_potjans/network.rst
  doc/microcircuit/api_potjans/network_params.rst
  doc/microcircuit/example.py
  doc/microcircuit/example.rst
  doc/microcircuit/index.rst
  doc/microcircuit/network_params.rst
  doc/microcircuit/sim_params.py
  doc/microcircuit/sim_params.rst
  doc/microcircuit/stimulus_params.py
  doc/microcircuit/stimulus_params.rst
  pynest/examples/Potjans_2014/README.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#1591 Convert exact-integration.ipynb to rst file
  doc/guides/exact-integration.rst
  doc/guides/index.rst
  doc/model_details/exact-integration.ipynb
Labels: I: No breaking change, S: Normal, T: Maintenance

#1606 Remove "Documentation" label from documentation issue template
  .github/ISSUE_TEMPLATE/documentation_improvement.md
Labels: I: No breaking change, S: Normal, T: Maintenance

#1474 Enables display of commands with default settings in the `.nestrc `
  pynest/nest/lib/hl_api_helper.py
Labels: I: No breaking change, S: High, T: Bug

#1608 Update syn_spec when a synapse parameter is list and we use fixed_total_number
  pynest/nest/lib/hl_api_connection_helpers.py
  pynest/nest/tests/test_weights_as_lists.py
Labels: I: No breaking change, S: High, T: Bug

#1605 Fix subscripts in ginzburg_neuron model documentation
  models/ginzburg_neuron.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1613 Correct path
  doc/documentation_workflow/user_documentation_workflow.rst
Labels: I: No breaking change, S: Normal, T: Bug
