Repository nest/nest-simulator, pull requests merged in 2020-07, with the labels that each got.

#1578 Clean up handling of path-related environment variables
  doc/guides/spatial/guide_spatially_structured_networks.rst
  doc/installation/linux_install.rst
  examples/nest/ReadData_demo.dat
  examples/nest/ReadData_demo.sli
  extras/nest-config.in
  extras/nest_vars.sh.in
  libnestutil/config.h.in
  nestkernel/dynamicloader.cpp
  nestkernel/rng_manager.cpp
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_info.py
  pynest/nest/lib/hl_api_simulation.py
  sli/slistartup.cc
  sli/slistartup.h
  testsuite/do_tests.sh.in
Labels: I: No breaking change, S: Normal, T: Bug

#1658 Fixed rendering of kernel parameter documentation in PyNEST
  pynest/nest/lib/hl_api_simulation.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1410 Update Debian installation instructions
  doc/installation/index.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1521 Fix default parameters of siegert_neuron
  models/siegert_neuron.cpp
  models/siegert_neuron.h
  pynest/nest/tests/test_siegert_neuron.py
Labels: I: Behavior changes, S: Normal, T: Maintenance

#1632 Update description for parameter U in Tsodyks synapses
  models/tsodyks2_connection.h
  models/tsodyks_connection.h
  models/tsodyks_connection_hom.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1626 Fix Izhikevich model initial conditions
  models/izhikevich.cpp
Labels: I: Behavior changes, S: Normal, T: Enhancement

#1654 Remove unused CMake options
  CMakeLists.txt
Labels: I: No breaking change, S: Normal, T: Maintenance

#1671 Fix wrong connection in STDP NN unit test
  pynest/nest/tests/test_stdp_nn_synapses.py
Labels: I: No breaking change, S: High, T: Bug

#1668 Remove orphaned and unmaintained bibliography file
  extras/CMakeLists.txt
  extras/bibliography/nest.bib
Labels: I: No breaking change, S: Normal, T: Maintenance

#1653 Update docstring, add comments, and minor refactoring of Create()
  pynest/nest/lib/hl_api_nodes.py
  pynest/nest/tests/test_create.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1656 Add documentation how to install NEST via homebrew
  doc/installation/index.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#1617 Systematize multiline strings for message text in hl_api
  pynest/nest/lib/hl_api_connection_helpers.py
  pynest/nest/lib/hl_api_connections.py
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_info.py
  pynest/nest/lib/hl_api_nodes.py
  pynest/nest/lib/hl_api_spatial.py
  pynest/nest/lib/hl_api_types.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1592 Update doc/model_details notebooks to work with NEST 3.0
  doc/model_details/HillTononiModels.ipynb
  doc/model_details/IAF_neurons_singularity.ipynb
  doc/model_details/aeif_models_implementation.ipynb
  doc/model_details/noise_generator.ipynb
  doc/model_details/test_post_trace.ipynb
Labels: I: No breaking change, S: High, T: Bug

#1324 Update copyright file in debian directory
  debian/copyright
Labels: I: No breaking change, S: Normal, T: Maintenance

#1598 Systematize error messages for Connect failures
  nestkernel/conn_builder.cpp
  nestkernel/conn_builder.h
  nestkernel/connection.h
  nestkernel/connection_manager.cpp
  nestkernel/node.cpp
  nestkernel/universal_data_logger.h
  pynest/nest/tests/test_onetooneconnect.py
  topology/connection_creator.cpp
  topology/connection_creator_impl.h
Labels: I: No breaking change, S: Normal, T: Enhancement

#1690 Bump Python version for macOS build
  .travis.yml
  extras/travis_build.sh
Labels: I: No breaking change, S: Critical, T: Maintenance

#1636 Fix GetConnections to correctly get connections with devices as sources when specifying only target
  nestkernel/connection_manager.cpp
  pynest/nest/tests/test_getconnections.py
Labels: I: No breaking change, S: High, T: Bug

#1666 Convert conngen documentation to a proper guide
  conngen/README.md
  doc/CMakeLists.txt
  doc/conngen/conngen.txt
  doc/guides/conngen_interface.rst
  doc/guides/index.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1700 Update to latest Python on MacOS Travis CI build
  .travis.yml
  extras/travis_build.sh
Labels: I: Internal API, S: Critical, T: Maintenance

#1623 Autodetect Python include path and library file instead of hardcoding them
  .travis.yml
  extras/travis_build.sh
Labels: I: No breaking change, S: High, T: Bug

#1693 Minor update to conngen documentation
  doc/guides/conngen_interface.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1680 Clarify conda installation with MPI
  doc/installation/index.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#1695 Fix issues when showing plots in examples
  pynest/examples/BrodyHopfield.py
  pynest/examples/brunel_alpha_nest.py
  pynest/examples/brunel_delta_nest.py
  pynest/examples/brunel_exp_multisynapse_nest.py
  pynest/examples/gif_population.py
  pynest/examples/one_neuron.py
  pynest/examples/repeated_stimulation.py
  pynest/examples/twoneurons.py
Labels: I: Internal API, S: Normal, T: Maintenance
