Repository nest/nest-simulator, pull requests merged in 2021-06, with the labels that each got.

#2040 Add documentation on parameter comparators
  doc/userdoc/guides/nest2_to_nest3/nest3_features/parametrization.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#2037 Fix failing assert when connecting spatial populations
  nestkernel/ntree_impl.h
  testsuite/unittests/test_ntree_split.sli
Labels: I: No breaking change, S: High, T: Bug

#1986 Add a NEST documentation style guide
  doc/userdoc/contribute/index.rst
  doc/userdoc/contribute/styleguide/sample_doc.rst
  doc/userdoc/contribute/styleguide/styleguide.rst
  doc/userdoc/contribute/styleguide/vim_support_sli.rst
  doc/userdoc/contribute/templates/example_template.rst
  doc/userdoc/contribute/templates/pyapi_template.rst
  doc/userdoc/contribute/templates/pynest_api_template.py
  doc/userdoc/contribute/templates/pynest_example_template.py
  doc/userdoc/documentation_workflow/user_documentation_workflow.rst
  doc/userdoc/glossary.rst
  doc/userdoc/installation/configuration.rst
  doc/userdoc/static/css/custom.css
Labels: I: No breaking change, S: Normal, T: Enhancement

#2066 Removed outdated CMake options
  CMakeLists.txt
  cmake/ProcessOptions.cmake
  doc/userdoc/installation/cmake_options.rst
  libnestutil/config.h.in
  nestkernel/kernel_manager.h
  sli/parser.cc
  sli/sliarray.cc
  sli/slicontrol.cc
Labels: I: No breaking change, S: Normal, T: Maintenance

#2061 Add a brief description of features of NEST 3.0 to its index
  doc/userdoc/guides/nest2_to_nest3/index.rst
Labels: I: No breaking change, S: High, T: Maintenance

#2068 Rename Stimulating{Backend,Device} to Stimulation{Backend,Device}
  doc/devdoc/static/img/MPI_backend_state_Nest.svg
  doc/devdoc/static/ulmet/MPI_backend_state_Nest.uxf
  doc/userdoc/guides/nest2_to_nest3/nest3_features/stimulation_backends.rst
  doc/userdoc/guides/stimulate_the_network.rst
  doc/userdoc/sli_docs/neural-simulations.rst
  doc/userdoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  models/ac_generator.cpp
  models/ac_generator.h
  models/dc_generator.cpp
  models/dc_generator.h
  models/gamma_sup_generator.cpp
  models/gamma_sup_generator.h
  models/inhomogeneous_poisson_generator.cpp
  models/inhomogeneous_poisson_generator.h
  models/mip_generator.cpp
  models/mip_generator.h
  models/noise_generator.cpp
  models/noise_generator.h
  models/poisson_generator.cpp
  models/poisson_generator.h
  models/poisson_generator_ps.cpp
  models/poisson_generator_ps.h
  models/ppd_sup_generator.cpp
  models/ppd_sup_generator.h
  models/pulsepacket_generator.cpp
  models/pulsepacket_generator.h
  models/sinusoidal_gamma_generator.cpp
  models/sinusoidal_gamma_generator.h
  models/sinusoidal_poisson_generator.cpp
  models/sinusoidal_poisson_generator.h
  models/spike_dilutor.h
  models/spike_generator.cpp
  models/spike_generator.h
  models/step_current_generator.cpp
  models/step_current_generator.h
  models/step_rate_generator.cpp
  models/step_rate_generator.h
  nestkernel/CMakeLists.txt
  nestkernel/io_manager.cpp
  nestkernel/io_manager.h
  nestkernel/io_manager_impl.h
  nestkernel/pseudo_recording_device.h
  nestkernel/recording_backend_mpi.h
  nestkernel/simulation_manager.cpp
  nestkernel/stimulation_backend.h
  nestkernel/stimulation_backend_mpi.cpp
  nestkernel/stimulation_backend_mpi.h
  nestkernel/stimulation_device.cpp
  nestkernel/stimulation_device.h
  pynest/examples/Potjans_2014/network.py
  pynest/examples/recording_demo.py
  testsuite/regressiontests/issue-264.sli
  testsuite/regressiontests/ticket-737.sli
Labels: I: Internal API, S: Critical, T: Maintenance

#2030 Add functions to access information about simulation time
  nestkernel/simulation_manager.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1503 Remove NEST 3.0 preview warnings
  doc/userdoc/conf.py
  doc/userdoc/download.rst
Labels: I: No breaking change, P: Blocked, S: Critical, T: Maintenance

#2065 Correct documentation of local_spike_counter.
  pynest/nest/lib/hl_api_simulation.py
Labels: I: No breaking change, S: High, T: Bug

#1998 Fix nest-server not starting with apt-installed uwsgi
  doc/userdoc/nest_server.rst
  extras/nest-server
Labels: I: No breaking change, S: Normal, T: Bug

#1959 Add support for different virtual environment types for Python
  CMakeLists.txt
  cmake/ProcessOptions.cmake
  doc/userdoc/installation/linux_install.rst
  doc/userdoc/installation/mac_install.rst
  extras/ConnPlotter/setup.py
  pynest/CMakeLists.txt
  pynest/setup.py.in
Labels: I: No breaking change, S: Normal, T: Enhancement

#2072 Update citation information
  README.md
  doc/userdoc/citing-nest.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#2077 Fix build log parser failed test list
  .github/workflows/nestbuildmatrix.yml
  extras/conda-nest-simulator-dev.yml
  testsuite/summarize_tests.py
Labels: I: No breaking change, S: Normal, T: Bug

#2080 Fixed `PYEXECDIR`
  CMakeLists.txt
  cmake/ProcessOptions.cmake
Labels: I: No breaking change, S: High, T: Bug

#2078 Adding Static code analysis in github actions
  .github/workflows/nestbuildmatrix.yml
  .travis.yml
  extras/gha_build.sh
  extras/travis_build.sh
Labels: I: No breaking change, S: Critical, T: Maintenance
