Repository nest/nest-simulator, pull requests merged in 2021-09, with the labels that each got.

#2131 Only call `set_connections_have_changed()` from thread 0
  nestkernel/connection_manager.cpp
  testsuite/pytests/test_regression_issue-2125.py
Labels: T: Bug, S: High, I: No breaking change

#2124 Update Python version check in __init__.py to check for minor version, and to report correct minimum required version (>= 3.8)
  CMakeLists.txt
  pynest/CMakeLists.txt
  pynest/nest/__init__.py.in
Labels: I: Internal API

#2127 Run Python tests using Pytest, reorganize MPI-based Python tests and improve error reporting.
  .github/workflows/nestbuildmatrix.yml
  extras/conda-nest-simulator-dev.yml
  pynest/examples/brunel_exp_multisynapse_nest.py
  testsuite/do_tests.sh
  testsuite/pytests/connect_test_base.py
  testsuite/pytests/mpi/2/connect_test_base.py
  testsuite/pytests/mpi/2/test_connect_all_to_all.py
  testsuite/pytests/mpi/2/test_connect_arrays_mpi.py
  testsuite/pytests/mpi/2/test_connect_fixed_indegree.py
  testsuite/pytests/mpi/2/test_connect_fixed_outdegree.py
  testsuite/pytests/mpi/2/test_connect_fixed_total_number.py
  testsuite/pytests/mpi/2/test_connect_one_to_one.py
  testsuite/pytests/mpi/2/test_connect_pairwise_bernoulli.py
  testsuite/pytests/mpi/2/test_connect_symmetric_pairwise_bernoulli.py
  testsuite/pytests/mpi/2/test_issue_576.py
  testsuite/pytests/mpi/4/test_consistent_local_vps.py
  testsuite/pytests/mpi/README.md
  testsuite/pytests/mpitest_get_local_vps.py
  testsuite/pytests/test_connect_all_to_all.py
  testsuite/pytests/test_connect_fixed_indegree.py
  testsuite/pytests/test_connect_fixed_outdegree.py
  testsuite/pytests/test_connect_fixed_total_number.py
  testsuite/pytests/test_connect_helpers.py
  testsuite/pytests/test_connect_one_to_one.py
  testsuite/pytests/test_connect_pairwise_bernoulli.py
  testsuite/pytests/test_connect_parameters.py
  testsuite/pytests/test_connect_symmetric_pairwise_bernoulli.py
  testsuite/pytests/test_mpitests.py
  testsuite/pytests/test_sp/mpitest_issue_578_sp.py
  testsuite/pytests/test_sp/test_disconnect.py
  testsuite/summarize_tests.py
Labels: T: Bug, S: Critical, I: No breaking change

#2143 Backport documentation for built-in and detailed timers
  extras/userdoc/md/documentation/built-in_timers.md
Labels: T: Enhancement, S: Normal, I: Internal API

#2141 Replace the `Vose` class with `std::discrete_distribution`
  nestkernel/CMakeLists.txt
  nestkernel/connection_creator.h
  nestkernel/connection_creator_impl.h
  nestkernel/random_generators.h
  nestkernel/vose.cpp
  nestkernel/vose.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2145 Automatically flag issues and pull-requests as stale
  .github/workflows/stale.yml
Labels: T: Enhancement, S: Normal

#2121 Fix use of thread-specific distributions in random parameters
  .github/workflows/nestbuildmatrix.yml
  extras/check_code_style.sh
  extras/ci_build.sh
  extras/static_code_analysis.sh
  lib/sli/sli-init.sli
  lib/sli/unittest.sli
  nestkernel/connection_creator_impl.h
  nestkernel/parameter.cpp
  nestkernel/parameter.h
  testsuite/mpitests/issue-2119.sli
Labels: T: Bug, S: High, I: No breaking change

#2076 Add Arbor backend to GitHub Actions testing matrix
  .github/workflows/nestbuildmatrix.yml
  extras/ci_build.sh
  nestkernel/mpiutil.h
  nestkernel/mpiutil_impl.h
  nestkernel/recording_backend_arbor.cpp
  testsuite/pytests/arbor_backend_test_arbor_side.py
  testsuite/pytests/arbor_backend_test_nest_side.py
  testsuite/pytests/test_arbor_backend.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2142 Copy `syn_spec` to prevent it being modified
  pynest/nest/lib/hl_api_connection_helpers.py
  testsuite/pytests/test_regression_issue-2069.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2148 Detect pytest executable more robustly
  .github/workflows/nestbuildmatrix.yml
  extras/conda-nest-simulator-dev.yml
  testsuite/do_tests.sh
  testsuite/pytests/non_concurrent/arbor_backend_test_arbor_side.py
  testsuite/pytests/non_concurrent/arbor_backend_test_nest_side.py
  testsuite/pytests/non_concurrent/test_arbor_backend.py
Labels: T: Bug, S: High, I: No breaking change

#2158 Check that timeout package is installed before running pytests
  testsuite/do_tests.sh
Labels: T: Bug, S: High, I: No breaking change

#2160 Added pp_pop_psc_delta to deprecation list
  doc/userdoc/release_notes/v3.1/index.rst
Labels: S: High, T: Maintenance, I: No breaking change

#2155 Remove Arbor recording backend
  .github/workflows/nestbuildmatrix.yml
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  doc/userdoc/tutorials/music_tutorial/music_tutorial_1.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_2.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_3.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_4.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_parrot.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_setlatency.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_sli.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_tips.rst
  extras/check_copyright_headers.py
  extras/ci_build.sh
  libnestutil/config.h.in
  nestkernel/CMakeLists.txt
  nestkernel/io_manager.cpp
  nestkernel/mpiutil.h
  nestkernel/mpiutil_impl.h
  nestkernel/recording_backend_arbor.cpp
  nestkernel/recording_backend_arbor.h
  pynest/examples/arbor_cosim_example/README.md
  pynest/examples/arbor_cosim_example/arbor_proxy.py
  pynest/examples/arbor_cosim_example/nest_sender.py
  pynest/examples/music_cont_out_proxy_example/nest_script.py
  pynest/examples/music_cont_out_proxy_example/receiver_script.py
  sli/slistartup.cc
  sli/slistartup.h
  testsuite/do_tests.sh
  testsuite/pytests/non_concurrent/arbor_backend_test_arbor_side.py
  testsuite/pytests/non_concurrent/arbor_backend_test_nest_side.py
  testsuite/pytests/non_concurrent/test_arbor_backend.py
  testsuite/run_test.sh
Labels: S: High, T: Maintenance, I: No breaking change

#2156 Update Random123 library to v1.14.0
  thirdparty/Random123/README.md
  thirdparty/Random123/array.h
  thirdparty/Random123/conventional/Engine.hpp
  thirdparty/Random123/features/compilerfeatures.h
  thirdparty/Random123/features/gccfeatures.h
  thirdparty/Random123/features/msvcfeatures.h
  thirdparty/Random123/features/nvccfeatures.h
  thirdparty/Random123/features/pgccfeatures.h
  thirdparty/Random123/features/sse.h
  thirdparty/Random123/features/xlcfeatures.h
  thirdparty/Random123/tests/kat_cpp.cpp
  thirdparty/Random123/tests/kat_vectors
  thirdparty/Random123/tests/util.h
  thirdparty/Random123/threefry.h
  thirdparty/Random123/uniform.hpp
Labels: S: Normal, T: Maintenance, I: No breaking change

#2162 Fix access of first element of an empty vector in pynestkernel
  pynest/pynestkernel.pyx
  testsuite/do_tests.sh
Labels: T: Bug, S: High, I: Internal API

#2157 Fix import nest in NEST Server
  pynest/nest/__init__.py
  pynest/nest/server/hl_api_server.py
Labels: T: Bug, S: High

#2150 Link to zenodo citation page in docs
  README.md
  doc/userdoc/citing-nest.rst
  doc/userdoc/conf.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2164 Update security support for 3.1 release
  SECURITY.md
Labels: S: Normal, T: Maintenance, I: User Interface

#2169 Fix container access in corner cases and add _GLIBCXX_ASSERTIONS checks to all test configurations
  extras/ci_build.sh
  libnestutil/block_vector.h
  nestkernel/mpi_manager.cpp
  nestkernel/mpi_manager_impl.h
Labels: T: Bug, S: High, I: No breaking change

#2172 Remove erroneous check in stimulation device base class
  nestkernel/stimulation_device.cpp
Labels: T: Bug, S: Normal, I: External API
