Repository nest/nest-simulator, pull requests merged in 2021-11, with the labels that each got.

#2165 Implement Version Role for Sphinx
  doc/userdoc/_ext/VersionSyncRole.py
  doc/userdoc/_ext/versions.json
  doc/userdoc/conf.py
  doc/userdoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
Labels: T: Enhancement, S: Normal, I: No breaking change

#2109 Implement hover tooltips in documentation
  doc/userdoc/_ext/HoverXTooltip.py
  doc/userdoc/conf.py
  doc/userdoc/glossary.rst
  doc/userdoc/static/css/bootstrap.min.css
  doc/userdoc/static/css/hoverxtooltip.css
  doc/userdoc/static/js/bootstrap.min.js
  doc/userdoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
  doc/userdoc/tutorials/pynest_tutorial/part_3_connecting_networks_with_synapses.rst
Labels: T: Enhancement, S: Normal, I: No breaking change

#2201 Fix Clang warnings
  nestkernel/nest_datums.cpp
  nestkernel/parameter.cpp
  nestkernel/stimulation_backend_mpi.cpp
  sli/CMakeLists.txt
  sli/arraydatum.cc
  sli/dictdatum.cc
  sli/doubledatum.cc
  sli/doubledatum.h
  sli/integerdatum.cc
  sli/iostreamdatum.cc
  sli/iostreamdatum.h
  sli/lockptrdatum.h
  sli/lockptrdatum_impl.h
  sli/namedatum.cc
  sli/numericdatum.h
  sli/numericdatum_impl.h
  sli/sliregexp.cc
  sli/stringdatum.cc
  sli/symboldatum.cc
Labels: S: Normal, T: Maintenance, I: No breaking change

#2181 Distribute node positions over MPI processes
  lib/sli/nest-init.sli
  nestkernel/free_layer.h
  nestkernel/grid_layer.h
  nestkernel/layer.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nestmodule.cpp
  nestkernel/node_collection.cpp
  nestkernel/node_collection.h
  nestkernel/spatial.cpp
  nestkernel/spatial.h
  pynest/nest/lib/hl_api_spatial.py
  pynest/nest/lib/hl_api_types.py
  testsuite/mpitests/test_spatial_distributed_positions.sli
  testsuite/mpitests/test_spatial_pairwise_bernoulli_on_source_param.sli
  testsuite/pytests/mpi/2/test_spatial_positions.py
  testsuite/pytests/mpi/2/test_synapsecollection_mpi.py
  testsuite/pytests/mpi/4/test_spatial_positions.py
  testsuite/pytests/test_NodeCollection.py
  testsuite/pytests/test_spatial/test_connect_sliced.py
  testsuite/pytests/test_spatial_positions.py
  testsuite/unittests/test_node_collection.sli
Labels: T: Bug, S: Critical, I: No breaking change

#2206 Fix broken links on the download page
  doc/userdoc/download.rst
Labels: S: High, T: Maintenance, I: No breaking change

#2205 Update outdated code snippets in documentation
  doc/userdoc/guides/parallel_computing.rst
  doc/userdoc/guides/weight_normalization.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2186 Make volume transmitter inherit from Node instead of ArchivingNode
  models/volume_transmitter.cpp
  models/volume_transmitter.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2183 Tidy up SLI startup, especially opening of sli-init.sli.
  sli/slistartup.cc
  sli/slistartup.h
Labels: T: Bug, S: High, I: No breaking change

#2135 Concise and static Python imports
  doc/userdoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  extras/nest-server-mpi
  pynest/nest/__init__.py
  pynest/nest/hl_api.py
  pynest/nest/import_libs.py
  pynest/nest/lib/hl_api_connection_helpers.py
  pynest/nest/lib/hl_api_connections.py
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_info.py
  pynest/nest/lib/hl_api_models.py
  pynest/nest/lib/hl_api_nodes.py
  pynest/nest/lib/hl_api_parallel_computing.py
  pynest/nest/lib/hl_api_simulation.py
  pynest/nest/lib/hl_api_spatial.py
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/test_sp/test_sp_manager.py
  testsuite/pytests/test_sp/utils.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2195 Use `Development.Module` to be compatible with static Python interpreter
  cmake/ProcessOptions.cmake
Labels: S: High, T: Maintenance, I: No breaking change

#2210 Fall back to `Development` Python module in case of any errors
  cmake/ProcessOptions.cmake
Labels: T: Enhancement, S: High, I: No breaking change

#2166 Handle empty and non-absolute installation prefixes
  CMakeLists.txt
Labels: T: Enhancement, S: Normal, I: Internal API

#2218 Fix typo in hpc_benchmark
  pynest/examples/hpc_benchmark.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2222 Remove unused parameter from STDP unit test
  testsuite/pytests/test_stdp_synapse.py
Labels: T: Maintenance, I: No breaking change
