Repository nest/nest-simulator, pull requests merged in 2021-08, with the labels that each got.

#2055 Refactor the `Parameter` classes
  nestkernel/conn_builder.cpp
  nestkernel/conn_parameter.cpp
  nestkernel/nest.cpp
  nestkernel/nest.h
  nestkernel/nestmodule.cpp
  nestkernel/parameter.cpp
  nestkernel/parameter.h
  testsuite/cpptests/test_parameter.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2014 Set `have_connections_changed` correctly when we have fewer connections than MPI ranks
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/simulation_manager.cpp
  nestkernel/sp_manager.cpp
  nestkernel/sp_manager.h
  nestkernel/spatial.cpp
  pynest/examples/Potjans_2014/network.py
  sli/token.h
  sli/tokenarray.cc
  testsuite/mpitests/issue-1957.sli
Labels: T: Bug, S: High, I: No breaking change

#2086 Add standard and detailed timers for benchmarking purposes for NEST 2.20.2
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  doc/guides/HillTononiModels.ipynb
  doc/model_details/HillTononiModels.ipynb
  doc/tutorials/topology/hill_tononi_Vp.ipynb
  doc/tutorials/topology/hill_tononi_Vp.py
  doc/tutorials/topology/hill_tononi_Vp.rst
  examples/neuronview/neuronview.py
  libnestutil/config.h.in
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nestmodule.cpp
  nestkernel/node_manager.cpp
  nestkernel/node_manager.h
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
  pynest/examples/gif_pop_psc_exp.py
  pynest/examples/repeated_stimulation.py
  pynest/examples/sensitivity_to_perturbation.py
  pynest/nest/tests/test_quantal_stp_synapse.py
  pynest/nest/tests/test_regression_issue-1034.py
  testsuite/regressiontests/ticket-619.sli
  testsuite/regressiontests/ticket-80-175-179.sli
  topology/examples/hill_tononi_Vp.py
  topology/topologymodule.cpp
Labels: T: Enhancement, S: High, I: Internal API

#2010 Link PyNEST functions in documentaton
  doc/userdoc/getting_help.rst
  doc/userdoc/getting_started.rst
  doc/userdoc/guides/connection_management.rst
  doc/userdoc/guides/parallel_computing.rst
  doc/userdoc/guides/random_numbers.rst
  doc/userdoc/guides/record_from_simulations.rst
  doc/userdoc/guides/running_simulations.rst
  doc/userdoc/guides/simulations_with_gap_junctions.rst
  doc/userdoc/guides/spatially_structured_networks.rst
  doc/userdoc/guides/weight_normalization.rst
  doc/userdoc/release_notes/v3.0/features/handling_connections.rst
  doc/userdoc/release_notes/v3.0/features/node_handles.rst
  doc/userdoc/sli_docs/neural-simulations.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_2.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_3.rst
  doc/userdoc/tutorials/music_tutorial/music_tutorial_setlatency.rst
  doc/userdoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  doc/userdoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
  doc/userdoc/tutorials/pynest_tutorial/part_3_connecting_networks_with_synapses.rst
  doc/userdoc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
Labels: T: Enhancement, S: Normal, I: No breaking change

#2118 Fix mismatched parenthesis in setup.py.in
  pynest/setup.py.in
Labels: T: Bug, S: Normal, I: No breaking change

#2122 Remove outdated comment on Python dynamic library flags
  pynest/nest/ll_api.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2133 Fix examples to make them run
  examples/nest/brunel-2000_newconnect_dc.sli
  pynest/examples/brunel_exp_multisynapse_nest.py
  pynest/examples/synapsecollection.py
Labels: T: Bug, S: High, I: Internal API
