Repository nest/nest-simulator, pull requests merged in 2021-07, with the labels that each got.

#2088 Remove undocumented weighted_spikes_{ex,in} from iaf_psc_{alpha,exp} recordables
  doc/userdoc/guides/nest2_to_nest3/nest3_features/nest3_node_handles.rst
  models/iaf_psc_alpha.cpp
  models/iaf_psc_alpha.h
  models/iaf_psc_exp.cpp
  models/iaf_psc_exp.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  testsuite/unittests/test_multiple_multimeter.sli
Labels: I: Behavior changes, S: Normal, T: Maintenance

#2089 Check validity of parameters given to SetKernelStatus
  pynest/nest/lib/hl_api_simulation.py
  pynest/nest/tests/test_status.py
Labels: I: No breaking change, S: Normal, T: Enhancement

#2095 Implement time limit for duration of update cycles.
  libnestutil/stopwatch.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
  pynest/nest/lib/hl_api_simulation.py
Labels: I: No breaking change, S: Normal, T: Enhancement

#2024 Automatic conversion of integers to doubles when setting parameters
  nestkernel/nestmodule.cpp
  pynest/nest/tests/test_create.py
  sli/sliarray.cc
  sli/token.cc
  sli/tokenarray.cc
  sli/tokenutils.cc
  sli/tokenutils.h
  testsuite/regressiontests/issue-545.sli
Labels: I: No breaking change, S: Normal, T: Enhancement

#2093 Fix figure in spatially structured networks tutorial
  doc/userdoc/static/img/free.png
  doc/userdoc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#2099 Turn docstring with math into raw string.
  pynest/nest/lib/hl_api_simulation.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#2090 aligned pkg_resources query with setup.py name
  pynest/CMakeLists.txt
Labels: I: No breaking change, S: Normal, T: Bug

#2103 Extend data combination routine for NEST Server
  pynest/nest/server/hl_api_server.py
Labels: I: External API, S: Normal, T: Enhancement

#2085 add intersphinx to NEST documentation with links to related projects
  doc/userdoc/conf.py
  doc/userdoc/index.rst
  doc/userdoc/related_projects.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#2105 Replace PEP8 by pycodestyle
  .github/workflows/nestbuildmatrix.yml
  doc/userdoc/contribute/ci.rst
  doc/userdoc/contribute/templates/pynest_api_template.py
  doc/userdoc/contribute/templates/pynest_example_template.py
  examples/nest/Potjans_2014/spike_analysis.py
  extras/ConnPlotter/ConnPlotter.py
  extras/check_code_style.sh
  extras/check_copyright_headers.py
  extras/check_unused_names.py
  extras/ci_build.sh
  extras/conda-nest-simulator-dev.yml
  extras/find_imports.py
  extras/help_generator/generate_help.py
  extras/help_generator/helpers.py
  extras/help_generator/writers.py
  extras/include_checker.py
  extras/parse_build_log.py
  extras/static_code_analysis.sh
  pynest/examples/Potjans_2014/helpers.py
Labels: I: No breaking change, S: High, T: Maintenance

#2107 Declared security support for new 3.0 release
  SECURITY.md
Labels: S: High, T: Enhancement

#2074 Remove machine-specifc code for K computer
  sli/allocator.cpp
  sli/allocator.h
  sli/slistartup.cc
Labels: I: No breaking change, S: Normal, T: Maintenance

#2111 Clean up NEST Server and fix deadlock
  doc/userdoc/conf.py
  extras/nest-server-mpi
  pynest/nest/server/hl_api_server.py
Labels: I: Internal API, S: High, T: Maintenance

#2082 Modify and improve colors in style sheet for ReadtheDocs
  doc/userdoc/conf.py
  doc/userdoc/static/css/custom.css
Labels: I: No breaking change, S: Normal, T: Enhancement

#2106 Add default values to SetKernelStatus parameters
  pynest/nest/lib/hl_api_info.py
  pynest/nest/lib/hl_api_simulation.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#2063 Add timers for NEST 2.14.1
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  libnestutil/config.h.in
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nestmodule.cpp
  nestkernel/node_manager.cpp
  nestkernel/node_manager.h
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
  topology/topologymodule.cpp
Labels: I: User Interface, S: Normal, T: Enhancement

#2112 Undo Markdown-to-reStructuredText conversion in doxygen comment
  sli/token.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#2087 Minor improvement to microcircuit example
  examples/nest/Potjans_2014/README.txt
  examples/nest/Potjans_2014/run_microcircuit.sh
  pynest/examples/Potjans_2014/helpers.py
  pynest/examples/Potjans_2014/network.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#2091 Add license to jupyter notebooks
  doc/userdoc/model_details/HillTononiModels.ipynb
  doc/userdoc/model_details/IAF_neurons_singularity.ipynb
  doc/userdoc/model_details/aeif_models_implementation.ipynb
  doc/userdoc/model_details/noise_generator.ipynb
  doc/userdoc/model_details/siegert_neuron_integration.ipynb
  doc/userdoc/model_details/test_post_trace.ipynb
Labels: I: No breaking change, S: Normal, T: Maintenance

#2115 Pave the way for per-version transition guides
  doc/userdoc/contents.rst
  doc/userdoc/download.rst
  doc/userdoc/features.rst
  doc/userdoc/guides/index.rst
  doc/userdoc/guides/nest2_to_nest3/index.rst
  doc/userdoc/guides/nest2_to_nest3/whats_removed.rst
  doc/userdoc/guides/random_numbers.rst
  doc/userdoc/guides/spatial/index.rst
  doc/userdoc/guides/spatial/overview_spatial.rst
  doc/userdoc/guides/spatial/pynest.rst
  doc/userdoc/guides/spatially_structured_networks.rst
  doc/userdoc/guides/spatially_structured_networks/figures/conn1.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn2.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn2_a.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn2_b.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn2_c.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn3.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn4.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn5.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn6.png
  doc/userdoc/guides/spatially_structured_networks/figures/conn_3d.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer1.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer2.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer3.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer3a.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer4.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer4_3d.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer4_3d_b.png
  doc/userdoc/guides/spatially_structured_networks/figures/layer4b.png
  doc/userdoc/guides/spatially_structured_networks/figures/player.png
  doc/userdoc/guides/spatially_structured_networks/figures/vislayer.png
  doc/userdoc/guides/spatially_structured_networks/scripts/connections.py
  doc/userdoc/guides/spatially_structured_networks/scripts/layers.py
  doc/userdoc/index.rst
  doc/userdoc/release_notes/index.rst
  doc/userdoc/release_notes/v3.0/features/handling_connections.rst
  doc/userdoc/release_notes/v3.0/features/index.rst
  doc/userdoc/release_notes/v3.0/features/node_handles.rst
  doc/userdoc/release_notes/v3.0/features/parametrization.rst
  doc/userdoc/release_notes/v3.0/features/random_number_generators.rst
  doc/userdoc/release_notes/v3.0/features/recording_simulations.rst
  doc/userdoc/release_notes/v3.0/features/stimulation_backends.rst
  doc/userdoc/release_notes/v3.0/index.rst
  doc/userdoc/release_notes/v3.0/refguide_nest2_nest3.rst
  doc/userdoc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
Labels: I: No breaking change, S: Normal, T: Maintenance
