Repository nest/nest-simulator, pull requests merged in 2021-12, with the labels that each got.

#2223 Fix pycodestyle
  testsuite/pytests/test_sp/test_sp_manager.py
Labels: S: Normal, T: Maintenance, I: Internal API

#2226 Remove some mergeconflict artifacts
  .gitignore
  libnestutil/CMakeLists.txt.orig
  nestkernel/mpi_manager.cpp.orig
  nestkernel/mpi_manager.h.orig
Labels: S: Normal, T: Maintenance, I: No breaking change

#2213 Fix missing functions in hl_api
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_info.py
Labels: T: Bug, S: High, I: Internal API

#2216 Add additional reference to Izhikevich model documentation
  models/izhikevich.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2220 Attribute assignment safeguards for `NestModule` and `SynapseCollection`
  pynest/nest/__init__.py
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/test_get_set.py
Labels: T: Bug, S: High, I: User Interface

#2231 Fix compiler warning issued by newest Clang
  .github/workflows/nestbuildmatrix.yml
  nestkernel/connection_creator_impl.h
Labels: T: Bug, S: Critical, I: No breaking change

#2233 Fix failing Read the docs build
  doc/userdoc/conf.py
Labels: S: High, T: Maintenance, I: No breaking change

#2228 Bump sphinx version to >=4.0.2 to remove jinja<3 requirement
  doc/requirements.txt
  environment.yml
Labels: S: Normal, T: Maintenance, I: No breaking change

#2244 Fix quirks with import machinery in Python 3.8
  pynest/nest/__init__.py
Labels: T: Bug, S: Critical, I: Internal API

#2232 Format error messages in `jonke_synapse` and `stdp_dopamine_synapse`
  models/jonke_synapse.h
  models/stdp_dopamine_synapse.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2147 Remove Connplotter from the NEST code base
  doc/userdoc/related_projects.rst
  doc/userdoc/release_notes/v3.2/index.rst
  examples/CMakeLists.txt
  examples/ConnPlotter/CMakeLists.txt
  examples/ConnPlotter/ConnPlotter.py
  examples/ConnPlotter/MANIFEST
  examples/ConnPlotter/__init__.py
  examples/ConnPlotter/colormaps.py
  examples/ConnPlotter/doc/connplotter_tutorial.pdf
  examples/ConnPlotter/examples/__init__.py
  examples/ConnPlotter/examples/complex.py
  examples/ConnPlotter/examples/connplotter_tutorial.py
  examples/ConnPlotter/examples/non_dale.py
  examples/ConnPlotter/examples/simple.py
  examples/ConnPlotter/setup.py
  examples/ConnPlotter/tcd_nest.py
Labels: S: Normal, T: Maintenance, I: Internal API

#2247 Add connectivity diagram to `hpc_benchmark` documentation
  doc/userdoc/conf.py
  pynest/examples/hpc_benchmark.py
  pynest/examples/hpc_benchmark_connectivity.svg
Labels: T: Enhancement, S: Normal

#2248 Fix path to connection diagram for HPC benchmark example
  pynest/examples/hpc_benchmark.py
Labels: S: Normal, T: Maintenance, I: No breaking change
