Repository nest/nest-simulator, pull requests merged in 2021-03, with the labels that each got.

#1951 Remove unnecessary and properly order remaining includes in gif_cond models
  models/gif_cond_exp.cpp
  models/gif_cond_exp_multisynapse.cpp
Labels: I: No breaking change, S: Normal, T: Maintenance

#1937 Hike Boost minimum version to 1.69
  cmake/ProcessOptions.cmake
Labels: I: No breaking change, S: Normal, T: Maintenance

#1918 Revised Mac installation instructions
  INSTALL
  README.md
  doc/userdoc/contribute/development_workflow.rst
  doc/userdoc/installation/cmake_options.rst
  doc/userdoc/installation/conda_tips.rst
  doc/userdoc/installation/hpc_install.rst
  doc/userdoc/installation/index.rst
  doc/userdoc/installation/linux_install.rst
  doc/userdoc/installation/mac_install.rst
  doc/userdoc/troubleshooting.rst
  extras/conda-env-nest-simulator.yml
Labels: I: No breaking change, S: High, T: Maintenance

#1936 Remove SLI examples in model documentation
  models/music_rate_out_proxy.h
  models/spike_generator.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1956 Reduce amount of data exchanged in test to ensure stable operation.
  testsuite/mpitests/test_multiple_synapses.sli
  testsuite/mpitests/test_multiple_synapses_spatial_networks.sli
Labels: I: No breaking change, S: High, T: Bug

#1949 Provide links to model_details in relevant model documentation
  models/aeif_cond_alpha.h
  models/aeif_cond_alpha_multisynapse.h
  models/aeif_cond_beta_multisynapse.h
  models/aeif_cond_exp.h
  models/aeif_psc_alpha.h
  models/aeif_psc_delta.h
  models/aeif_psc_delta_clopath.h
  models/aeif_psc_exp.h
  models/gif_psc_exp.h
  models/gif_psc_exp_multisynapse.h
  models/glif_psc.h
  models/ht_connection.h
  models/ht_neuron.h
  models/iaf_psc_alpha.h
  models/iaf_psc_alpha_canon.h
  models/iaf_psc_alpha_multisynapse.h
  models/iaf_psc_alpha_ps.h
  models/iaf_psc_exp.h
  models/iaf_psc_exp_htum.h
  models/iaf_psc_exp_multisynapse.h
  models/iaf_psc_exp_ps.h
  models/iaf_psc_exp_ps_lossless.h
  models/noise_generator.h
  models/siegert_neuron.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1942 fix setting synapse parameters when running connect_arrays multithreaded
  nestkernel/nest.cpp
  pynest/nest/tests/test_connect_arrays.py
Labels: I: No breaking change, S: Critical, T: Bug

#1958 Add Visual Studio Code settings directory to .gitignore
  .gitignore
Labels: I: No breaking change, S: Normal, T: Maintenance

#1935 Activation term exponent for I_NaP and I_T configurable in ht_neuron
  doc/model_details/HillTononiModels.ipynb
  models/ht_neuron.cpp
  models/ht_neuron.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
Labels: I: No breaking change, S: Normal, T: Enhancement, good first issue

#1963 Extended gitignore with specific excludes for various IDE config files, macOS-specific files and _build.
  .gitignore
Labels: I: No breaking change, S: Normal, T: Maintenance

#1908 Add PyNEST function to obtain local VPs
  extras/check_code_style.sh
  pynest/nest/hl_api.py
  pynest/nest/lib/hl_api_parallel_computing.py
  pynest/nest/lib/hl_api_simulation.py
  pynest/nest/tests/mpitest_get_local_vps.py
  pynest/nest/tests/test_all.py
  pynest/nest/tests/test_mpitests.py
  pynest/nest/tests/test_sp/mpitest_issue_578_sp.py
  pynest/nest/tests/test_sp/test_all.py
Labels: I: No breaking change, S: High, T: Enhancement

#1941 Add instructions for how to work with Eclipse when developing NEST
  doc/userdoc/contribute/index.rst
  doc/userdoc/contribute/nest_with_ides.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#1969 Clean up t_ref parameter in aeif models
  models/aeif_cond_alpha.h
  models/aeif_cond_exp.cpp
  models/aeif_cond_exp.h
  models/aeif_psc_alpha.h
  models/aeif_psc_delta.cpp
  models/aeif_psc_delta.h
  models/aeif_psc_delta_clopath.cpp
  models/aeif_psc_delta_clopath.h
  models/aeif_psc_exp.cpp
  models/aeif_psc_exp.h
Labels: I: No breaking change, S: Critical, T: Bug, good first issue

#1920 Remove broken link in poisson generator documentation
  models/poisson_generator.h
Labels: I: No breaking change, S: Normal, T: Maintenance, good first issue

#1950 Add link to set_verbosity documentation
  doc/userdoc/getting_started.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#1911 Remove "Edit on GitHub" button on Read the Docs
  doc/userdoc/static/css/custom.css
Labels: I: No breaking change, S: Normal, T: Maintenance

#1921 Clarify the post-pre convention used in plot-weight-matrices example documentation
  pynest/examples/plot_weight_matrices.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1979 Fix broken images in documentation
  doc/userdoc/documentation_workflow/user_documentation_workflow.rst
  doc/userdoc/getting_started.rst
  doc/userdoc/guides/connection_management.rst
  doc/userdoc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
  doc/userdoc/guides/parallel_computing.rst
  doc/userdoc/guides/running_simulations.rst
  doc/userdoc/guides/simulations_with_precise_spike_times.rst
  doc/userdoc/index.rst
  doc/userdoc/installation/index.rst
  doc/userdoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  doc/userdoc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1926 Fix PyNest help and helpdesk commands
  doc/CMakeLists.txt
  doc/userdoc/documentation_workflow/user_documentation_workflow.rst
  doc/userdoc/getting_help.rst
  doc/userdoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  pynest/nest/__init__.py
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_info.py
Labels: I: Behavior changes, S: High, T: Maintenance

#1985 Minor update parallel computing guide
  doc/userdoc/guides/parallel_computing.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1981 Remove hill_tononi_Vp example
  doc/CMakeLists.txt
  doc/userdoc/conf.py
  doc/userdoc/examples/index.rst
  doc/userdoc/model_details/HillTononiModels.ipynb
  doc/userdoc/model_details/IAF_neurons_singularity.ipynb
  doc/userdoc/model_details/aeif_models_implementation.ipynb
  doc/userdoc/model_details/noise_generator.ipynb
  doc/userdoc/model_details/siegert_neuron_integration.ipynb
  doc/userdoc/model_details/test_post_trace.ipynb
  libnestutil/propagator_stability.h
  models/ht_neuron.h
  pynest/examples/spatial/hill_tononi_Vp.py
  pynest/nest/tests/test_aeif_data_lsodar.dat
  pynest/nest/tests/test_aeif_lsodar.py
  pynest/nest/tests/test_regression_issue-1034.py
  pynest/nest/tests/test_siegert_neuron.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#1966 Fixed a number of missing initialisations detected by Eclipse.
  extras/parse_travis_log.py
  libnestutil/block_vector.h
  models/aeif_psc_delta.cpp
  models/aeif_psc_delta.h
  models/noise_generator.cpp
  models/volume_transmitter.cpp
  nestkernel/connection_id.cpp
  nestkernel/connection_id.h
  nestkernel/mpi_manager.cpp
  nestkernel/simulation_manager.cpp
  nestkernel/sparse_node_array.h
  sli/scanner.cc
Labels: I: No breaking change, S: Normal, T: Maintenance

#1741 Shrink MPI buffers for spike communication
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/mpi_manager.cpp
  nestkernel/mpi_manager.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1940 Include ACKNOWLEDGMENTS.md directly into main page of ReadtheDocs
  ACKNOWLEDGMENTS.md
  doc/userdoc/conf.py
  doc/userdoc/index.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1980 Adapt warning parser to output format on GitHub Actions
  extras/parse_travis_log.py
Labels: I: No breaking change, S: High, T: Maintenance

#1991 Fix wrong code in the getting started documentation
  doc/userdoc/getting_started.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#1965 Replaces conda environment files with one file covering all needs.
  .readthedocs.yml
  doc/environment.yml
  doc/userdoc/documentation_workflow/user_documentation_workflow.rst
  doc/userdoc/installation/conda_tips.rst
  doc/userdoc/installation/mac_install.rst
  extras/conda-env-nest-simulator.yml
  extras/conda-nest-simulator-dev.yml
  extras/nest-simulator-doc-requirements.txt
Labels: I: No breaking change, S: High, T: Enhancement

#1993 Fix for failing Read the Docs build
  .readthedocs.yml
Labels: S: Critical

#1778 Timers for Benchmarking (related to issue #1471 "Basic Instrumentation")
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  libnestutil/config.h.in
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/nest.cpp
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nestmodule.cpp
  nestkernel/node_manager.cpp
  nestkernel/node_manager.h
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
  pynest/nest/tests/test_quantal_stp_synapse.py
  pynest/nest/tests/test_regression_issue-1034.py
  testsuite/regressiontests/ticket-619.sli
  testsuite/regressiontests/ticket-80-175-179.sli
Labels: I: No breaking change, S: Normal, T: Enhancement
