Repository nest/nest-simulator, pull requests merged in 2021-04, with the labels that each got.

#1954 Hike and enforce Python version requirement to 3.8
  cmake/ConfigureSummary.cmake
  cmake/FindCython.cmake
  cmake/FindPythonModule.cmake
  cmake/ProcessOptions.cmake
  cmake/UseCython.cmake
  doc/CMakeLists.txt
  doc/userdoc/installation/linux_install.rst
  doc/userdoc/troubleshooting.rst
  extras/nest-config.in
  nest/CMakeLists.txt
  pynest/CMakeLists.txt
  testsuite/do_tests.sh
Labels: I: No breaking change, S: High, T: Maintenance

#1994 Correctly draw rectangular masks with azimuth_angle != 0
  pynest/nest/lib/hl_api_spatial.py
Labels: I: No breaking change, S: Normal, T: Bug

#1999 Add missing include file to CMakeLists
  libnestutil/CMakeLists.txt
Labels: I: No breaking change, S: Normal, T: Bug

#1988 Update user-level documentation workflow
  doc/userdoc/documentation_workflow/user_documentation_workflow.rst
  doc/userdoc/installation/linux_install.rst
Labels: I: No breaking change, S: Normal, T: Maintenance

#2012 Parse build output of GitHub Actions
  .github/workflows/nestbuildmatrix.yml
  .travis.yml
  doc/userdoc/contribute/ci.rst
  extras/check_code_style.sh
  extras/gha_build.sh
  extras/parse_build_log.py
  extras/static_code_analysis.sh
  extras/travis_build.sh
Labels: I: No breaking change, S: High, T: Bug

#2008 Remove unused function communicate_Allreduce_max_in_place()
  nestkernel/mpi_manager.cpp
  nestkernel/mpi_manager.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1984 Add instructions for how to work with VS Code when developing NEST
  doc/userdoc/contribute/nest_with_ides.rst
Labels: I: No breaking change, S: Normal, T: Enhancement

#2001 Propagate the `cython --version` error
  cmake/FindCython.cmake
Labels: I: No breaking change, S: Normal, T: Bug

#2018 Remove unused event_prototypes_ member
  nestkernel/model_manager.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#1995 Move developer space content into docs on master branch
  CONTRIBUTING.md
  README.md
  doc/slidoc/index.html
  doc/userdoc/contents.rst
  doc/userdoc/contribute/code_review_guidelines.rst
  doc/userdoc/contribute/index.rst
  doc/userdoc/contribute/naming_conventions.rst
  doc/userdoc/contribute/nest_with_ides.rst
  doc/userdoc/documentation_workflow/user_documentation_workflow.rst
  doc/userdoc/index.rst
  doc/userdoc/installation/index.rst
  extras/check_code_style.sh
  extras/help_generator/templates/overview-sample-header.tmpl
  extras/help_generator/templates/sample-header.tmpl
  sli/token.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#2016 Move connect_arrays() from nest.cpp to connection_manager
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/nest.cpp
Labels: I: No breaking change, S: Normal, T: Maintenance
