Repository nest/nest-simulator, pull requests merged in 2021-05, with the labels that each got.

#1338 Communication via compressed spikes
  nestkernel/archiving_node.cpp
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/event_delivery_manager.cpp
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/simulation_manager.cpp
  nestkernel/source_table.cpp
  nestkernel/source_table.h
  pynest/nest/lib/hl_api_simulation.py
  pynest/nest/tests/test_spatial/test_basics.py
  testsuite/unittests/test_connect_after_simulate.sli
  testsuite/unittests/test_free_mask_circ_anchor_00.sli
  testsuite/unittests/test_free_mask_circ_anchor_01.sli
  testsuite/unittests/test_free_mask_circ_anchor_10.sli
  testsuite/unittests/test_free_mask_circ_anchor_11.sli
  testsuite/unittests/test_free_mask_donut_anchor_00.sli
  testsuite/unittests/test_free_mask_donut_anchor_01.sli
  testsuite/unittests/test_free_mask_donut_anchor_10.sli
  testsuite/unittests/test_free_mask_donut_anchor_11.sli
  testsuite/unittests/test_free_mask_rect_00.sli
  testsuite/unittests/test_free_mask_rect_01.sli
  testsuite/unittests/test_free_mask_rect_11.sli
  testsuite/unittests/test_free_mask_rect_13.sli
  testsuite/unittests/test_reg_mask_circ_anchor_00.sli
  testsuite/unittests/test_reg_mask_circ_anchor_01.sli
  testsuite/unittests/test_reg_mask_circ_anchor_10.sli
  testsuite/unittests/test_reg_mask_circ_anchor_11.sli
  testsuite/unittests/test_reg_mask_donut_anchor_00.sli
  testsuite/unittests/test_reg_mask_donut_anchor_01.sli
  testsuite/unittests/test_reg_mask_donut_anchor_10.sli
  testsuite/unittests/test_reg_mask_donut_anchor_11.sli
  testsuite/unittests/test_reg_mask_grid_anchor_00.sli
  testsuite/unittests/test_reg_mask_grid_anchor_01.sli
  testsuite/unittests/test_reg_mask_grid_anchor_02.sli
  testsuite/unittests/test_reg_mask_grid_anchor_03.sli
  testsuite/unittests/test_reg_mask_grid_anchor_04.sli
  testsuite/unittests/test_reg_mask_grid_anchor_05.sli
  testsuite/unittests/test_reg_mask_grid_anchor_06.sli
  testsuite/unittests/test_reg_mask_grid_anchor_10.sli
  testsuite/unittests/test_reg_mask_grid_anchor_11.sli
  testsuite/unittests/test_reg_mask_grid_anchor_13.sli
  testsuite/unittests/test_reg_mask_grid_anchor_15.sli
  testsuite/unittests/test_reg_mask_rect_00.sli
  testsuite/unittests/test_reg_mask_rect_01.sli
  testsuite/unittests/test_reg_mask_rect_02.sli
  testsuite/unittests/test_reg_mask_rect_10.sli
  testsuite/unittests/test_reg_mask_rect_11.sli
  testsuite/unittests/test_weight_delay.sli
  testsuite/unittests/test_weight_delay_free.sli
Labels: I: No breaking change, S: Normal, T: Enhancement

#2011 Add documentation on multicompartment models
  doc/userdoc/examples/index.rst
  doc/userdoc/guides/index.rst
  doc/userdoc/static/img/multicompartment.png
  models/iaf_cond_alpha_mc.h
  models/pp_cond_exp_mc_urbanczik.h
  models/urbanczik_synapse.h
Labels: I: No breaking change, S: Normal, T: Maintenance

#2026 Revised Quantal STP Example
  pynest/examples/evaluate_quantal_stp_synapse.py
Labels: I: No breaking change, S: High, T: Enhancement, good first issue

#2022 Add MPI-enabled version of NEST Server and NEST Server documentation
  ACKNOWLEDGMENTS.md
  doc/userdoc/contents.rst
  doc/userdoc/index.rst
  doc/userdoc/installation/index.rst
  doc/userdoc/nest_server.rst
  doc/userdoc/static/img/nest_server.png
  extras/CMakeLists.txt
  extras/nest-server
  extras/nest-server-mpi
  pynest/nest/server/hl_api_server.py
Labels: I: Internal API, S: High, T: Enhancement

#2039 Fix issue with building Sphinx documentation with recent Jinja version
  extras/conda-nest-simulator-dev.yml
  extras/nest-simulator-doc-requirements.txt
Labels: I: No breaking change, S: Critical, T: Bug

#2036 Remove brackets around NodeCollections in tests
  testsuite/regressiontests/issue-1242.sli
  testsuite/regressiontests/issue-735.sli
  testsuite/regressiontests/issue-737-threads.sli
  testsuite/regressiontests/issue-737.sli
  testsuite/regressiontests/ticket-451.sli
  testsuite/regressiontests/ticket-681.sli
  testsuite/unittests/test_bernoulli_synapse.sli
  testsuite/unittests/test_gap_junction.sli
Labels: I: No breaking change, S: Critical, T: Bug

#2045 Fix missing state variable initialisation in iaf_chxk_2008
  models/iaf_chxk_2008.cpp
Labels: T: Bug

#2047 fix python MPI tests
  pynest/nest/tests/test_mpitests.py
Labels: I: No breaking change, S: High, T: Bug

#2043 Make quantal_stp_synapse support setting `n` and `a` when connecting
  models/quantal_stp_synapse.h
  models/quantal_stp_synapse_impl.h
  pynest/nest/tests/test_connect_parameters.py
  pynest/nest/tests/test_quantal_stp_synapse.py
  testsuite/regressiontests/issue-737.sli
Labels: I: No breaking change, S: High, T: Maintenance

#1919 Add example for how to store and restore a network.
  pynest/examples/store_restore_network.py
Labels: I: No breaking change, S: Normal, T: Enhancement

#1982 Improve documentation of Run() and RunManager()
  pynest/nest/lib/hl_api_simulation.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#2048 C++ implementations of spatial distribution functions
  nestkernel/nestmodule.cpp
  nestkernel/parameter.cpp
  nestkernel/parameter.h
  pynest/nest/spatial_distributions/hl_api_spatial_distributions.py
  pynest/nest/tests/test_spatial/test_spatial_distributions.py
Labels: I: No breaking change, S: Normal, T: Maintenance

#2054 Fix failing build on ReadtheDocs due to key error
  doc/userdoc/conf.py
Labels: S: High, T: Bug

#1929 Restructure NEST 3.0 guides
  doc/userdoc/contents.rst
  doc/userdoc/examples/index.rst
  doc/userdoc/guides/index.rst
  doc/userdoc/guides/nest2_to_nest3/index.rst
  doc/userdoc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
  doc/userdoc/guides/nest2_to_nest3/nest3_features/index.rst
  doc/userdoc/guides/nest2_to_nest3/nest3_features/nest3_handling_connections.rst
  doc/userdoc/guides/nest2_to_nest3/nest3_features/nest3_node_handles.rst
  doc/userdoc/guides/nest2_to_nest3/nest3_features/parametrization.rst
  doc/userdoc/guides/nest2_to_nest3/nest3_features/random_number_generators.rst
  doc/userdoc/guides/nest2_to_nest3/nest3_features/recording_simulations.rst
  doc/userdoc/guides/nest2_to_nest3/refguide_nest2_nest3.rst
  doc/userdoc/guides/nest2_to_nest3/whats_removed.rst
  doc/userdoc/guides/random_numbers.rst
  doc/userdoc/guides/running_simulations.rst
  doc/userdoc/guides/spatial/index.rst
  doc/userdoc/guides/spatial/overview_spatial.rst
  doc/userdoc/index.rst
  doc/userdoc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
Labels: I: No breaking change, S: Normal, T: Enhancement
