Repository nest/nest-simulator, pull requests merged in 2022-10, with the labels that each got.

#2379 Ensure correct model id and model name when models are copied
  nestkernel/io_manager.cpp
  nestkernel/model_manager.cpp
  testsuite/pytests/test_copy_model.py
  testsuite/pytests/test_create.py
Labels: T: Bug, S: High, I: No breaking change

#2377 Prohibit multimeter-recording from noise_generator in multithreaded mode
  doc/htmldoc/neurons/model_details/noise_generator.ipynb
  models/noise_generator.h
  pynest/examples/spatial/conncon_sources.py
  testsuite/pytests/test_spatial_positions.py
  testsuite/regressiontests/issue-2282.sli
Labels: T: Bug, S: High, I: No breaking change

#2491 Ensure do_tests.sh completes even when tests fail
  testsuite/do_tests.sh
Labels: S: Normal, T: Maintenance, I: No breaking change

#2455 Install assimulo from conda-forge
  doc/htmldoc/neurons/model_details/aeif_models_implementation.ipynb
  environment.yml
Labels: S: Normal, T: Maintenance, I: No breaking change

#2417 Add note about PYNEST_QUIET in docstring
  pynest/nest/lib/hl_api_info.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2505 Change NEST Server default port to 52425
  bin/nest-server
  doc/htmldoc/connect_nest/nest_server.rst
  doc/htmldoc/installation/docker.rst
  pynest/nest/server/hl_api_server.py
Labels: S: Normal, T: Maintenance, I: External API

#2475 Update documentation for `CreateParameter`
  pynest/nest/lib/hl_api_types.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2502 Remove superfluous data structure for secondary events
  models/modelsmodule.cpp
  nestkernel/CMakeLists.txt
  nestkernel/connection.h
  nestkernel/connection_manager.cpp
  nestkernel/connector_model.h
  nestkernel/connector_model_impl.h
  nestkernel/dynamicloader.cpp
  nestkernel/dynamicloader.h
  nestkernel/event.h
  nestkernel/event_delivery_manager.h
  nestkernel/event_delivery_manager_impl.h
  nestkernel/kernel_manager.h
  nestkernel/model_manager.cpp
  nestkernel/model_manager.h
  nestkernel/model_manager_impl.h
  nestkernel/node.h
  nestkernel/secondary_event.h
  nestkernel/simulation_manager.cpp
  nestkernel/sp_manager.cpp
  pynest/nest/__init__.py
  testsuite/pytests/test_copy_model.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2403 Add conversion from `IntegerDatum` to `ConstantParameter` in `create_parameter()`
  nestkernel/nestmodule.cpp
  nestkernel/parameter.h
  testsuite/pytests/test_spatial/test_connect_layers.py
Labels: T: Bug, S: High, I: No breaking change, stale, need reviewer

#2474 Refactor functions to use `MPI_Allreduce`
  nestkernel/mpi_manager.cpp
  nestkernel/mpi_manager.h
  nestkernel/random_manager.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change

#2510 Update port in NESTServerClient
  examples/NESTServerClient/NESTServerClient.py
Labels: S: High, T: Maintenance, I: No breaking change

#2485 Improved clarity of `Dwith-python` error
  cmake/ProcessOptions.cmake
Labels: S: Normal, T: Maintenance, I: No breaking change

#2514 Add missing tests of MUSIC models
  testsuite/do_tests.sh
  testsuite/musictests/test_message.music
  testsuite/musictests/test_message0.dat
  testsuite/musictests/test_message_receiver.sli
  testsuite/musictests/test_rate_proxy.music
  testsuite/musictests/test_rate_proxy_receiver.sli
  testsuite/musictests/test_rate_proxy_sender.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2501 Add support for `Parameter` objects for `indegree` and `outdegree` in `syn_spec`s
  build_support/static_code_analysis.sh
  doc/htmldoc/networks/scripts/connections.py
  doc/htmldoc/networks/spatially_structured_networks.rst
  nestkernel/connection_creator.cpp
  nestkernel/connection_creator.h
  nestkernel/connection_creator_impl.h
  testsuite/pytests/test_spatial/test_connect_layers.py
Labels: T: Enhancement, S: Normal, I: No breaking change
