Repository nest/nest-simulator, pull requests merged in 2022-08, with the labels that each got.

#2380 Remove remaining uses of `float` datatype from C++ code.
  libnestutil/block_vector.h
  nestkernel/recording_backend_ascii.cpp
  nestkernel/simulation_manager.cpp
  nestkernel/vp_manager_impl.h
  sli/token.h
  sli/tokenarray.cc
  sli/tokenarray.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2412 Remove the SLI-based NEST configuration file
  build_support/check_copyright_headers.py
  build_support/ci_build.sh
  cmake/ConfigureSummary.cmake
  doc/htmldoc/hpc/parallel_computing.rst
  doc/htmldoc/installation/cmake_options.rst
  doc/htmldoc/installation/configuration.rst
  examples/CMakeLists.txt
  examples/sli/nestrc.sli
  lib/sli/helpinit.sli
  lib/sli/processes.sli
  lib/sli/sli-init.sli
  libnestutil/config.h.in
  sli/slistartup.cc
  sli/slistartup.h
  testsuite/do_tests.sh
  testsuite/musictests/README.md
  testsuite/selftests/test_crash_or_die.sli
  testsuite/selftests/test_failbutnocrash_or_die_crash.sli
  testsuite/selftests/test_failbutnocrash_or_die_pass.sli
  testsuite/selftests/test_passorfailbutnocrash_or_die.sli
Labels: S: Normal, T: Maintenance, I: Behavior changes

#2375 Deprecate `spike_dilutor` and prohibit its use with multiple threads
  doc/htmldoc/release_notes/v3.4/index.rst
  doc/htmldoc/whats_new/index.rst
  models/bernoulli_synapse.h
  models/gif_pop_psc_exp.h
  models/modelsmodule.cpp
  models/spike_dilutor.cpp
  models/spike_dilutor.h
  nestkernel/exceptions.h
  testsuite/regressiontests/issue-2052.sli
  testsuite/unittests/test_spike_dilutor.sli
Labels: T: Bug, S: High, I: Behavior changes

#2445 Fix Sudoku link in examples
  doc/htmldoc/examples/index.rst
  doc/htmldoc/static/img/sudoku_solution.gif
  doc/htmldoc/static/img/sudoku_solution.png
Labels: S: High, T: Maintenance, I: No breaking change

#2442 Update environment.yml and fix link to API documentation
  doc/htmldoc/templates/index.html
  environment.yml
Labels: S: Normal, T: Maintenance, I: No breaking change

#2396 Use MAKE variable to pass correct info to child.
  CMakeLists.txt
Labels: T: Bug, S: High, I: No breaking change

#2449 Fix errors in clang-format version handling
  .github/workflows/nestbuildmatrix.yml
  build_support/check_code_style.sh
  build_support/parse_build_log.py
Labels: T: Bug, S: High, I: No breaking change

#2448 Fix image scaling in docs
  doc/htmldoc/static/css/custom.css
Labels: S: Normal, T: Maintenance, I: No breaking change, need reviewer

#2447 Fix some dimensions in developer documentation adex neurons
  models/aeif_cond_alpha.h
  models/aeif_cond_alpha_multisynapse.h
  models/aeif_cond_beta_multisynapse.h
  models/aeif_cond_exp.h
  models/aeif_psc_alpha.h
  models/aeif_psc_delta.h
  models/aeif_psc_delta_clopath.h
  models/aeif_psc_exp.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2451 Conda packages for Apple's M1 are available now
  doc/htmldoc/installation/conda_forge.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2374 Report actual number of synapse created in PyNEST Brunel examples
  build_support/check_code_style.sh
  pynest/examples/brunel_alpha_nest.py
  pynest/examples/brunel_delta_nest.py
  pynest/examples/brunel_exp_multisynapse_nest.py
Labels: S: Normal, T: Maintenance, I: No breaking change, good first issue, stale, need reviewer

#2432 Adjust documentation to the actual behaviour of -Dwith-optimize
  CMakeLists.txt
  doc/htmldoc/installation/cmake_options.rst
Labels: T: Bug, S: High, I: No breaking change, need reviewer

#2373 Ensure that thread-shared variable is initialized by single thread
  nestkernel/event_delivery_manager.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change, stale

#2452 Add documentation on discretization of uniformly distributed delays
  doc/htmldoc/nest_behavior/random_numbers.rst
  pynest/nest/random/hl_api_random.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2415 Fix spatial attribute positions of sliced NodeCollection
  nestkernel/nest.cpp
  nestkernel/nest.h
  nestkernel/nestmodule.cpp
  testsuite/pytests/test_spatial/test_basics.py
Labels: T: Bug, S: Critical, I: User Interface, need reviewer
