Repository nest/nest-simulator, pull requests merged in 2022-06, with the labels that each got.

#2410 Fix typo in model docstring
  models/poisson_generator.h
Labels: T: Bug, S: Normal, I: No breaking change

#2411 Change all apostrophe and quote characters to plain ASCII
  ACKNOWLEDGMENTS.md
  doc/htmldoc/developer_space/guidelines/code_review_guidelines.rst
  doc/htmldoc/developer_space/sli_docs/first-steps.rst
  doc/htmldoc/developer_space/sli_docs/neural-simulations.rst
  doc/htmldoc/developer_space/sli_docs/objects-and-data-types.rst
  doc/htmldoc/developer_space/sli_docs/programming-in-sli.rst
  doc/htmldoc/developer_space/sli_docs/using-files-and-keyboard-input.rst
  doc/htmldoc/developer_space/workflows/development_workflow.rst
  doc/htmldoc/faqs/qa-precise-spike-times.rst
  doc/htmldoc/nest_behavior/random_numbers.rst
  doc/htmldoc/networks/spatially_structured_networks.rst
  doc/htmldoc/neurons/model_details/HillTononiModels.ipynb
  doc/htmldoc/release_notes/v3.0/refguide_nest2_nest3.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_1.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_2.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_3.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_4.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_parrot.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_setlatency.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_sli.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_tips.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_3_connecting_networks_with_synapses.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
  pynest/examples/Potjans_2014/README.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2408 Expose `prepared` flag via kernel status dictionary
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/simulation_manager.cpp
Labels: T: Enhancement, S: Normal, I: External API

#2419 Add link to NEST Desktop lecture material
  doc/htmldoc/installation/lecturer.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2418 Include NEST GPU into the docs
  doc/htmldoc/conf.py
  doc/htmldoc/related_projects.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2423 Change `assertEqual` to `assertAlmostEqual` in node parametrization tests
  testsuite/pytests/test_nodeParametrization.py
Labels: S: High, T: Maintenance, I: No breaking change
