Repository nest/nest-simulator, pull requests merged in 2022-01, with the labels that each got.

#2253 Explicitly use nest namespace to avoid compiler confusion
  nestkernel/nestmodule.cpp
  testsuite/pytests/test_nodeParametrization.py
Labels: S: Normal, I: No breaking change, T: External bug

#2257 More detailed explanation of why C++ ADL requires nest::apply()
  nestkernel/nestmodule.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change

#2258 Fix file formatting error
  nestkernel/nestmodule.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change

#2246 Enhance and clean up model documentation
  models/aeif_cond_alpha_multisynapse.h
  models/aeif_cond_beta_multisynapse.h
  models/aeif_cond_exp.h
  models/aeif_psc_alpha.h
  models/aeif_psc_delta.h
  models/aeif_psc_exp.h
  models/amat2_psc_exp.h
  models/cont_delay_synapse.h
  models/correlation_detector.h
  models/correlomatrix_detector.h
  models/correlospinmatrix_detector.h
  models/gauss_rate.h
  models/gif_cond_exp.h
  models/gif_cond_exp_multisynapse.h
  models/gif_psc_exp.h
  models/gif_psc_exp_multisynapse.h
  models/glif_cond.h
  models/glif_psc.h
  models/ht_synapse.h
  models/iaf_chs_2007.h
  models/iaf_cond_alpha.h
  models/iaf_psc_alpha_canon.h
  models/iaf_psc_alpha_ps.h
  models/iaf_psc_delta.h
  models/iaf_psc_delta_ps.h
  models/iaf_psc_exp.h
  models/iaf_psc_exp_multisynapse.h
  models/iaf_psc_exp_ps.h
  models/iaf_psc_exp_ps_lossless.h
  models/jonke_synapse.h
  models/lin_rate.h
  models/mat2_psc_exp.h
  models/noise_generator.h
  models/parrot_neuron.h
  models/parrot_neuron_ps.h
  models/pp_cond_exp_mc_urbanczik.h
  models/pp_psc_delta.h
  models/pulsepacket_generator.h
  models/rate_transformer_node.h
  models/siegert_neuron.h
  models/sigmoid_rate.h
  models/sigmoid_rate_gg_1998.h
  models/sinusoidal_gamma_generator.h
  models/sinusoidal_poisson_generator.h
  models/static_synapse_hom_w.h
  models/stdp_dopamine_synapse.h
  models/stdp_pl_synapse_hom.h
  models/stdp_synapse_facetshw_hom.h
  models/stdp_synapse_hom.h
  models/tanh_rate.h
  models/threshold_lin_rate.h
  models/tsodyks2_synapse.h
  models/tsodyks_synapse_hom.h
  models/urbanczik_synapse.h
Labels: S: Normal, T: Maintenance, I: Internal API

#2230 Restructure `cmake_options.rst`
  CMakeLists.txt
  doc/userdoc/installation/cmake_options.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2229 Update documentation and refactor comments in iaf_psc_exp current input
  models/iaf_psc_exp.cpp
  models/iaf_psc_exp.h
Labels: T: Enhancement, S: Normal, I: No breaking change

#2238 Update links for live media image
  doc/userdoc/download.rst
  doc/userdoc/installation/livemedia.rst
Labels: S: High, T: Maintenance, I: No breaking change

#2240 Add warning to installation docs about Conda package
  doc/userdoc/installation/index.rst
Labels: S: High, T: Maintenance, I: No breaking change

#2225 Update nest-server command
  bin/nest-server
Labels: T: Enhancement, S: Normal, I: Internal API

#2270 Fix PEP8 errors in doc helper files
  doc/extractor_userdocs.py
  doc/userdoc/conf.py
Labels: S: High, I: No breaking change

#2273 Clean up OpenMP pragmas
  models/correlation_detector.h
  nestkernel/node_manager.cpp
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/test_connect_all_to_all.py
  testsuite/pytests/test_errors.py
  testsuite/pytests/test_events.py
  testsuite/pytests/test_sp/test_conn_builder.py
  testsuite/pytests/test_stdp_triplet_synapse.py
  testsuite/pytests/test_vogels_sprekeler_synapse.py
Labels: S: Normal, T: Maintenance, I: Internal API

#2274 Fix version warning
  doc/userdoc/conf.py
Labels: S: Normal, T: Maintenance

#2279 Re-add version number for clang-format
  build_support/ci_build.sh
Labels: S: High, T: Maintenance, I: No breaking change

#2269 Update microcircuit reference data
  pynest/examples/Potjans_2014/box_plot.png
  pynest/examples/Potjans_2014/raster_plot.png
  pynest/examples/Potjans_2014/reference_data/rate0.dat
  pynest/examples/Potjans_2014/reference_data/rate1.dat
  pynest/examples/Potjans_2014/reference_data/rate2.dat
  pynest/examples/Potjans_2014/reference_data/rate3.dat
  pynest/examples/Potjans_2014/reference_data/rate4.dat
  pynest/examples/Potjans_2014/reference_data/rate5.dat
  pynest/examples/Potjans_2014/reference_data/rate6.dat
  pynest/examples/Potjans_2014/reference_data/rate7.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7718-0.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7719-0.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7720-0.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7721-0.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7722-0.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7723-0.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7724-0.dat
  pynest/examples/Potjans_2014/reference_data/spike_recorder-7725-0.dat
Labels: S: Normal, T: Maintenance, I: No breaking change
