Repository nest/nest-simulator, pull requests merged in 2022-02, with the labels that each got.

#2262 Make `plot_weight_matrices.py` run
  pynest/examples/plot_weight_matrices.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2281 Fix GHA clang format issue
  .github/workflows/nestbuildmatrix.yml
  build_support/static_code_analysis.sh
Labels: T: Bug, S: High, I: No breaking change

#2278 Update `operator+=` logic for composite NodeCollection
  nestkernel/node_collection.cpp
  nestkernel/node_collection.h
Labels: T: Enhancement, S: Normal, I: No breaking change

#2297 Fix search field on readthedocs
  doc/userdoc/_ext/HoverXTooltip.py
  doc/userdoc/static/css/bootstrap.min.css
  doc/userdoc/static/css/bootstrap.min.css.map
  doc/userdoc/static/js/bootstrap.min.js
  doc/userdoc/static/js/bootstrap.min.js.map
  doc/userdoc/static/js/doctools.js
  doc/userdoc/static/js/jquery-2.0.3.min.js
  doc/userdoc/static/js/jquery-migrate-2.0.3.min.js
  doc/userdoc/static/js/underscore-1.3.1.js
  doc/userdoc/static/js/underscore.js
Labels: S: High, T: Maintenance, I: No breaking change

#2299 Fix typo in tsodyks synapse documentation.
  models/tsodyks_synapse.h
  models/tsodyks_synapse_hom.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#1895 Compartmental models for NEST
  doc/userdoc/release_notes/v3.3/index.rst
  models/CMakeLists.txt
  models/cm_compartmentcurrents.cpp
  models/cm_compartmentcurrents.h
  models/cm_default.cpp
  models/cm_default.h
  models/cm_tree.cpp
  models/cm_tree.h
  models/modelsmodule.cpp
  nestkernel/exceptions.cpp
  nestkernel/exceptions.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/recordables_map.h
  pynest/examples/compartmental_model/receptors_and_current.py
  pynest/examples/compartmental_model/two_comps.py
  testsuite/cpptests/CMakeLists.txt
  testsuite/pytests/test_compartmental_model.py
  testsuite/pytests/test_getconnections.py
  testsuite/pytests/test_urbanczik_synapse.py
  testsuite/regressiontests/issue-77.sli
  testsuite/regressiontests/ticket-386.sli
  testsuite/unittests/test_multimeter.sli
  testsuite/unittests/test_multimeter_support.sli
  testsuite/unittests/test_neurons_handle_multiplicity.sli
Labels: T: Enhancement, S: Normal, I: No breaking change
