Repository nest/nest-simulator, pull requests merged in 2022-12, with the labels that each got.

#2528 Add documentation about Simulate() in Run() function
  pynest/nest/lib/hl_api_simulation.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2553 Capitalize Simulator in NEST Simulator
  CONTRIBUTING.md
  SECURITY.md
  doc/htmldoc/conf.py
  doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
  doc/htmldoc/related_projects.rst
  doc/htmldoc/templates/index.html
  doc/htmldoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  pynest/README.rst
  pynest/nest/__init__.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2539 Improve documentation on some HH models
  models/hh_cond_beta_gap_traub.h
  models/hh_cond_exp_traub.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2523 Remove superfluous css and js bootstrap files
  doc/htmldoc/_ext/HoverXTooltip.py
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.css
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.min.css
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.min.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.rtl.css
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.rtl.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.rtl.min.css
  doc/htmldoc/static/css/bootstrap/bootstrap-grid.rtl.min.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.css
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.min.css
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.min.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.rtl.css
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.rtl.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.rtl.min.css
  doc/htmldoc/static/css/bootstrap/bootstrap-reboot.rtl.min.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.css
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.min.css
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.min.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.rtl.css
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.rtl.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.rtl.min.css
  doc/htmldoc/static/css/bootstrap/bootstrap-utilities.rtl.min.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap.css
  doc/htmldoc/static/css/bootstrap/bootstrap.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap.min.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap.rtl.css
  doc/htmldoc/static/css/bootstrap/bootstrap.rtl.css.map
  doc/htmldoc/static/css/bootstrap/bootstrap.rtl.min.css
  doc/htmldoc/static/css/bootstrap/bootstrap.rtl.min.css.map
  doc/htmldoc/static/js/bootstrap/bootstrap.bundle.js
  doc/htmldoc/static/js/bootstrap/bootstrap.bundle.js.map
  doc/htmldoc/static/js/bootstrap/bootstrap.bundle.min.js.map
  doc/htmldoc/static/js/bootstrap/bootstrap.esm.js
  doc/htmldoc/static/js/bootstrap/bootstrap.esm.js.map
  doc/htmldoc/static/js/bootstrap/bootstrap.esm.min.js
  doc/htmldoc/static/js/bootstrap/bootstrap.esm.min.js.map
  doc/htmldoc/static/js/bootstrap/bootstrap.js
  doc/htmldoc/static/js/bootstrap/bootstrap.js.map
  doc/htmldoc/static/js/bootstrap/bootstrap.min.js
  doc/htmldoc/static/js/bootstrap/bootstrap.min.js.map
  doc/htmldoc/static/js/copybutton.js
  doc/htmldoc/templates/index.html
Labels: S: Normal, T: Maintenance, I: No breaking change

#2544 Documentation UX revamp and internal CMake restructuring
  .gitignore
  CMakeLists.txt
  build_support/ci_build.sh
  cmake/ConfigureSummary.cmake
  cmake/FindPandoc.cmake
  cmake/FindSphinx.cmake
  cmake/ProcessOptions.cmake
  doc/CMakeLists.txt
  doc/htmldoc/developer_space/workflows/documentation_workflow/developer_documentation_workflow.rst
  doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
  doc/htmldoc/neurons/exact-integration.rst
  doc/normaldoc.conf.in
Labels: S: Normal, T: Maintenance, I: User Interface

#2537 Fix position of headings in Read the Docs
  doc/htmldoc/static/css/custom.css
Labels: S: Normal, T: Maintenance, I: No breaking change

#2543 Add compiler version to nest-config
  bin/nest-config.in
Labels: T: Enhancement, S: Normal, I: Internal API

#2540 Improved comments on weight positivity for conductance-based multisynapse models
  models/aeif_cond_alpha_multisynapse.h
  models/aeif_cond_beta_multisynapse.h
  models/gif_cond_exp_multisynapse.cpp
  models/gif_cond_exp_multisynapse.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2527 Fix output of nest.spatial in Read the Docs
  doc/htmldoc/ref_material/pynest_apis.rst
  nestkernel/sparse_node_array.cpp
  pynest/nest/lib/hl_api_nodes.py
  pynest/nest/spatial/__init__.py
  pynest/nest/spatial/hl_api_spatial.py
Labels: T: Bug, S: Normal, I: No breaking change

#2545 Remove VERA++ static code checking
  build_support/check_code_style.sh
  build_support/ci_build.sh
  build_support/parse_build_log.py
  build_support/static_code_analysis.sh
  build_support/vera++.profile
Labels: S: Normal, T: Maintenance, I: No breaking change

#2550 Correct documentation for aeif_psc models
  models/aeif_psc_alpha.h
  models/aeif_psc_delta.h
  models/aeif_psc_exp.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2453 Fix and update model_details notebooks
  doc/htmldoc/conf.py
  doc/htmldoc/model_details/HillTononiModels.ipynb
  doc/htmldoc/model_details/IAF_Integration_Singularity.ipynb
  doc/htmldoc/model_details/IAF_neurons_singularity.ipynb
  doc/htmldoc/model_details/aeif_models_implementation.ipynb
  doc/htmldoc/model_details/noise_generator.ipynb
  doc/htmldoc/model_details/siegert_neuron_integration.ipynb
  doc/htmldoc/model_details/test_post_trace.ipynb
  doc/htmldoc/neurons/model_details/aeif_models_implementation.ipynb
  doc/htmldoc/static/img/nb-logo.svg
  doc/htmldoc/static/img/python-logo.svg
  doc/requirements.txt
  models/noise_generator.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2402 Add links in docs to glossary
  doc/htmldoc/_ext/HoverXTooltip.py
  doc/htmldoc/connect_nest/nest_server.rst
  doc/htmldoc/developer_space/guidelines/coding_guidelines_cpp.rst
  doc/htmldoc/developer_space/sli_docs/neural-simulations.rst
  doc/htmldoc/developer_space/workflows/nest_with_ides.rst
  doc/htmldoc/faqs/faqs.rst
  doc/htmldoc/faqs/qa-precise-spike-times.rst
  doc/htmldoc/hpc/parallel_computing.rst
  doc/htmldoc/installation/configuration.rst
  doc/htmldoc/nest_behavior/random_numbers.rst
  doc/htmldoc/nest_behavior/running_simulations.rst
  doc/htmldoc/networks/spatially_structured_networks.rst
  doc/htmldoc/neurons/node_handles.rst
  doc/htmldoc/ref_material/glossary.rst
  doc/htmldoc/synapses/connection_management.rst
  doc/htmldoc/synapses/handling_connections.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_1.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_3.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_4.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_parrot.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_3_connecting_networks_with_synapses.rst
  doc/htmldoc/whats_new/v3.0/features/recording_simulations.rst
  doc/htmldoc/whats_new/v3.0/features/stimulation_backends.rst
Labels: T: Enhancement, S: Normal, I: No breaking change

#2554 Reduce the size of header field in Read the Docs
  doc/htmldoc/static/css/custom.css
Labels: S: Normal, T: Maintenance, I: No breaking change

#2416 Add introductory text for models in documentation
  doc/extractor_userdocs.py
  doc/htmldoc/installation/index.rst
  doc/htmldoc/installation/lecturer.rst
  doc/htmldoc/models/index.rst
  doc/htmldoc/models/models-main.rst
  doc/htmldoc/ref_material/glossary.rst
  doc/htmldoc/static/css/custom.css
  doc/htmldoc/static/img/nestml-logo.png
  doc/htmldoc/understand_index.rst
Labels: T: Enhancement, S: Normal, I: No breaking change

#2522 Refactor collocate_spike_data_buffers
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/event_delivery_manager_impl.h
  nestkernel/spike_data.h
  nestkernel/target.h
  nestkernel/target_table.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2557 Add note that nest.help('model_name') only works if the documentation is built
  doc/htmldoc/getting_help.rst
  pynest/nest/__init__.py
Labels: S: Normal, I: No breaking change

#2565 Remove autogenerated file from models directory
  doc/htmldoc/models/index.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2518 Getter for NodeCollection step on C++ level
  nestkernel/node_collection.h
Labels: T: Enhancement, S: Normal, I: No breaking change

#2571 Make pynestkernel compatible with NumPy 1.24
  pynest/pynestkernel.pyx
Labels: T: Bug, S: Critical, I: No breaking change
