Repository nest/nest-simulator, pull requests merged in 2022-04, with the labels that each got.

#2365 Add GIF / GLIF acronyms to model title in docs
  models/gif_cond_exp.h
  models/gif_cond_exp_multisynapse.h
  models/gif_pop_psc_exp.h
  models/gif_psc_exp.h
  models/gif_psc_exp_multisynapse.h
  models/glif_cond.h
  models/glif_psc.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2298 Generalize double and integer synapse parameters in `connect_arrays()`
  nestkernel/connection_manager.cpp
  testsuite/pytests/test_connect_arrays.py
Labels: T: Bug, S: High, I: No breaking change, stale

#2370 Add missing PyNEST examples to docs
  doc/userdoc/examples/index.rst
  pynest/examples/aeif_cond_beta_multisynapse.py
  pynest/examples/compartmental_model/two_comps.py
  pynest/examples/gif_cond_exp_multisynapse.py
  pynest/examples/glif_cond_neuron.py
  pynest/examples/glif_psc_neuron.py
  pynest/examples/store_restore_network.py
  pynest/examples/synapsecollection.py
  pynest/examples/testiaf.py
  pynest/examples/urbanczik_synapse_example.py
Labels: S: High, T: Maintenance, I: No breaking change

#2352 Update review guidelines
  doc/userdoc/contribute/code_review_guidelines.rst
Labels: T: Enhancement, S: Normal, I: No breaking change
