Repository nest/nest-simulator, pull requests merged in 2023-01, with the labels that each got.

#2551 Allow more than one optimization flag to be set when running CMake
  CMakeLists.txt
  cmake/ProcessOptions.cmake
Labels: T: Enhancement, S: Normal, I: Internal API

#2583 Allow setting host and port for the MPI enabled NEST Server from environment variables
  bin/nest-server-mpi
Labels: T: Enhancement, S: Normal, I: External API

#2575 Move MUSIC status printout up in the summary
  testsuite/do_tests.sh
Labels: T: Bug, S: High, I: No breaking change

#2589 Fix mocker regex to avoid failures when building documentation
  doc/htmldoc/mock_kernel.py
Labels: T: Bug, S: High, I: No breaking change

#2578 Replace while-loop with C++ find_if function
  nestkernel/universal_data_logger.h
Labels: S: Normal, T: Maintenance, I: Internal API

#2582 Change order of pre_run hook in `SimulationManager`
  nestkernel/simulation_manager.cpp
Labels: S: Normal, T: Maintenance, I: Internal API

#2552 Add search box to the index page on Read the Docs
  doc/CMakeLists.txt
  doc/htmldoc/static/css/custom.css
  doc/htmldoc/static/css/normalize.css
  doc/htmldoc/templates/index.html
  doc/htmldoc/templates/tmp_layout.html
Labels: T: Enhancement, S: Normal, I: No breaking change

#2558 Allow getting and setting of synapse trace variable
  models/jonke_synapse.h
  models/stdp_dopamine_synapse.h
  models/stdp_nn_pre_centered_synapse.h
  models/stdp_synapse.h
Labels: T: Enhancement, S: Normal, I: No breaking change

#2587 Refactor NodeCollection
  nestkernel/node_collection.cpp
  nestkernel/node_collection.h
  testsuite/pytests/test_NodeCollection.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2592 Add docstrings for NodeCollection ptr in Node class
  nestkernel/node.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2549 Add the ability to patch the documentation on Read the Docs
  doc/htmldoc/conf.py
Labels: T: Enhancement, S: Normal, I: No breaking change
