Repository nest/nest-simulator, pull requests merged in 2023-12, with the labels that each got.

#3030 Update documentation of video tutorial to clarify version
  doc/htmldoc/tutorials/videos/one_neuron.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3029 Update the documentaton regarding Windows
  doc/htmldoc/installation/docker.rst
  doc/htmldoc/installation/user.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3036 Fix path to docker compose file in documentation
  doc/htmldoc/installation/docker.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3031 Remove unused doxygen groups in developer documentation
  models/aeif_cond_alpha_multisynapse.h
  models/aeif_cond_beta_multisynapse.h
  models/amat2_psc_exp.h
  models/binary_neuron.h
  models/gif_pop_psc_exp.h
  models/gif_psc_exp.h
  models/gif_psc_exp_multisynapse.h
  models/iaf_chs_2007.h
  models/iaf_psc_alpha.h
  models/iaf_psc_alpha_multisynapse.h
  models/iaf_psc_alpha_ps.h
  models/iaf_psc_delta.h
  models/iaf_psc_delta_ps.h
  models/iaf_psc_exp.h
  models/iaf_psc_exp_htum.h
  models/iaf_psc_exp_multisynapse.h
  models/iaf_psc_exp_ps.h
  models/iaf_psc_exp_ps_lossless.h
  models/iaf_tum_2000.h
  models/mat2_psc_exp.h
  models/pp_psc_delta.h
  nestkernel/exceptions.h
  nestkernel/manager_interface.h
  nestkernel/nestmodule.h
  nestkernel/node_manager.h
  nestkernel/recording_backend.h
  nestkernel/stimulation_backend.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3035 Set buffer shrink limit to 20% by default (activates shrinking) and fix documentation
  nestkernel/event_delivery_manager.cpp
  nestkernel/kernel_manager.h
  nestkernel/save_doc_fmt.txt
  pynest/nest/__init__.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3039 Simplify clearing of spike buffers
  nestkernel/event_delivery_manager.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change

#3033 Remove last mentions of C++11 as default
  .github/workflows/nestbuildmatrix.yml
  cmake/Platform/JURON_Base.cmake
  cmake/Platform/JURON_Clang.cmake
  cmake/Platform/JURON_GCC.cmake
  cmake/Platform/JURON_XL.cmake
  doc/htmldoc/developer_space/workflows/nest_with_ides.rst
  doc/htmldoc/installation/cmake_options.rst
  nestkernel/save_doc_fmt.txt
Labels: S: Normal, T: Maintenance, I: No breaking change

#2987 Add ignore_and_fire neuron model
  models/ignore_and_fire.cpp
  models/ignore_and_fire.h
  modelsets/full
  testsuite/pytests/sli2py_neurons/test_neurons_handle_multiplicity.py
  testsuite/pytests/sli2py_regressions/test_issue_77.py
  testsuite/pytests/test_ignore_and_fire_neuron.py
Labels: T: Enhancement, S: Normal

#3044 Register only spikes actually sent with weight_recorder
  models/bernoulli_synapse.h
  models/clopath_synapse.h
  models/cont_delay_synapse.h
  models/diffusion_connection.h
  models/gap_junction.h
  models/ht_synapse.h
  models/jonke_synapse.h
  models/quantal_stp_synapse.h
  models/rate_connection_delayed.h
  models/rate_connection_instantaneous.h
  models/sic_connection.h
  models/static_synapse.h
  models/static_synapse_hom_w.h
  models/stdp_dopamine_synapse.h
  models/stdp_facetshw_synapse_hom.h
  models/stdp_nn_pre_centered_synapse.h
  models/stdp_nn_restr_synapse.h
  models/stdp_nn_symm_synapse.h
  models/stdp_pl_synapse_hom.h
  models/stdp_synapse.h
  models/stdp_synapse_hom.h
  models/stdp_triplet_synapse.h
  models/tsodyks2_synapse.h
  models/tsodyks_synapse.h
  models/tsodyks_synapse_hom.h
  models/urbanczik_synapse.h
  models/vogels_sprekeler_synapse.h
  nestkernel/connector_base.h
  testsuite/pytests/test_weight_recorder_dropped_spikes.py
Labels: T: Bug, S: High, I: No breaking change

#2986 bug fix iaf_psc_exp_multisynapse / sli2py test_iaf_psc_exp_multisynapse
  models/iaf_psc_alpha_multisynapse.cpp
  models/iaf_psc_alpha_multisynapse.h
  models/iaf_psc_exp_multisynapse.cpp
  models/iaf_psc_exp_multisynapse.h
  testsuite/pytests/sli2py_neurons/test_iaf_psc_alpha_multisynapse.py
  testsuite/pytests/sli2py_neurons/test_iaf_psc_exp_multisynapse.py
  testsuite/unittests/test_iaf_psc_exp_multisynapse.sli
Labels: T: Bug, S: Normal, I: No breaking change

#2988 Fix misplaced `assert` statement causing a lot of warnings
  nestkernel/connection.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2990 Models no longer wrapped in SLI Module, model registration and thread-setting in managers revised
  CMakeLists.txt
  build_support/check_copyright_headers.py
  build_support/generate_modelsmodule.py
  cmake/WriteStaticModules_h.cmake
  doc/htmldoc/developer_space/workflows/nest_with_ides.rst
  models/CMakeLists.txt
  models/models.h
  nest/neststartup.cpp
  nestkernel/CMakeLists.txt
  nestkernel/conn_builder.cpp
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/connector_model_impl.h
  nestkernel/event.cpp
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/io_manager.cpp
  nestkernel/io_manager.h
  nestkernel/kernel_manager.cpp
  nestkernel/logging_manager.cpp
  nestkernel/logging_manager.h
  nestkernel/manager_interface.h
  nestkernel/model_manager.cpp
  nestkernel/model_manager.h
  nestkernel/model_manager_impl.h
  nestkernel/modelrange_manager.cpp
  nestkernel/modelrange_manager.h
  nestkernel/mpi_manager.cpp
  nestkernel/mpi_manager.h
  nestkernel/music_manager.cpp
  nestkernel/music_manager.h
  nestkernel/node_manager.cpp
  nestkernel/node_manager.h
  nestkernel/per_thread_bool_indicator.cpp
  nestkernel/random_manager.cpp
  nestkernel/random_manager.h
  nestkernel/secondary_event.h
  nestkernel/secondary_event_impl.h
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
  nestkernel/source_table.cpp
  nestkernel/source_table.h
  nestkernel/sp_manager.cpp
  nestkernel/sp_manager.h
  nestkernel/target_table_devices.cpp
  nestkernel/vp_manager.cpp
  nestkernel/vp_manager.h
  testsuite/regressiontests/ticket-478.sli
Labels: T: Enhancement, S: High, I: No breaking change

#3034 Further improve `iaf_psc_alpha` documentation
  models/iaf_psc_alpha.h
Labels: T: Enhancement, S: High, I: No breaking change

#3050 Increase admonition to warning
  doc/htmldoc/nest_behavior/random_numbers.rst
Labels: S: Normal, T: Maintenance, I: No breaking change
