Repository nest/nest-simulator, pull requests merged in 2023-03, with the labels that each got.

#2621 Remove `get_thread()` function from proxynode class
  nestkernel/node.cpp
  nestkernel/proxynode.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2628 Improve parameter test and implementation
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/test_parameter.py
  testsuite/pytests/test_parameter_operators.py
Labels: T: Enhancement, S: High, I: No breaking change

#2597 Fixing bad coding pattern in loops in connection creation
  nestkernel/connection_creator_impl.h
Labels: S: Normal, I: No breaking change, need reviewer

#2631 Further improvement of parameter operator test implementation
  testsuite/pytests/test_parameter_operators.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2648 Invert delay-related documentation tagging logic for rate connections
  models/rate_connection_delayed.h
  models/rate_connection_instantaneous.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2615 Correctly build connection infrastructure in GetConnections also when secondary events in use
  nestkernel/connection_manager.cpp
  pynest/examples/CampbellSiegert.py
  testsuite/pytests/test_rate_instantaneous_and_delayed.py
  testsuite/unittests/test_hh_psc_alpha_gap.sli
Labels: T: Bug, S: High, I: No breaking change
