Repository nest/nest-simulator, pull requests merged in 2023-09, with the labels that each got.

#2914 Add warning if local_num_threads set by user disagrees with OMP_NUM_THREADS
  nestkernel/vp_manager.cpp
Labels: T: Enhancement, S: Normal, I: User Interface

#2862 Changed total_num_virtual_procs to local_num_threads in hpc benchmark
  pynest/examples/hpc_benchmark.py
Labels: S: Normal, I: External API, I: No breaking change

#2924 Fix 'potential' misspelling
  models/iaf_psc_alpha_ps.h
  models/iaf_psc_delta.h
  models/iaf_psc_delta_ps.h
  models/iaf_psc_exp.h
  models/iaf_psc_exp_htum.h
  models/iaf_psc_exp_ps.h
  models/iaf_psc_exp_ps_lossless.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2920 Filter connections also by target when dumping layer connections
  nestkernel/conn_builder.cpp
  nestkernel/layer_impl.h
  nestkernel/nestmodule.cpp
  nestkernel/node_collection.cpp
  nestkernel/node_collection.h
  pynest/nest/lib/hl_api_helper.py
  pynest/nest/lib/hl_api_spatial.py
  testsuite/pytests/sli2py_regressions/test_issue_2629.py
  testsuite/pytests/test_spatial/test_weight_delay.py
  testsuite/unittests/test_weight_delay.sli
  testsuite/unittests/test_weight_delay_free.sli
Labels: T: Bug, S: High, I: No breaking change

#2922 Port `issue-521.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_521.py
  testsuite/regressiontests/issue-521.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2913 Add support for more addition operations for `NodeCollection`
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/test_NodeCollection.py
  testsuite/pytests/test_connect_node_collection.py
  testsuite/pytests/test_create.py
  testsuite/pytests/test_get_connections.py
  testsuite/pytests/test_get_set.py
  testsuite/pytests/test_node_collection_indexing_slicing.py
  testsuite/pytests/test_node_collection_operations.py
  testsuite/pytests/test_node_collection_to_from_object.py
  testsuite/pytests/test_spatial/test_parameter_apply.py
  testsuite/pytests/test_weight_recorder.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2923 Add note on using Mamba instead of conda
  doc/htmldoc/installation/conda_forge.rst
  doc/htmldoc/installation/conda_tips.rst
  doc/htmldoc/installation/condaenv_install.rst
Labels: S: Normal, T: Maintenance

#2903 Re-add Jupyter notebook download to examples and move script to _ext folder
  doc/htmldoc/_ext/add_button_notebook.py
  doc/htmldoc/conf.py
  doc/htmldoc/static/css/custom.css
Labels: S: Normal, T: Maintenance, I: No breaking change

#2603 Add sphinx-mermaid extension and update userdoc workflow
  doc/htmldoc/conf.py
  doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
  doc/htmldoc/static/css/custom.css
  doc/requirements.txt
  environment.yml
  pynest/examples/README.txt
Labels: T: Enhancement, S: Normal

#2932 Rename microcircuit images
  doc/htmldoc/examples/index.rst
  doc/htmldoc/static/img/potjans_2014_box_plot.png
  doc/htmldoc/static/img/potjans_2014_microcircuit.png
  doc/htmldoc/static/img/potjans_2014_raster_plot.png
  pynest/examples/Potjans_2014/README.rst
Labels: S: Normal, T: Maintenance

#2934 Add documentation builds to cmake options
  doc/htmldoc/installation/cmake_options.rst
  doc/htmldoc/installation/developer.rst
Labels: S: Normal, T: Maintenance

#2917 Port ticket-459.sli to Pytest and fix name for ticket_754.py
  testsuite/pytests/sli2py_regressions/test_ticket_459.py
  testsuite/pytests/sli2py_regressions/test_ticket_754.py
  testsuite/regressiontests/ticket-459.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2937 Fix up typos and missing references to resolve Sphinx warnings
  doc/htmldoc/developer_space/index.rst
  doc/htmldoc/networks/spatially_structured_networks.rst
  doc/htmldoc/ref_material/pynest_api/index.rst
  doc/htmldoc/ref_material/pynest_api/nest.spatial.hl_api_spatial.rst
Labels: S: Normal, T: Maintenance

#2926 Improve NEST performance by revised connection exchange and spike delivery
  CMakeLists.txt
  cmake/ProcessOptions.cmake
  doc/htmldoc/installation/cmake_options.rst
  lib/sli/unittest.sli
  libnestutil/config.h.in
  models/music_event_out_proxy.cpp
  models/rate_neuron_ipn_impl.h
  models/rate_neuron_opn_impl.h
  models/rate_transformer_node_impl.h
  models/spike_recorder.cpp
  nestkernel/CMakeLists.txt
  nestkernel/buffer_resize_log.cpp
  nestkernel/buffer_resize_log.h
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/event.h
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/event_delivery_manager_impl.h
  nestkernel/kernel_manager.cpp
  nestkernel/kernel_manager.h
  nestkernel/mpi_manager.cpp
  nestkernel/mpi_manager.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nest_types.h
  nestkernel/recording_backend_mpi.h
  nestkernel/save_doc_fmt.txt
  nestkernel/send_buffer_position.cpp
  nestkernel/send_buffer_position.h
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
  nestkernel/source_table.cpp
  nestkernel/source_table.h
  nestkernel/sp_manager.cpp
  nestkernel/spike_data.h
  nestkernel/stimulation_backend_mpi.h
  nestkernel/target.h
  pynest/nest/__init__.py
  testsuite/pytests/test_connect_after_simulate.py
  testsuite/pytests/test_mip_corrdet.py
  testsuite/pytests/test_ongrid_offgrid.py
  testsuite/pytests/test_regression_issue-1034.py
  testsuite/pytests/test_spatial/test_basics.py
  testsuite/pytests/test_spatial/test_mask_anchors_boundaries.py
  testsuite/pytests/test_spatial/test_weight_delay.py
  testsuite/pytests/test_spike_transmission.py
  testsuite/pytests/test_status.py
  testsuite/pytests/test_stdp_synapse.py
  testsuite/regressiontests/ticket-85.sli
Labels: T: Enhancement, S: High, I: Behavior changes

#2601 Remove NodeCollection pointer from Node class
  nestkernel/node.h
  nestkernel/node_collection.h
  nestkernel/node_manager.cpp
  nestkernel/node_manager.h
  nestkernel/parameter.cpp
  nestkernel/spatial.cpp
Labels: T: Enhancement, S: Normal, I: Internal API

#2941 Fix indentation in PyNEST API
  doc/htmldoc/static/css/custom.css
Labels: S: Normal, T: Maintenance

#2856 Completely revised iaf_psc_alpha user documentation
  environment.yml
  models/iaf_psc_alpha.h
Labels: T: Discussion, S: Normal, I: No breaking change

#2881 Added package attrs to environment.yml
  environment.yml
Labels: T: Enhancement, S: Normal, I: No breaking change

#2940 Fix up HTML output to clean up browser warnings
  doc/htmldoc/conf.py
  doc/htmldoc/templates/layout.html
Labels: S: Normal, T: Maintenance

#2943 Remove mentions of vera++ in docs
  doc/htmldoc/developer_space/guidelines/coding_guidelines_check.rst
  doc/htmldoc/developer_space/guidelines/coding_guidelines_cpp.rst
Labels: S: Normal, T: Maintenance

#2945 Correct limit for test on target fields and remove duplicate assertions
  nestkernel/target.h
  testsuite/cpptests/test_target_fields.h
Labels: T: Bug, S: Critical, I: No breaking change

#2946 Improve message about OMP_THREAD_NUM on startup
  doc/htmldoc/hpc/parallel_computing.rst
  doc/htmldoc/ref_material/pynest_api/nest.NestModule.rst
  nestkernel/vp_manager.cpp
  nestkernel/vp_manager.h
Labels: T: Enhancement, S: High, I: No breaking change

#2933 Add details on Hodgkin Huxley models, based on asynchronicity discussion
  doc/htmldoc/model_details/hh_details.rst
  models/hh_cond_beta_gap_traub.h
  models/hh_cond_exp_traub.h
  models/hh_psc_alpha.h
  models/hh_psc_alpha_clopath.h
  models/hh_psc_alpha_gap.h
Labels: S: Normal, T: Maintenance

#2936 Add `clang-format` pre-commit hook
  .pre-commit-config.yaml
Labels: T: Enhancement, S: Normal, I: No breaking change

#2948 Fix bug in reconstruction of connection data structures after disconnect and fix small problems with examples
  examples/run_examples.sh
  nestkernel/connection_manager.cpp
  nestkernel/connector_base.h
  nestkernel/simulation_manager.cpp
  nestkernel/source_table.cpp
  pynest/examples/evaluate_quantal_stp_synapse.py
  pynest/examples/pong/README.rst
  pynest/examples/store_restore_network.py
  testsuite/pytests/test_spike_transmission_after_disconnect.py
Labels: T: Bug, S: Critical, I: Behavior changes

#2942 Cleanup NEST Server environment variable handling
  bin/nest-server
  doc/htmldoc/connect_nest/nest_server.rst
  doc/htmldoc/whats_new/v3.6/index.rst
  pynest/nest/server/hl_api_server.py
Labels: T: Enhancement, S: High

#2947 Add text for what's new 3.6
  doc/htmldoc/whats_new/index.rst
  doc/htmldoc/whats_new/v3.6/index.rst
Labels: S: Normal, T: Maintenance

#2950 Fixes to some examples
  pynest/examples/brunel_alpha_evolution_strategies.py
  pynest/examples/pong/README.rst
  pynest/examples/pong/generate_gif.py
  pynest/examples/sudoku/README.rst
  pynest/examples/sudoku/plot_progress.py
Labels: T: Bug, S: Normal, I: No breaking change

#2958 Fix broken links in documenation
  doc/htmldoc/whats_new/v3.6/index.rst
  models/sic_connection.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2952 Fix default origins for NEST Server
  pynest/nest/server/hl_api_server.py
Labels: T: Bug, S: Normal, I: No breaking change

#2959 Fix default origins for NEST Server
  pynest/nest/server/hl_api_server.py
Labels: T: Bug, S: Normal, I: No breaking change

#2954 Fix image generation in Sudoku and Pong examples for compatibility with Matplotlib 3.8
  pynest/examples/pong/generate_gif.py
  pynest/examples/sudoku/plot_progress.py
Labels: T: Bug, S: Normal, I: No breaking change

#2906 Remove assimulo from requirements
  doc/htmldoc/model_details/aeif_models_implementation.ipynb
  environment.yml
Labels: S: Normal, T: Maintenance, I: No breaking change
