Repository nest/nest-simulator, pull requests merged in 2023-05, with the labels that each got.

#2753 Require Cython >= 0.29.14 to avoid tp_print problem
  doc/requirements.txt
Labels: T: Bug, S: Critical, I: No breaking change

#2758 Add documentation about deadlock in mpi processes
  doc/htmldoc/hpc/parallel_computing.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2766 Update readthedocs.yml to resolve build error from incompatible urllib3 version
  .readthedocs.yml
Labels: S: High, T: Maintenance

#2401 Add documentation regarding HPC systems
  doc/htmldoc/hpc/benchmarking.rst
  doc/htmldoc/hpc/index.rst
  doc/htmldoc/hpc/mpi_processes.rst
  doc/htmldoc/hpc/optimizing_nest.rst
  doc/htmldoc/hpc/overview_hardware.rst
  doc/htmldoc/hpc/parallel_computing.rst
  doc/htmldoc/hpc/slurm_script.rst
  doc/htmldoc/hpc/threading.rst
  doc/htmldoc/static/img/CPUs-cross-empty.gif
  doc/htmldoc/static/img/CPUs-lin-empty.gif
  doc/htmldoc/static/img/CPUs-lin-lin.gif
  doc/htmldoc/static/img/CPUs-lin-sparse.gif
  doc/htmldoc/static/img/hpc-hardware.svg
  doc/htmldoc/static/img/multi-area-model_5faa0e9c.png
  doc/htmldoc/understand_index.rst
Labels: T: Enhancement, S: Normal, I: No breaking change

#2763 Get Sphinx build working in CI
  .github/workflows/nestbuildmatrix.yml
Labels: S: Normal, T: Maintenance, I: No breaking change

#2778 Add new dockerhub repository to the docker documentation
  README.md
  doc/htmldoc/connect_nest/nest_server.rst
  doc/htmldoc/installation/docker.rst
  doc/htmldoc/troubleshooting.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2788 Return valid version information also when git is unavailable
  build_support/version_info.sh
Labels: T: Bug, S: High, I: Internal API

#2791 Update doc directory readme
  doc/README.md
Labels: T: Bug, ZC: Documentation

#2798 Update vale version and fix CI package index
  .github/styles/nest-styles/Units.yml
  .github/workflows/nestbuildmatrix.yml
Labels: S: Normal, T: Maintenance

#2785 Make multapses and autapses flags more visible in documentation
  doc/htmldoc/synapses/connection_management.rst
Labels: T: Enhancement, ZC: Documentation

#2793 Clean up and fix clickable images in installation instructions
  doc/htmldoc/installation/docker.rst
  doc/htmldoc/installation/user.rst
Labels: S: Normal, T: Maintenance, I: No breaking change
