Repository nest/nest-simulator, pull requests merged in 2023-02, with the labels that each got.

#2572 Fix various Sphinx warnings
  doc/extractor_userdocs.py
  doc/htmldoc/conf.py
  doc/htmldoc/developer_space/guidelines/code_review_guidelines.rst
  doc/htmldoc/developer_space/guidelines/naming_conventions.rst
  doc/htmldoc/developer_space/index.rst
  doc/htmldoc/developer_space/sli_docs/neural-simulations.rst
  doc/htmldoc/developer_space/sli_docs/objects-and-data-types.rst
  doc/htmldoc/developer_space/workflows/nest_with_ides.rst
  doc/htmldoc/examples/cortical_microcircuit_index.rst
  doc/htmldoc/examples/index.rst
  doc/htmldoc/getting_help.rst
  doc/htmldoc/model_details/IAF_Integration_Singularity.ipynb
  doc/htmldoc/model_details/index.rst
  doc/htmldoc/model_details/noise_generator.ipynb
  doc/htmldoc/model_details/post_trace_computation.ipynb
  doc/htmldoc/model_details/test_post_trace.ipynb
  doc/htmldoc/models/models-main.rst
  doc/htmldoc/models/models-toc.rst
  doc/htmldoc/nest_behavior/random_numbers.rst
  doc/htmldoc/networks/spatially_structured_networks.rst
  doc/htmldoc/neurons/exact-integration.rst
  doc/htmldoc/neurons/index.rst
  doc/htmldoc/neurons/parametrization.rst
  doc/htmldoc/ref_material/glossary.rst
  doc/htmldoc/ref_material/pynest_apis.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_3.rst
  doc/htmldoc/understand_index.rst
  doc/htmldoc/whats_new/index.rst
  doc/htmldoc/whats_new/v3.0/features/index.rst
  doc/slihelp_generator/generate_help.py
  doc/slihelp_generator/helpers_sli.py
  doc/slihelp_generator/writers.py
  models/hh_cond_beta_gap_traub.h
  models/sigmoid_rate_gg_1998.h
  models/spike_dilutor.h
  nestkernel/recording_backend_sionlib.h
  pynest/examples/BrodyHopfield.py
  pynest/examples/Potjans_2014/README.rst
  pynest/examples/README.rst
  pynest/examples/compartmental_model/receptors_and_current.py
  pynest/examples/evaluate_tsodyks2_synapse.py
  pynest/examples/gif_population.py
  pynest/examples/pong/pong.py
  pynest/examples/sudoku/helpers_sudoku.py
  pynest/examples/sudoku/plot_progress.py
  pynest/examples/sudoku/sudoku_solver.py
  pynest/nest/lib/hl_api_connections.py
  pynest/nest/lib/hl_api_nodes.py
  pynest/nest/lib/hl_api_simulation.py
  pynest/nest/lib/hl_api_spatial.py
  pynest/nest/lib/hl_api_types.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2600 Fix patch application for documentation
  doc/htmldoc/conf.py
Labels: T: Bug, S: Critical, I: No breaking change

#2584 Add `userdict` in in PyNEST to let users store custom data with the kernel
  pynest/nest/__init__.py
Labels: T: Enhancement, S: Normal, I: External API

#2602 Fix the patch application for the documentation (again)
  doc/htmldoc/conf.py
Labels: T: Bug, S: High, I: No breaking change

#2609 Cherry-picked changes for post-release doc-patching
  doc/htmldoc/conf.py
Labels: T: Enhancement, S: Critical, I: No breaking change

#2607 Cherry-picked changes to add `userdict` in PyNEST
  pynest/nest/__init__.py
Labels: T: Enhancement, S: High, I: User Interface
