Repository nest/nest-simulator, pull requests merged in 2023-07, with the labels that each got.

#2845 Remove redundant SLI tests
  testsuite/regressiontests/issue-437.sli
  testsuite/regressiontests/issue-596.sli
  testsuite/unittests/issue-565.sli
  testsuite/unittests/test_time_input.sli
  testsuite/unittests/test_two_devices.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2850 Fix typo on docs landing page
  doc/htmldoc/templates/index.html
Labels: S: Normal, T: Maintenance

#2832 Fix formatting of developer guidelines - naming conventions
  doc/htmldoc/developer_space/guidelines/naming_conventions.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#2823 Update microcircuit docs regarding virtual process constraint and fix images
  doc/htmldoc/conf.py
  doc/htmldoc/static/img/box_plot.png
  doc/htmldoc/static/img/microcircuit.png
  doc/htmldoc/static/img/raster_plot.png
  pynest/examples/Potjans_2014/README.rst
  pynest/examples/Potjans_2014/microcircuit.png
  pynest/examples/Potjans_2014/sim_params.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2836 Set copybutton to only copy input lines in docs
  doc/htmldoc/conf.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2846 Add a custom 404 page for Read the docs
  doc/htmldoc/404.rst
  doc/htmldoc/conf.py
  doc/requirements.txt
  environment.yml
Labels: T: Enhancement, S: Normal, I: No breaking change

#2855 Remove duplicate notebook and all references to it.
  doc/htmldoc/model_details/IAF_neurons_singularity.ipynb
  models/gif_psc_exp.h
  models/gif_psc_exp_multisynapse.h
  models/glif_psc.h
  models/iaf_psc_alpha.h
  models/iaf_psc_alpha_multisynapse.h
  models/iaf_psc_alpha_ps.h
  models/iaf_psc_exp.h
  models/iaf_psc_exp_htum.h
  models/iaf_psc_exp_multisynapse.h
  models/iaf_psc_exp_ps.h
  models/iaf_psc_exp_ps_lossless.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2857 Improve error checking in MPI IO backends
  nestkernel/exceptions.cpp
  nestkernel/exceptions.h
  nestkernel/recording_backend_mpi.cpp
  nestkernel/stimulation_backend_mpi.cpp
Labels: T: Enhancement, S: Normal, I: No breaking change

#2858 Add support to set mpi address via device status
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/recording_backend_mpi.cpp
  nestkernel/recording_backend_mpi.h
  nestkernel/stimulation_backend_mpi.cpp
  nestkernel/stimulation_backend_mpi.h
Labels: T: Enhancement, S: Normal, I: No breaking change

#2835 Replace hand-written modelsmodule by a code generation framework
  CMakeLists.txt
  build_support/generate_modelsmodule.py
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  cmake/WriteStaticModules_h.cmake
  doc/htmldoc/installation/cmake_options.rst
  doc/htmldoc/models/models-main.rst
  models/CMakeLists.txt
  models/diffusion_connection.h
  models/gap_junction.h
  models/glif_cond.h
  models/glif_psc.h
  models/mcculloch_pitts_neuron.h
  models/modelsmodule.cpp
  models/rate_connection_delayed.h
  models/rate_connection_instantaneous.h
  models/stdp_facetshw_synapse_hom.h
  models/stdp_facetshw_synapse_hom_impl.h
  modelsets/binary
  modelsets/full
  modelsets/iaf_minimal
  modelsets/precise
  modelsets/rate
  nest/CMakeLists.txt
  pynest/CMakeLists.txt
Labels: T: Enhancement, S: Normal, I: Internal API

#2853 Allow setting volume_transmitter via NodeCollection, instead of naked ID
  doc/htmldoc/whats_new/v3.6/index.rst
  models/CMakeLists.txt
  models/stdp_dopamine_synapse.cpp
  models/stdp_dopamine_synapse.h
  nestkernel/CMakeLists.txt
  nestkernel/common_synapse_properties.cpp
  nestkernel/common_synapse_properties.h
  nestkernel/connector_base_impl.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/node_collection.cpp
  nestkernel/node_collection.h
  pynest/examples/pong/networks.py
  testsuite/pytests/connect_test_base.py
  testsuite/pytests/sli2py_regressions/test_issue_410.py
  testsuite/pytests/sli2py_synapses/test_common_props_setting.py
  testsuite/pytests/test_labeled_synapses.py
  testsuite/regressiontests/issue-211.sli
  testsuite/regressiontests/issue-735.sli
  testsuite/regressiontests/issue-737-threads.sli
  testsuite/regressiontests/ticket-716.sli
  testsuite/unittests/test_common_props_setting.sli
Labels: T: Enhancement, S: Normal, I: Behavior changes

#2665 Set sender node id info with correct target lcid
  nestkernel/connector_base.h
  nestkernel/event_delivery_manager.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change

#2632 Enhance module imports in NEST Server
  pynest/nest/server/hl_api_server.py
Labels: T: Enhancement, S: Normal, I: No breaking change
