Repository nest/nest-simulator, pull requests merged in 2023-08, with the labels that each got.

#2506 Modernize the codebase - convert C-style casts to static_casts
  libnestutil/numerics.cpp
  libnestutil/stopwatch.h
  nestkernel/layer_impl.h
  nestkernel/model.cpp
  nestkernel/model.h
  nestkernel/model_manager.cpp
  nestkernel/ring_buffer.h
  nestkernel/simulation_manager.cpp
  nestkernel/slice_ring_buffer.h
  sli/interpret.cc
  sli/scanner.cc
  sli/sliarray.cc
  sli/slicontrol.cc
  sli/slidata.cc
  sli/sligraphics.cc
  sli/tarrayobj.cc
  sli/tarrayobj.h
  testsuite/cpptests/test_block_vector.h
Labels: S: Normal, T: Maintenance, I: Internal API

#2869 Fix type check to use isinstance()
  pynest/nest/lib/hl_api_helper.py
Labels: T: Bug, S: Critical, I: No breaking change

#2882 Allow `NodeCollection` slicing with list of NumPy integers
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/sli2py_regressions/test_issue_2637.py
Labels: T: Enhancement, S: Normal, I: External API

#2886 Add NEST favicon to documentation webpage
  doc/htmldoc/conf.py
  doc/htmldoc/static/img/nest_favicon.ico
  doc/htmldoc/templates/index.html
Labels: T: Enhancement, S: Normal

#2887 Fix malformed table in models documentation
  models/stdp_dopamine_synapse.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2884 Hike minimum required CMake version to 3.19
  CMakeLists.txt
Labels: T: Bug, S: High, I: No breaking change

#2885 Test iaf ps psp poisson accuracy (sli2py)
  testsuite/pytests/test_iaf_ps_psp_poisson_accuracy.py
  testsuite/unittests/test_iaf_ps_psp_poisson_accuracy.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2872 Fail gracefully when `node_id` 0 is used to access non-existent node
  nestkernel/modelrange_manager.h
  testsuite/pytests/sli2py_regressions/test_issue_2636_2795.py
Labels: T: Bug, S: High, I: No breaking change

#2864 Mention parameter `t_ref` in documentation
  models/hh_psc_alpha.h
  models/hh_psc_alpha_clopath.h
  models/hh_psc_alpha_gap.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2899 Port `test_ntree_split` from SLI-2-Py
  testsuite/pytests/test_spatial/test_ntree_split.py
  testsuite/unittests/test_ntree_split.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2905 Port `test_rate_connections` from SLI-2-Py
  testsuite/pytests/sli2py_connect/test_rate_connections.py
  testsuite/unittests/test_rate_connections.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2900 Improve robustness of `test_ticket_80_175_179.py`
  testsuite/pytests/sli2py_regressions/test_ticket_80_175_179.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2907 Update DOI to NEST 3.5 in README
  README.md
Labels: S: Normal, T: Maintenance, I: No breaking change

#2588 Separate PyNEST API modules into separate pages in documentation
  doc/htmldoc/_ext/extract_api_functions.py
  doc/htmldoc/conf.py
  doc/htmldoc/index.rst
  doc/htmldoc/ref_material/pynest_api/index.rst
  doc/htmldoc/ref_material/pynest_api/nest.NestModule.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_connections.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_info.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_models.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_nodes.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_parallel_computing.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_simulation.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_sonata.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_spatial.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_types.rst
  doc/htmldoc/ref_material/pynest_api/nest.logic.hl_api_logic.rst
  doc/htmldoc/ref_material/pynest_api/nest.math.hl_api_math.rst
  doc/htmldoc/ref_material/pynest_api/nest.random.hl_api_random.rst
  doc/htmldoc/ref_material/pynest_api/nest.raster_plot.rst
  doc/htmldoc/ref_material/pynest_api/nest.server.hl_api_server.rst
  doc/htmldoc/ref_material/pynest_api/nest.spatial.hl_api_spatial.rst
  doc/htmldoc/ref_material/pynest_api/nest.spatial_distributions.hl_api_spatial_distributions.rst
  doc/htmldoc/ref_material/pynest_api/nest.visualization.rst
  doc/htmldoc/ref_material/pynest_api/nest.voltage_trace.rst
  doc/htmldoc/ref_material/pynest_apis.rst
  doc/htmldoc/static/css/custom.css
  doc/htmldoc/static/js/custom.js
  doc/htmldoc/templates/index.html
  doc/requirements.txt
  pynest/nest/__init__.py
  pynest/nest/lib/hl_api_sonata.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2888 Move deprecated tests to `sli2py_ignore` directory
  testsuite/regressiontests/sli2py_ignore/issue-2052.sli
  testsuite/unittests/sli2py_ignore/test_DoubleVector_IntVector.sli
  testsuite/unittests/sli2py_ignore/test_Map.sli
  testsuite/unittests/sli2py_ignore/test_MapIndexed.sli
  testsuite/unittests/sli2py_ignore/test_connect.sli
  testsuite/unittests/sli2py_ignore/test_cva.sli
  testsuite/unittests/sli2py_ignore/test_cvi.sli
  testsuite/unittests/sli2py_ignore/test_dirname.sli
  testsuite/unittests/sli2py_ignore/test_fast_operators.sli
  testsuite/unittests/sli2py_ignore/test_lambertw.sli
  testsuite/unittests/sli2py_ignore/test_message.sli
  testsuite/unittests/sli2py_ignore/test_round.sli
  testsuite/unittests/sli2py_ignore/test_sort.sli
  testsuite/unittests/sli2py_ignore/test_spike_dilutor.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2635 Serialize all responses
  pynest/nest/lib/hl_api_types.py
  pynest/nest/server/hl_api_server.py
Labels: S: Normal, T: Maintenance, I: External API

#2810 Port `issue-2282.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_2282.py
  testsuite/regressiontests/issue-2282.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2808 Port `issue-1610.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_1610.py
  testsuite/regressiontests/issue-1610.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2803 Port `issue-1212.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_1212.py
  testsuite/regressiontests/issue-1212.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2802 Port `issue-1140.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_1140.py
  testsuite/regressiontests/issue-1140.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2801 Port `issue-1100.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_1100.py
  testsuite/regressiontests/issue-1100.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2809 Port `issue-1640.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_1640.py
  testsuite/regressiontests/issue-1640.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2794 Port `test_distance` from SLI-2-Py
  testsuite/pytests/test_spatial/test_distance.py
  testsuite/unittests/test_distance.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2777 Port `test_multiple_random_source_stepping` from SLI-2-Py
  testsuite/pytests/sli2py_other/test_multiple_random_source_stepping.py
  testsuite/unittests/test_multiple_random_source_stepping.sli
Labels: T: Discussion, S: Normal, I: No breaking change

#2772 Port `issue-105.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_105.py
  testsuite/regressiontests/issue-105.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2800 Port `issue-1085.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_1085.py
  testsuite/regressiontests/issue-1085.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2797 Port `issue-211.sli` to Pytest
  testsuite/pytests/sli2py_regressions/test_issue_211.py
  testsuite/regressiontests/issue-211.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2782 Port `test_ginzburg_and_mcculloch` from SLI-2-Py
  testsuite/pytests/sli2py_neurons/test_ginzburg_and_mcculloch.py
  testsuite/unittests/test_ginzburg_and_mcculloch.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2767 Port `issue-77.sli` from SLI-2-Py
  testsuite/pytests/sli2py_neurons/test_neurons_handle_multiplicity.py
  testsuite/pytests/sli2py_recording/test_multimeter_stepping.py
  testsuite/pytests/sli2py_regressions/test_issue_77.py
  testsuite/pytests/test_multimeter.py
  testsuite/regressiontests/issue-77.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2754 Port `test_multiple_multimeter` from SLI-2-Py
  testsuite/pytests/sli2py_neurons/test_add_freeze_thaw.py
  testsuite/pytests/sli2py_recording/test_multimeter_freeze_thaw.py
  testsuite/pytests/test_multimeter.py
  testsuite/unittests/test_multiple_multimeter.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2429 Add flags for autapses and multapses in `structural_plasticity_synapses`
  nestkernel/conn_builder.cpp
  nestkernel/conn_builder.h
  nestkernel/sp_manager.cpp
  pynest/examples/structural_plasticity.py
  testsuite/pytests/test_sp/test_sp_autapses_multapses.py
  testsuite/pytests/test_sp/test_sp_manager.py
Labels: T: Enhancement, S: Normal, I: External API

#2387 Add rectified Gabor distribution for nest.spatial
  doc/htmldoc/networks/scripts/connections.py
  doc/htmldoc/networks/spatially_structured_networks.rst
  nestkernel/nestmodule.cpp
  nestkernel/parameter.cpp
  nestkernel/parameter.h
  pynest/nest/spatial_distributions/hl_api_spatial_distributions.py
  testsuite/pytests/test_spatial/test_spatial_distributions.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2769 Port `issue-545.sli` to py
  testsuite/pytests/sli2py_regressions/test_issue_545.py
  testsuite/regressiontests/issue-545.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2916 Remove test that is no longer relevant
  testsuite/unittests/sli2py_ignore/test_rows_cols_pos.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2764 Port `test_GetConnections` from SLI-2-Py
  testsuite/pytests/sli2py_connect/test_getconnections_multiple_syn_models.py
  testsuite/unittests/test_GetConnections.sli
Labels: S: Normal, T: Maintenance, I: No breaking change
