Repository nest/nest-simulator, pull requests merged in 2023-10, with the labels that each got.

#2965 Update extension for API extractor
  doc/htmldoc/_ext/extract_api_functions.py
  doc/htmldoc/conf.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2972 Properly suppress pylint complaints about unused plt in tests
  testsuite/pytests/test_stdp_pl_synapse_hom.py
  testsuite/pytests/test_stdp_synapse.py
Labels: T: Bug, S: Critical, I: No breaking change

#2929 Sli2py `iaf_psc_alpha_multisynapse`
  testsuite/pytests/test_iaf_psc_alpha_multisynapse.py
  testsuite/unittests/test_iaf_psc_alpha_multisynapse.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2961 Port `test_thread_local_ids.sli` to Pytest
  testsuite/pytests/sli2py_other/test_thread_local_ids.py
  testsuite/unittests/test_thread_local_ids.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2963 Port `test_wfr_settings.sli` to Pytest
  testsuite/pytests/sli2py_other/test_wfr_settings.py
  testsuite/unittests/test_wfr_settings.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2964 Port `issue-311` from SLI-2-Py
  testsuite/pytests/sli2py_regressions/test_issue_311.py
  testsuite/regressiontests/issue-311.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2968 Allow `isort` pre-commit to make in-place changes
  .pre-commit-config.yaml
Labels: T: Bug, S: High, I: No breaking change

#2962 Port `test_steppedsim.sli` to Pytest
  testsuite/pytests/sli2py_other/test_stepped_simulation.py
  testsuite/unittests/test_steppedsim.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2976 Port sinusoidal generator tests (SLI-2-Py)
  testsuite/pytests/sli2py_stimulating/test_sinusoidal_generators.py
  testsuite/pytests/sli2py_stimulating/test_sinusoidal_poisson_generator.py
  testsuite/unittests/test_sinusoidal_gamma_generator.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2978 Port `test_setconnections_threads.sli` to Pytest
  testsuite/pytests/sli2py_synapses/test_synapse_collection_set_get_multithreading.py
  testsuite/unittests/test_setconnections_threads.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2971 Add `iaf_tum_2000`: a neuron model with integrated short-term plasticity synapse
  doc/htmldoc/examples/index.rst
  models/iaf_tum_2000.cpp
  models/iaf_tum_2000.h
  models/quantal_stp_synapse.h
  models/quantal_stp_synapse_impl.h
  models/tsodyks2_synapse.h
  models/tsodyks_synapse.h
  modelsets/full
  pynest/examples/iaf_tum_2000_short_term_depression.py
  pynest/examples/iaf_tum_2000_short_term_facilitation.py
  pynest/examples/tsodyks_depressing.py
  pynest/examples/tsodyks_facilitating.py
  testsuite/mpitests/test_mini_brunel_ps.sli
  testsuite/pytests/sli2py_neurons/test_iaf_tum_2000.py
  testsuite/pytests/test_refractory.py
  testsuite/regressiontests/ticket-686-positive-parameters.sli
Labels: T: Enhancement, S: Normal, I: No breaking change

#2980 Minor cleanup of code and comments
  nestkernel/logging_manager.h
  nestkernel/manager_interface.h
  nestkernel/node.h
  nestkernel/node_manager.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change
