Repository nest/nest-simulator, pull requests merged in 2023-04, with the labels that each got.

#2651 Further improve style of parameter test implementation
  testsuite/pytests/test_parameter_operators.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#2443 Fix STDP k-value error for edge case
  nestkernel/archiving_node.cpp
  testsuite/pytests/test_stdp_synapse.py
  testsuite/regressiontests/issue-77.sli
Labels: T: Bug, S: High, I: No breaking change

#2657 Revise some spatial tests to pytest style; avoids numercial issues due to float comparisons
  testsuite/pytests/test_spatial/test_SynapseCollection_distance.py
  testsuite/pytests/test_spatial/test_plotting.py
Labels: T: Bug, S: High, I: No breaking change

#2652 Convert multimeter test from SLI to Python implementation
  .github/workflows/nestbuildmatrix.yml
  testsuite/pytests/test_multimeter.py
  testsuite/unittests/test_multimeter.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2656 Remove NEST Server Client from nest-simulator repository
  doc/htmldoc/connect_nest/nest_server.rst
  examples/NESTServerClient/NESTServerClient.py
  examples/NESTServerClient/__init__.py
  examples/NESTServerClient/examples/NESTClient_example.py
  examples/NESTServerClient/examples/NESTClient_script.py
  examples/NESTServerClient/examples/__init__.py
  examples/NESTServerClient/setup.py
Labels: S: Normal, T: Maintenance, I: External API

#2655 Make helper libraries static and don't install the archive files
  libnestutil/CMakeLists.txt
  models/CMakeLists.txt
  nestkernel/CMakeLists.txt
Labels: S: Normal, T: Maintenance, I: No breaking change

#2658 Make it an error to set multiple threads if NEST was built without thread support
  nestkernel/vp_manager.cpp
  testsuite/mpitests/test_get_nodes.sli
  testsuite/mpitests/test_sinusoidal_poisson_generator_5.sli
  testsuite/mpitests/test_sinusoidal_poisson_generator_6.sli
  testsuite/mpitests/topo_mpi_test_pairwise_bernoulli_on_source.sli
  testsuite/mpitests/topo_mpi_test_pairwise_bernoulli_on_target.sli
  testsuite/pytests/mpi/2/test_connect_arrays_mpi.py
  testsuite/pytests/mpi/4/test_consistent_local_vps.py
  testsuite/pytests/test_connect_all_to_all.py
  testsuite/pytests/test_connect_array_fixed_outdegree.py
  testsuite/pytests/test_connect_arrays.py
  testsuite/pytests/test_connect_fixed_indegree.py
  testsuite/pytests/test_connect_fixed_outdegree.py
  testsuite/pytests/test_connect_fixed_total_number.py
  testsuite/pytests/test_connect_one_to_one.py
  testsuite/pytests/test_connect_pairwise_bernoulli.py
  testsuite/pytests/test_connect_symmetric_pairwise_bernoulli.py
  testsuite/pytests/test_recording_backend_ascii.py
  testsuite/pytests/test_recording_backend_memory.py
  testsuite/pytests/test_weight_recorder.py
  testsuite/regressiontests/issue-1640.sli
  testsuite/regressiontests/ticket-643.sli
  testsuite/regressiontests/ticket-881.sli
  testsuite/unittests/test_GetConnections.sli
  testsuite/unittests/test_sinusoidal_gamma_generator.sli
  testsuite/unittests/test_sinusoidal_poisson_generator.sli
Labels: S: Normal, T: Maintenance, I: Behavior changes

#2659 Fix build of extension modules after change to static helper libraries
  CMakeLists.txt
Labels: T: Bug, S: Critical, I: External API

#2660 Fix OpenMP issues on CI under macOS and re-activate testing with threads for macOS
  .github/workflows/nestbuildmatrix.yml
  build_support/ci_build.sh
Labels: S: High, T: Maintenance, I: No breaking change

#2676 Fix typo in existing `CopyModel` Pytest and remove obsolete SLI test
  testsuite/pytests/test_copy_model.py
  testsuite/unittests/test_copymodel.sli
Labels: S: Normal, T: Maintenance, I: Internal API

#2677 Catch all exceptions in SimulationManager::update_()
  nestkernel/simulation_manager.cpp
Labels: T: Bug, ZC: Kernel, S: High

#2662 Add comment on min delay
  pynest/examples/Potjans_2014/network.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2704 Ensure VP number, RNG type and RNG seed can be set in any order
  nestkernel/random_manager.cpp
  pyproject.toml
  testsuite/pytests/neurons/test_add_freeze_thaw.py
  testsuite/pytests/sli2py_neurons/test_add_freeze_thaw.py
  testsuite/pytests/sli2py_regressions/ticket_754.py
  testsuite/regressiontests/ticket-754.sli
Labels: T: Bug, S: High, I: No breaking change

#2720 Fix conftest fixtures
  testsuite/pytests/conftest.py
Labels: T: Bug

#2728 Remove installation of PyNEST egg-info and dependencies from setup.py
  pynest/CMakeLists.txt
Labels: S: Normal, T: Maintenance, I: Internal API

#2749 Microcircuit model quick fix for issue #2741
  pynest/examples/Potjans_2014/network.py
Labels: T: Bug, S: High, I: No breaking change
