Repository nest/nest-simulator, pull requests merged in 2023-11, with the labels that each got.

#2981 Update clang-format version to 17.0.4 and activate `InsertBraces`
  .clang-format
  .github/workflows/nestbuildmatrix.yml
  .pre-commit-config.yaml
  build_support/format_all_c_c++_files.sh
  doc/htmldoc/developer_space/guidelines/coding_guidelines_check.rst
  environment.yml
  nestkernel/position.h
  sli/filesystem.cc
  sli/sliregexp.cc
Labels: S: Normal, T: Maintenance, I: No breaking change

#2975 Add plantuml to docs
  .readthedocs.yml
  doc/htmldoc/conf.py
  doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
  doc/htmldoc/testuml.rst
  doc/requirements.txt
Labels: T: Enhancement, S: Normal, I: No breaking change

#2967 Copy documentation to CI artifacts
  .github/workflows/nestbuildmatrix.yml
Labels: S: Normal, T: Maintenance

#2834 Organize Python dependencies in separate requirements files
  .pre-commit-config.yaml
  environment.yml
  requirements.txt
  requirements_docs.txt
  requirements_nest_server.txt
  requirements_pynest.txt
  requirements_testing.txt
Labels: S: Normal, T: Maintenance, I: No breaking change

#2985 port test_iaf_psc_exp to py
  testsuite/pytests/sli2py_neurons/test_iaf_psc_exp.py
  testsuite/unittests/test_iaf_psc_exp.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#2955 Add a tripartite connection rule for neuron-astrocyte connectivity
  CMakeLists.txt
  build_support/generate_modelsmodule.py
  doc/htmldoc/examples/index.rst
  doc/htmldoc/static/img/astrocyte_interaction.png
  doc/htmldoc/static/img/tripartite_pool_type.svg
  doc/htmldoc/synapses/connection_management.rst
  doc/htmldoc/whats_new/v3.6/index.rst
  doc/htmldoc/whats_new/v3.7/index.rst
  models/astrocyte_lr_1994.cpp
  models/astrocyte_lr_1994.h
  nestkernel/conn_builder.cpp
  nestkernel/conn_builder.h
  nestkernel/conn_builder_factory.h
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/nest.cpp
  nestkernel/nest.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nestmodule.cpp
  nestkernel/nestmodule.h
  nestkernel/node_collection.cpp
  nestkernel/node_collection.h
  nestkernel/random_generators.h
  nestkernel/vp_manager.cpp
  pynest/examples/astrocytes/README.rst
  pynest/examples/astrocytes/astrocyte_brunel.py
  pynest/examples/astrocytes/astrocyte_interaction.py
  pynest/examples/astrocytes/astrocyte_single.py
  pynest/examples/astrocytes/astrocyte_small_network.py
  pynest/nest/lib/hl_api_connections.py
  testsuite/pytests/test_connect_tripartite_bernoulli.py
  testsuite/pytests/test_stdp_pl_synapse_hom.py
  testsuite/pytests/test_stdp_synapse.py
  testsuite/pytests/test_tripartite_connect.py
Labels: T: Enhancement, S: High, I: No breaking change

#2997 Replace assertDictContainsSubset() which has been removed in Python 3.12
  testsuite/pytests/test_helper_functions.py
  testsuite/pytests/test_sp/test_synaptic_elements.py
  testsuite/pytests/test_sp/test_update_synaptic_elements.py
  testsuite/pytests/utilities/testutil.py
Labels: T: Bug, S: High, I: No breaking change

#3011 Sort results of NEST releases on Zenodo by most recent
  doc/htmldoc/citing-nest.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3013 Fix broken links in documentation
  models/iaf_tum_2000.h
  pynest/examples/iaf_tum_2000_short_term_depression.py
  pynest/examples/iaf_tum_2000_short_term_facilitation.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3014 Add note about missing random generators for osx-arm64
  doc/htmldoc/installation/conda_forge.rst
  doc/htmldoc/nest_behavior/random_numbers.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3015 Add missing keyword to glif neuron model documentation
  models/glif_cond.h
  models/glif_psc.h
  models/glif_psc_double_alpha.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#2757 Port `test-set-start-stop-origin.sli` from Sli-2-Py
  testsuite/pytests/sli2py_recording/test_set_start_stop_origin.py
  testsuite/unittests/test_set_start_stop_origin.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#3023 Add missing links to examples in model documentation
  models/aeif_cond_alpha_astro.h
  models/amat2_psc_exp.h
  models/astrocyte_lr_1994.h
  models/glif_psc_double_alpha.h
  models/iaf_psc_exp_multisynapse.h
  models/iaf_tum_2000.h
  models/quantal_stp_synapse.h
  models/rate_connection_delayed.h
  models/rate_neuron_opn.h
  models/sic_connection.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3021 Ensure Connect() does not allow passing parameters that need to be set at the synapse-model level
  models/jonke_synapse.h
  models/stdp_dopamine_synapse.h
  models/tsodyks_synapse_hom.h
  nestkernel/connection.h
  nestkernel/connector_model.h
  nestkernel/connector_model_impl.h
  testsuite/pytests/sli2py_connect/test_common_properties_setting.py
  testsuite/unittests/test_common_props_setting.sli
Labels: T: Bug, S: High, I: No breaking change
