Repository nest/nest-simulator, pull requests merged in 2024-02, with the labels that each got.

#3085 Fix typo in documentation of ```iaf_psc_alpha```
  models/iaf_psc_alpha.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3051 Properly handle OpenMP linker flags
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
Labels: T: Bug, S: High, I: No breaking change

#3094 Add doi to the BibTeX entry
  doc/htmldoc/citing-nest.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3093 Rename the variable "Ca" in astrocyte_lr_1994 to "Ca_astro"
  doc/htmldoc/model_details/astrocyte_model_implementation.ipynb
  models/astrocyte_lr_1994.cpp
  models/astrocyte_lr_1994.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  pynest/examples/astrocytes/astrocyte_brunel.py
  pynest/examples/astrocytes/astrocyte_interaction.py
  pynest/examples/astrocytes/astrocyte_single.py
  pynest/examples/astrocytes/astrocyte_small_network.py
  testsuite/pytests/test_astrocyte.dat
  testsuite/pytests/test_astrocyte.py
  testsuite/pytests/test_sic_connection.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3097 Add detailed timers for gathering and delivering secondary events
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
Labels: T: Enhancement, S: High, I: No breaking change

#3101 Avoid MPI deadlocks on SynapseCollection.get()/set()
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/mpi/2/test_issue_3099.py
Labels: T: Bug, S: High, I: No breaking change

#3092 Ensure assert_valid_syn_id() is always called with correct thread id
  nestkernel/connection_manager.cpp
  nestkernel/model_manager.cpp
  nestkernel/model_manager.h
Labels: T: Bug, S: High, I: No breaking change

#3117 Fix tests and examples to pass Pylint test R1730
  pynest/examples/pong/pong.py
  testsuite/pytests/test_jonke_synapse.py
  testsuite/pytests/test_stdp_nn_synapses.py
Labels: S: High, T: Maintenance, I: No breaking change

#3102 Port MPI tests from SLI to Python, Part I
  testsuite/do_tests.sh
  testsuite/mpitests/issue-1957.sli
  testsuite/mpitests/test_all_to_all.sli
  testsuite/mpitests/test_mini_brunel_ps.sli
  testsuite/pytests/sli2py_mpi/README.md
  testsuite/pytests/sli2py_mpi/mpi_test_wrapper.py
  testsuite/pytests/sli2py_mpi/test_all_to_all.py
  testsuite/pytests/sli2py_mpi/test_issue_1957.py
  testsuite/pytests/sli2py_mpi/test_mini_brunel_ps.py
Labels: T: Enhancement, S: High, I: No breaking change
