Repository nest/nest-simulator, pull requests merged in 2024-03, with the labels that each got.

#3086 Update model documentation for ```iaf_psc_delta``` model
  models/iaf_psc_delta.h
Labels: T: Enhancement, S: Normal, I: No breaking change

#3127 Fix broken links in documentation
  doc/htmldoc/connect_nest/using_nest_with_music.rst
  doc/htmldoc/developer_space/guidelines/coding_guidelines_check.rst
  doc/htmldoc/developer_space/guidelines/coding_guidelines_cpp.rst
  doc/htmldoc/developer_space/guidelines/styleguide/styleguide.rst
  doc/htmldoc/developer_space/workflows/development_workflow.rst
  doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
  doc/htmldoc/developer_space/workflows/nest_with_ides.rst
  doc/htmldoc/faqs/faqs.rst
  doc/htmldoc/faqs/qa-precise-spike-times.rst
  doc/htmldoc/installation/user.rst
  doc/htmldoc/model_details/HillTononiModels.ipynb
  doc/htmldoc/model_details/aeif_models_implementation.ipynb
  doc/htmldoc/neurons/exact-integration.rst
  doc/htmldoc/neurons/simulations_with_precise_spike_times.rst
  models/aeif_psc_delta_clopath.h
  models/clopath_synapse.h
  models/glif_psc_double_alpha.h
  models/hh_cond_beta_gap_traub.h
  models/hh_psc_alpha_clopath.h
  models/sigmoid_rate_gg_1998.h
  pynest/examples/Potjans_2014/README.rst
  pynest/examples/iaf_tum_2000_short_term_depression.py
  pynest/examples/intrinsic_currents_spiking.py
  pynest/examples/sonata_example/sonata_network.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3133 Fix minor integer type mismatches
  nestkernel/mpi_manager.cpp
  nestkernel/vp_manager.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3067 Improve doc install pages
  doc/htmldoc/installation/admin.rst
  doc/htmldoc/installation/cmake_options.rst
  doc/htmldoc/installation/docker.rst
  doc/htmldoc/installation/hpc_install.rst
  doc/htmldoc/installation/index.rst
  doc/htmldoc/installation/noenv_install.rst
  doc/htmldoc/installation/user.rst
  doc/htmldoc/static/img/dev_orange.svg
  doc/htmldoc/static/img/nestdesktop022023.svg
  doc/htmldoc/static/img/nestml022023.svg
  doc/requirements.txt
Labels: T: Enhancement, S: Normal, I: No breaking change

#3121 Add a section in installation docs about running NEST with EBRAINS
  doc/htmldoc/installation/cmake_options.rst
  doc/htmldoc/installation/index.rst
  doc/htmldoc/static/css/custom.css
Labels: T: Enhancement, S: Normal, I: No breaking change

#3141 Fix broken formatting in documentation
  doc/htmldoc/installation/index.rst
  doc/htmldoc/templates/layout.html
Labels: S: Normal, T: Maintenance, I: No breaking change

#3129 Automatically adjust column widths in testsuite report
  testsuite/summarize_tests.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3138 astrocyte_lr_1994: Store result of expression evaluation in proper variable
  models/astrocyte_lr_1994.cpp
Labels: T: Bug, S: High, I: No breaking change

#3120 Fix data race in nestkernel/per_thread_bool_indicator.cpp
  nestkernel/connection_manager.cpp
  nestkernel/event_delivery_manager.cpp
  nestkernel/per_thread_bool_indicator.cpp
  nestkernel/per_thread_bool_indicator.h
  nestkernel/source_table.h
Labels: T: Bug, S: High, I: No breaking change

#3145 Stop IPython from time consuming deep inspection of NodeCollection objects
  pynest/nest/lib/hl_api_types.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3151 Add localhost ipv4 to default origins for NEST Server
  pynest/nest/server/hl_api_server.py
Labels: T: Bug, S: Normal, I: No breaking change

#3152 Fix padding around links in docs
  doc/htmldoc/static/css/custom.css
Labels: S: Normal, T: Maintenance, I: No breaking change

#3158 Correctly handle random parameters appearing in the denominator
  lib/sli/nest-init.sli
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/test_regression_issue-3156.py
Labels: T: Bug, S: High, I: No breaking change

#3103 Create NEST Extension Interface for NEST compatible with new registration scheme and unloading
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  doc/htmldoc/installation/cmake_options.rst
  nest/CMakeLists.txt
  nest/neststartup.cpp
  nestkernel/CMakeLists.txt
  nestkernel/connection_manager.cpp
  nestkernel/dynamicloader.cpp
  nestkernel/dynamicloader.h
  nestkernel/event_delivery_manager.cpp
  nestkernel/io_manager.cpp
  nestkernel/kernel_manager.cpp
  nestkernel/kernel_manager.h
  nestkernel/logging_manager.cpp
  nestkernel/manager_interface.h
  nestkernel/model_manager.cpp
  nestkernel/module_manager.cpp
  nestkernel/module_manager.h
  nestkernel/mpi_manager.cpp
  nestkernel/music_manager.cpp
  nestkernel/nest_extension_interface.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nestmodule.cpp
  nestkernel/nestmodule.h
  nestkernel/node_manager.cpp
  nestkernel/random_manager.cpp
  nestkernel/simulation_manager.cpp
  nestkernel/sp_manager.cpp
  nestkernel/vp_manager.cpp
  pynest/CMakeLists.txt
  sli/sliexceptions.h
Labels: T: Enhancement, S: High, I: External API

#2773 User configurable voltage initialization for the compartmental model
  models/cm_compartmentcurrents.cpp
  models/cm_compartmentcurrents.h
  models/cm_default.cpp
  models/cm_default.h
  models/cm_tree.cpp
  models/cm_tree.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  pynest/examples/compartmental_model/receptors_and_current.py
  pynest/examples/compartmental_model/two_comps.py
  testsuite/pytests/test_compartmental_model.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#3149 Move registration of ConnBuilders, Backends, growth curves from nestmodule to respective managers, allowing unloading
  nestkernel/connection_manager.cpp
  nestkernel/event_delivery_manager.cpp
  nestkernel/io_manager.cpp
  nestkernel/kernel_manager.cpp
  nestkernel/kernel_manager.h
  nestkernel/nest_extension_interface.h
  nestkernel/nestmodule.cpp
  nestkernel/sp_manager.cpp
Labels: T: Enhancement, S: High, I: No breaking change

#2935 Add GCC compiler problem matcher to CI
  .github/workflows/nestbuildmatrix.yml
  gcc_problem_matcher.json
Labels: S: Normal, T: Maintenance, I: No breaking change

#3153 Add link to 3.7 whats new page in docs
  doc/htmldoc/whats_new/index.rst
  doc/htmldoc/whats_new/v3.7/index.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3140 Add CMAKE option for optimizing performance of benchmarks
  doc/htmldoc/hpc/benchmarking.rst
  doc/htmldoc/installation/cmake_options.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3148 Make -Dwith-mpi respect provided path and ensure "default off" options are turned on only by explicit ON
  cmake/ProcessOptions.cmake
Labels: T: Bug, S: High, I: No breaking change
