Repository nest/nest-simulator, pull requests merged in 2024-01, with the labels that each got.

#2960 New connection rule for Poisson-distributed number of synapses between neuron pairs
  doc/htmldoc/networks/spatially_structured_networks.rst
  doc/htmldoc/synapses/connection_management.rst
  nestkernel/conn_builder.cpp
  nestkernel/conn_builder.h
  nestkernel/connection_creator.cpp
  nestkernel/connection_creator.h
  nestkernel/connection_creator_impl.h
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/nestmodule.cpp
  nestkernel/random_generators.h
  pynest/nest/lib/hl_api_connection_helpers.py
  pynest/nest/lib/hl_api_connections.py
  testsuite/pytests/connect_test_base.py
  testsuite/pytests/test_connect_pairwise_poisson.py
  testsuite/pytests/test_spatial/test_connect_layers.py
Labels: T: Enhancement, S: Normal, I: No breaking change, good first issue

#3045 Add CLion IDE developer documentation
  doc/htmldoc/developer_space/workflows/nest_with_ides.rst
  doc/htmldoc/static/css/custom.css
Labels: T: Enhancement, S: Normal, I: No breaking change

#3079 Update test failing due to removed scipy method
  testsuite/pytests/sli2py_regressions/test_ticket_903.py
Labels: S: High, T: Maintenance, I: No breaking change

#3065 Modify doc extensions to check for correct files
  doc/htmldoc/_ext/add_button_notebook.py
  doc/htmldoc/_ext/list_examples.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3077 Fix various Sphinx warnings
  doc/htmldoc/connect_nest/nest_server.rst
  doc/htmldoc/developer_space/cppcomments.rst
  doc/htmldoc/developer_space/guidelines/coding_guidelines_cpp.rst
  doc/htmldoc/examples/index.rst
  doc/htmldoc/get-started_index.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_models.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_spatial.rst
  doc/htmldoc/ref_material/pynest_api/nest.lib.hl_api_types.rst
  doc/htmldoc/whats_new/index.rst
  models/glif_psc_double_alpha.h
  models/ignore_and_fire.h
  pynest/examples/glif_psc_double_alpha_neuron.py
  pynest/nest/lib/hl_api_models.py
  pynest/nest/lib/hl_api_simulation.py
Labels: S: Normal, T: Maintenance, I: No breaking change
