Repository nest/nest-simulator, pull requests merged in 2024-12, with the labels that each got.

#3370 Update instances of conda with mamba in docs
  README.md
  doc/htmldoc/connect_nest/nest_server.rst
  doc/htmldoc/developer_space/guidelines/mailing_list_guidelines.rst
  doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
  doc/htmldoc/developer_space/workflows/nest_with_ides.rst
  doc/htmldoc/installation/conda_forge.rst
  doc/htmldoc/installation/conda_tips.rst
  doc/htmldoc/installation/condaenv_install.rst
  doc/htmldoc/installation/developer.rst
  doc/htmldoc/installation/mac_install.rst
  doc/htmldoc/installation/user.rst
  doc/htmldoc/nest_behavior/random_numbers.rst
  doc/htmldoc/troubleshooting.rst
  environment.yml
  nestkernel/CMakeLists.txt
  requirements.txt
  requirements_docs.txt
  requirements_nest_server.txt
  requirements_pynest.txt
  requirements_testing.txt
Labels: S: High, T: Maintenance, I: No breaking change

#3338 Fix parentheses in connection_helpers
  pynest/nest/lib/hl_api_connection_helpers.py
Labels: T: Bug, S: High, I: No breaking change

#3358 Update MAM benchmark on website
  doc/htmldoc/benchmark_results.rst
  doc/htmldoc/static/img/mam_benchmark.png
  doc/htmldoc/static/img/mam_ground-state_benchmark.png
  doc/htmldoc/static/img/mam_metastable-state_benchmark.png
Labels: S: Normal, T: Maintenance, I: No breaking change

#3249 Remove pointless initialisation of integration step size
  models/aeif_cond_alpha.cpp
  models/aeif_cond_alpha_astro.cpp
  models/aeif_cond_alpha_multisynapse.cpp
  models/aeif_cond_beta_multisynapse.cpp
  models/aeif_cond_exp.cpp
  models/aeif_psc_alpha.cpp
  models/aeif_psc_delta.cpp
  models/aeif_psc_delta_clopath.cpp
  models/aeif_psc_exp.cpp
  models/glif_cond.cpp
Labels: S: Normal, T: Maintenance, I: No breaking change

#3277 Update README on GitHub
  README.md
Labels: T: Enhancement, S: Normal, I: No breaking change, stale

#3379 Change doc folder name for nest server and other services
  doc/htmldoc/get-started_index.rst
  doc/htmldoc/interface_nest/index.rst
  doc/htmldoc/interface_nest/nest_server.rst
  doc/htmldoc/interface_nest/using_nest_with_music.rst
  doc/htmldoc/whats_new/v3.0/features/index.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3343 Add line number to error message
  pynest/nest/server/hl_api_server.py
Labels: T: Enhancement, S: Normal, I: No breaking change
