Repository nest/nest-simulator, pull requests merged in 2024-04, with the labels that each got.

#3170 Update docstring for pynest ResetKernel() to include module unloading
  pynest/nest/lib/hl_api_simulation.py
Labels: T: Bug, S: Normal, I: No breaking change

#3172 Align documentation of connection management with connectivity concepts publication (v2)
  doc/htmldoc/get-started_index.rst
  doc/htmldoc/installation/cmake_options.rst
  doc/htmldoc/nest_behavior/running_simulations.rst
  doc/htmldoc/networks/spatially_structured_networks.rst
  doc/htmldoc/static/css/custom.css
  doc/htmldoc/static/img/All_to_all.png
  doc/htmldoc/static/img/All_to_all_H.png
  doc/htmldoc/static/img/Autapse.png
  doc/htmldoc/static/img/Autapse_H.png
  doc/htmldoc/static/img/Autapse_multapse.png
  doc/htmldoc/static/img/Autapse_multapse_v.png
  doc/htmldoc/static/img/Connection_overview.png
  doc/htmldoc/static/img/Fixed_indegree.png
  doc/htmldoc/static/img/Fixed_indegree_H.png
  doc/htmldoc/static/img/Fixed_outdegree.png
  doc/htmldoc/static/img/Fixed_outdegree_H.png
  doc/htmldoc/static/img/Fixed_total_number.png
  doc/htmldoc/static/img/Fixed_total_number_H.png
  doc/htmldoc/static/img/Multapse.png
  doc/htmldoc/static/img/Multapse_H.png
  doc/htmldoc/static/img/One_to_one.png
  doc/htmldoc/static/img/One_to_one_H.png
  doc/htmldoc/static/img/Pairwise_bernoulli.png
  doc/htmldoc/static/img/Pairwise_bernoulli_H.png
  doc/htmldoc/synapses/connection_generator.rst
  doc/htmldoc/synapses/connectivity_concepts.rst
  doc/htmldoc/synapses/handling_connections.rst
  doc/htmldoc/synapses/synapse_specification.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_3_connecting_networks_with_synapses.rst
  doc/htmldoc/whats_new/v3.7/index.rst
  models/multimeter.h
  pynest/nest/lib/hl_api_connections.py
Labels: T: Enhancement, S: High, I: No breaking change

#3028 Add EI_clustered_network by Rostami et al to PyNEST examples
  doc/htmldoc/examples/index.rst
  doc/htmldoc/static/img/pynest/EI_clustered_network_schematic.png
  pynest/examples/EI_clustered_network/README.rst
  pynest/examples/EI_clustered_network/helper.py
  pynest/examples/EI_clustered_network/network.py
  pynest/examples/EI_clustered_network/network_params.py
  pynest/examples/EI_clustered_network/run_simulation.py
  pynest/examples/EI_clustered_network/sim_params.py
  pynest/examples/EI_clustered_network/stimulus_params.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#3175 Fix MUSIC support in NEST
  .github/workflows/nestbuildmatrix.yml
  models/music_cont_in_proxy.cpp
  models/music_cont_in_proxy.h
  models/music_cont_out_proxy.cpp
  models/music_cont_out_proxy.h
  models/music_event_in_proxy.cpp
  models/music_event_in_proxy.h
  models/music_event_out_proxy.cpp
  models/music_event_out_proxy.h
  models/music_message_in_proxy.cpp
  models/music_message_in_proxy.h
  models/music_rate_in_proxy.cpp
  models/music_rate_in_proxy.h
  models/music_rate_out_proxy.cpp
  models/music_rate_out_proxy.h
  nestkernel/music_manager.cpp
  nestkernel/music_manager.h
  testsuite/do_tests.sh
Labels: T: Bug, S: High, I: No breaking change

#3159 Clarify documentation related to recorders and recording backends
  doc/htmldoc/devices/index.rst
  doc/htmldoc/devices/record_from_simulations.rst
  models/multimeter.h
  models/spike_recorder.h
  models/weight_recorder.h
  nestkernel/recording_backend_ascii.h
  nestkernel/recording_backend_memory.h
  nestkernel/recording_backend_mpi.h
  nestkernel/recording_backend_screen.h
  nestkernel/recording_backend_sionlib.h
  nestkernel/recording_device.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3189 Improve glossary references in documentation
  doc/htmldoc/hpc/parallel_computing.rst
  doc/htmldoc/tutorials/music_tutorial/music_tutorial_1.rst
  doc/htmldoc/tutorials/pynest_tutorial/part_3_connecting_networks_with_synapses.rst
Labels: S: Normal, T: Maintenance, I: No breaking change
