Repository nest/nest-simulator, pull requests merged in 2024-08, with the labels that each got.

#3267 Add whats new link for 3.8
  doc/htmldoc/whats_new/index.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3268 Fix minor typo in documentation
  models/iaf_cond_beta.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3253 Add OpenSSF Scorecard badge to README
  README.md
Labels: S: Normal, T: Maintenance, I: No breaking change

#3240 Add deprecation notice to `iaf_cond_alpha_mc` model documentation
  models/iaf_cond_alpha_mc.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3203 Modify model directory documentation UI and related pages
  .pre-commit-config.yaml
  doc/htmldoc/.gitignore
  doc/htmldoc/_ext/extractor_userdocs.py
  doc/htmldoc/_ext/model_tag_setup.py
  doc/htmldoc/clean_source_dirs.py
  doc/htmldoc/conf.py
  doc/htmldoc/developer_space/sli_docs/neural-simulations.rst
  doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
  doc/htmldoc/devices/index.rst
  doc/htmldoc/get-started_index.rst
  doc/htmldoc/models/.gitignore
  doc/htmldoc/models/index.rst
  doc/htmldoc/models/models-main.rst
  doc/htmldoc/models/models-toc.rst
  doc/htmldoc/neurons/index.rst
  doc/htmldoc/neurons/node_handles.rst
  doc/htmldoc/static/css/filter_models.css
  doc/htmldoc/static/js/filter_models.js
  doc/htmldoc/synapses/connection_generator.rst
  doc/htmldoc/synapses/index.rst
  doc/htmldoc/synapses/synapse_specification.rst
  doc/htmldoc/whats_new/v3.6/index.rst
  doc/htmldoc/whats_new/v3.7/index.rst
  models/diffusion_connection.h
  models/iaf_tum_2000.h
Labels: T: Enhancement, S: Normal, I: No breaking change

#3274 Fix links in documentation
  doc/htmldoc/index.rst
  doc/htmldoc/models/index.rst
  doc/htmldoc/static/img/excalidraw_nestconcept_horiz.svg
Labels: S: Normal, T: Maintenance, I: No breaking change

#3275 Fix minor issues in docs
  doc/htmldoc/neurons/exact-integration.rst
  doc/htmldoc/synapses/connectivity_concepts.rst
  doc/htmldoc/synapses/index.rst
  models/iaf_bw_2001.h
  models/iaf_bw_2001_exact.h
  models/iaf_psc_exp.h
  pynest/examples/one_neuron_with_noise.py
  pynest/examples/wang_decision_making.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3282 Update documentation for mailing list guidelines
  doc/htmldoc/developer_space/guidelines/mailing_list_guidelines.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3272 Fix memory safety issue in slistartup.cc
  nestkernel/connection_creator_impl.h
  sli/parser.h
  sli/slistartup.cc
Labels: T: Bug, S: Normal, I: No breaking change

#3284 Configure Sphinx gallery to copy files from `pynest/examples`
  doc/htmldoc/conf.py
  doc/htmldoc/examples/index.rst
  pynest/examples/EI_clustered_network/EI_clustered_network_schematic.png
  pynest/examples/EI_clustered_network/README.rst
  pynest/examples/Potjans_2014/README.rst
  pynest/examples/Potjans_2014/potjans_2014_box_plot.png
  pynest/examples/Potjans_2014/potjans_2014_microcircuit.png
  pynest/examples/Potjans_2014/potjans_2014_raster_plot.png
  pynest/examples/eprop_plasticity/README.rst
  pynest/examples/eprop_plasticity/eprop_supervised_classification_evidence-accumulation.py
  pynest/examples/eprop_plasticity/eprop_supervised_regression_handwriting.py
  pynest/examples/eprop_plasticity/eprop_supervised_regression_infinite-loop.py
  pynest/examples/eprop_plasticity/eprop_supervised_regression_sine-waves.py
  pynest/examples/hpc_benchmark.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3295 Fix Read the Docs warning about JavaScript search functionality
  doc/htmldoc/static/js/jquery-3.6.0.min.js
  doc/htmldoc/static/js/jquery-ui.min.js
  doc/htmldoc/static/js/particles-app.js
  doc/htmldoc/static/js/tsparticles.min.js
  doc/htmldoc/templates/layout.html
Labels: S: Normal, T: Maintenance, I: No breaking change

#3285 Update boost detection and issue warning message
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
Labels: S: Normal, T: Maintenance, I: No breaking change
