Repository nest/nest-simulator, pull requests merged in 2025-02, with the labels that each got.

#3378 Add optional support for per-thread timers and timing MPI synchronization
  CMakeLists.txt
  cmake/ConfigureSummary.cmake
  cmake/ProcessOptions.cmake
  doc/htmldoc/developer_space/guidelines/coding_guidelines_cpp.rst
  doc/htmldoc/installation/cmake_options.rst
  doc/htmldoc/nest_behavior/built-in_timers.rst
  libnestutil/CMakeLists.txt
  libnestutil/config.h.in
  libnestutil/stopwatch.cpp
  libnestutil/stopwatch.h
  nestkernel/CMakeLists.txt
  nestkernel/connection_manager.cpp
  nestkernel/connection_manager.h
  nestkernel/event_delivery_manager.cpp
  nestkernel/event_delivery_manager.h
  nestkernel/kernel_manager.cpp
  nestkernel/kernel_manager.h
  nestkernel/module_manager.h
  nestkernel/mpi_manager.cpp
  nestkernel/nest_names.cpp
  nestkernel/nest_names.h
  nestkernel/node_manager.cpp
  nestkernel/node_manager.h
  nestkernel/per_thread_bool_indicator.cpp
  nestkernel/simulation_manager.cpp
  nestkernel/simulation_manager.h
  nestkernel/source_table.cpp
  nestkernel/stimulation_backend_mpi.cpp
  nestkernel/stopwatch.h
  nestkernel/stopwatch_impl.h
Labels: S: Normal, I: No breaking change

#3404 Check if dot binary exists
  testsuite/pytests/test_visualization.py
Labels: T: Bug, S: Normal, I: No breaking change

#3299 Allow passing OpenMP root directory to -Dwith-openmp
  .github/workflows/nestbuildmatrix.yml
  cmake/ConfigureSummary.cmake
  cmake/FindSIONlib.cmake
  cmake/ProcessOptions.cmake
Labels: T: Bug, S: High, I: No breaking change, stale

#3234 Update C++ docstrings for extended histentry
  models/clopath_synapse.h
  nestkernel/histentry.h
Labels: S: Normal, T: Maintenance, I: No breaking change

#3403 Remove deprecated environment variable from SLI init script
  lib/sli/nest-init.sli
Labels: S: Normal, T: Maintenance, I: No breaking change

#3365 Add logger for nest-server-mpi
  bin/nest-server-mpi
  pynest/nest/server/hl_api_server.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#2752 Port `aeif_cond_beta_multisynapse_test` from SLI-2-Py and add test for `..._alpha_...`
  testsuite/pytests/conftest.py
  testsuite/pytests/test_aeif_cond_alpha_multisynapse.py
  testsuite/pytests/test_aeif_cond_beta_multisynapse.py
  testsuite/unittests/test_aeif_cond_beta_multisynapse.sli
Labels: S: Normal, T: Maintenance, I: No breaking change
