Repository nest/nest-simulator, pull requests merged in 2025-03, with the labels that each got.

#3423 Correctly detect that substring was not found
  sli/slidata.cc
Labels: T: Bug, S: High, I: No breaking change

#3420 Move critical section so it can be avoided by limiting verbosity
  sli/interpret.cc
Labels: S: High, T: Maintenance, I: No breaking change

#3382 Port test_count_connections from SLI to Py
  testsuite/pytests/sli2py_connect/test_count_connections.py
  testsuite/unittests/test_count_connections.sli
Labels: S: Normal, T: Maintenance, I: No breaking change, stale

#3429 Add NEAT to related projects in docs
  doc/htmldoc/conf.py
  doc/htmldoc/index.rst
  doc/htmldoc/related_projects.rst
Labels: S: Normal, T: Maintenance, I: No breaking change

#3427 Fix sphinx warnings in docs
  doc/htmldoc/_ext/list_examples.py
  doc/htmldoc/_ext/model_tag_setup.py
  doc/htmldoc/community.rst
  doc/htmldoc/conf.py
  doc/htmldoc/developer_space/index.rst
  doc/htmldoc/examples/index.rst
  doc/htmldoc/get-started_index.rst
  doc/htmldoc/hpc/optimizing_nest.rst
  doc/htmldoc/installation/developer.rst
  doc/htmldoc/nest_behavior/built-in_timers.rst
  doc/htmldoc/related_projects.rst
  doc/htmldoc/whats_new/index.rst
  doc/htmldoc/whats_new/v3.0/features/index.rst
  doc/htmldoc/whats_new/v3.7/index.rst
  pynest/examples/astrocytes/astrocyte_small_network.py
  pynest/examples/eprop_plasticity/eprop_supervised_regression_handwriting_bsshslm_2020.py
  pynest/examples/eprop_plasticity/eprop_supervised_regression_lemniscate_bsshslm_2020.py
  pynest/nest/lib/hl_api_connections.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3434 Simplify handling of OTHER labels in new-style mpitests
  testsuite/pytests/sli2py_mpi/mpi_test_wrapper.py
  testsuite/pytests/sli2py_mpi/test_all_to_all.py
  testsuite/pytests/sli2py_mpi/test_issue_1957.py
  testsuite/pytests/sli2py_mpi/test_mini_brunel_ps.py
Labels: T: Enhancement, S: High, I: No breaking change

#3436 Port mpitests/issue-281.sli to Python
  testsuite/mpitests/issue-281.sli
  testsuite/pytests/sli2py_mpi/mpi_test_wrapper.py
  testsuite/pytests/sli2py_mpi/test_issue_2119.py
  testsuite/pytests/sli2py_mpi/test_issue_281.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#3433 Derive astrocyte_lr_1994 directly from Node
  models/astrocyte_lr_1994.cpp
  models/astrocyte_lr_1994.h
  pynest/examples/astrocytes/astrocyte_brunel_fixed_indegree.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3437 Port mpitests/issue_600.sli to Pytests
  testsuite/mpitests/issue-600.sli
  testsuite/pytests/sli2py_mpi/test_issue_600.py
Labels: S: Normal, T: Maintenance, I: No breaking change

#3438 Port test_gap_junctions_mpi from SLI to Py
  testsuite/mpitests/test_gap_junctions_mpi.sli
  testsuite/pytests/sli2py_mpi/test_gap_junctions_mpi.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#3447 Handle CalledProcessError better
  pynest/nest/lib/hl_api_types.py
  testsuite/pytests/sli2py_mpi/mpi_test_wrapper.py
  testsuite/pytests/sli2py_mpi/test_self_get_conns_with_empty_ranks.py
Labels: T: Enhancement, S: Normal, I: No breaking change

#3451 Fix incorrect initialization in move constructor
  models/eprop_synapse.h
Labels: T: Bug, S: High, I: No breaking change
